function s = ar_state_at(P, k, tag)
%AR_STATE_AT  Every quantity the report compares, at one iteration.
if isempty(k) || isnan(k)
    s = struct('tag',tag,'iter',NaN,'move',NaN,'l2',NaN,'rms',NaN,'maxAbs',NaN, ...
        'ratio',NaN,'omega1',NaN,'omega2',NaN,'gap12',NaN,'Mnd',NaN,'gray',NaN, ...
        'mid',NaN,'volume',NaN,'itersSinceMoveChange',NaN,'stage',NaN);
    return
end
s = struct('tag',tag,'iter',k,'move',P.move(k),'l2',P.l2(k),'rms',P.rms(k), ...
    'maxAbs',P.maxAbs(k),'ratio',P.ratio(k),'omega1',P.omega1(k), ...
    'omega2',P.omega2(k),'gap12',P.gap12(k),'Mnd',P.Mnd(k),'gray',P.gray(k), ...
    'mid',P.mid(k),'volume',P.volume(k), ...
    'itersSinceMoveChange',P.itersSinceMoveChange(k),'stage',P.stage(k));
end
