function paths = olhoffm4_forbidden_paths()
%OLHOFFM4_FORBIDDEN_PATHS  Olhoff implementations that must never execute here.
%
%   Every path below is a SUPERSEDED or HISTORICAL Du-Olhoff realization kept in
%   this repository for provenance.  None of them is the conference-active
%   reconstruction, and the conference benchmark fails closed if execution ever
%   resolves into one.  The classification of each is in
%   analysis/OLHOFF_IMPLEMENTATION_STATUS.md.
%
%   Paths are repository-relative and matched as prefixes of the resolved
%   file location.

paths = { ...
    fullfile('analysis', 'OlhoffApproach'), ...
    fullfile('analysis', 'OlhoffApproachExact'), ...
    fullfile('analysis', 'OlhoffApproachExactOpus'), ...
    fullfile('analysis', 'OlhoffRegularized'), ...
    fullfile('analysis', 'OlhoffReproduced2007'), ...
    fullfile('analysis', 'olhoff_stabilization_audit'), ...
    fullfile('analysis', 'olhoff_fixed_budget_audit'), ...
    fullfile('analysis', 'olhoff_native_convergence'), ...
    fullfile('analysis', 'olhoff_nested_mma_route_audit'), ...
    fullfile('analysis', 'olhoff_practical_convergence_audit'), ...
    fullfile('Matlab', 'reproduction2007') };
end
