function [cfg, meta] = olhoffm4_config(nelx, nely, varargin)
%OLHOFFM4_CONFIG  The FROZEN conference configuration of the Du-Olhoff (M4) reconstruction.
%
%   cfg = OLHOFFM4_CONFIG(nelx, nely) returns the configuration struct that the
%   imported solver is run with for the conference performance benchmark.  It
%   is the realization frozen by
%
%       audit_conference_admission/WP4_frozen_realization.m|md   (M4 + filter)
%       audit_filter_mesh_admission/FROZEN_REALIZATION.json      (R = 0.06)
%       audit_termination_mesh_admission/wp8_run.m               (outer guard)
%
%   in the source repository /Users/piotrek/Programming/Matlab/Olhoff, and it
%   reproduces the field set and the field values of TMA_FROZEN_CFGS.mat
%   exactly.  Nothing here is tuned, selected or swept.
%
%   Name/value options:
%     'Diag'      (default false)  per-iteration diagnostic recorder.  The
%                 audited runs set it TRUE.  It is PURELY ADDITIVE and proved
%                 bitwise inert, but it costs measurable time per outer
%                 iteration, so the performance benchmark runs it OFF and the
%                 preflight proves the trajectory is unchanged either way.
%                 This is the ONLY benchmark-vs-audit configuration difference.
%     'MaxOuter'  (default 400)    safety cap.  A run that reaches it is NOT
%                 converged.  Overriding it marks the run as non-scientific.
%     'Name'      (default sprintf('OLHOFF_M4_%dx%d', nelx, nely))
%
%   meta records the provenance and the epistemic caveat that must travel with
%   every number this configuration produces.
%
%   THE LABEL.  This is the "Du-Olhoff reconstruction (M4)".  It must NOT be
%   called "Olhoff 2007": numerical continuation and inner-convergence details
%   are incompletely specified in the original publication.
%
%   See also OLHOFFM4_RUN, OLHOFFM4_PATHS.

p = inputParser();
p.addRequired('nelx', @(v) isnumeric(v) && isscalar(v) && v > 0 && mod(v,1) == 0);
p.addRequired('nely', @(v) isnumeric(v) && isscalar(v) && v > 0 && mod(v,1) == 0);
p.addParameter('Diag', false, @(v) islogical(v) && isscalar(v));
p.addParameter('MaxOuter', 400, @(v) isnumeric(v) && isscalar(v) && v >= 1);
p.addParameter('Name', '', @(v) ischar(v) || isstring(v));
p.parse(nelx, nely, varargin{:});
opt = p.Results;

nelx = double(opt.nelx);
nely = double(opt.nely);
assert(mod(nely, 2) == 0, 'olhoffm4_config:OddNely', ...
    ['The simply-supported idealization pins the supports at MID HEIGHT, ' ...
     'which requires an even nely (got %d).'], nely);

name = char(string(opt.Name));
if isempty(name); name = sprintf('OLHOFF_M4_%dx%d', nelx, nely); end

% ---- the frozen realization, field for field ---------------------------
cfg = struct( ...
    ... % domain and material
    'a', 8, 'b', 1, 't', 1, 'E', 1e7, 'nu', 0.3, 'rhom', 1, ...
    'nelx', nelx, 'nely', nely, ...
    'bc', 'a', 'support', 'mid', 'axial', 'both', ...
    'elemType', 'Q4', 'massType', 'consistent', ...
    ... % SIMP: p = 3 constant, no continuation; mass law eq. (4b), C^1
    'p', 3, 'massInterp', '4b', 'rhomin', 1e-3, 'rho0', 0.5, 'volfrac', 0.5, ...
    ... % problem: maximize omega_1, five modes computed
    'n', 1, 'Nmax', 4, ...
    ... % filter: FIXED PHYSICAL radius R = 0.06*b, rminEl DERIVED by olhoffOpt
    'rminEl', NaN, 'rminPhys', 0.06, 'filterMode', 'all', ...
    ... % multiplicity: M4 -- no classifier, fixed subspace window subN = 2
    'tolMult', 0.05, 'multRule', 'subspace', 'subN', 2, ...
    ... % step control: S2 staged ladder.  s2Signal is deliberately ABSENT, so
    ... % moveControl uses its legacy 'beta' signal -- the design-driven 'drms'
    ... % trigger was measured and NOT adopted (audit_s2_design_continuation).
    'move', 0.04, 'moveFamily', 'S2', 'moveMin', 0.002, ...
    's1Gamma', 0.97, 's1AfterCoal', true, ...
    's2Levels', [0.04 0.02 0.01 0.005], 's2Window', 10, 's2Tol', 5e-3, ...
    's3Lo', 0.30, 's3Hi', 0.70, 's3Down', 0.7, 's3Up', 1.1, ...
    ... % inner loop: GENUINE NESTED sub-optimization by MMA
    'offDiag', true, 'innerSolver', 'mma', 'mmaVariant', 'published', ...
    'innerVar', 'drho', 'maxInner', 500, 'tolInner', 0.05, 'minInner', 5, ...
    ... % outer stop: ||drho||_2 < tolOuter, with tolOuter scaled so the
    ... % PER-ELEMENT (RMS) density tolerance is mesh-independent, and the
    ... % settled-move guard that refuses to read the test on an iteration
    ... % where the move ladder just changed.
    'maxOuter', double(opt.MaxOuter), 'tolOuter', NaN, ...
    'outerNorm', 'l2', 'outerGuard', 'settledmove', ...
    ... % numerics
    'solver', 'eigs', 'threads', 1, 'verbose', false, ...
    'diag', logical(opt.Diag), 'name', name);

% tolOuter: 0.05 at 160x20, scaled as 0.05*sqrt(NE/3200).
NE = nelx*nely;
cfg.tolOuter = 0.05*sqrt(NE/3200);

% Derived filter radius, asserted rather than assumed.
rminElDerived = cfg.rminPhys/(cfg.b/cfg.nely);
assert(abs(rminElDerived - 0.06*nely) < 1e-12, 'olhoffm4_config:FilterRadius', ...
    'Derived rminEl = %.17g does not match R/(b/nely).', rminElDerived);

meta = struct( ...
    'label', 'Du-Olhoff reconstruction (M4)', ...
    'must_not_be_labelled', 'Olhoff 2007', ...
    'epistemic_class', 'reconstruction (class C): internally coherent, not a claimed historical implementation', ...
    'realization_id', 'olhoff_m4_subspaceN2_R006_tolInner005_S2beta_settledmove_v1', ...
    'source_repository', '/Users/piotrek/Programming/Matlab/Olhoff', ...
    'frozen_by', {{'audit_conference_admission/WP4_frozen_realization.md', ...
                   'audit_filter_mesh_admission/FROZEN_REALIZATION.json', ...
                   'audit_termination_mesh_admission/wp8_run.m'}}, ...
    'rmin_el_derived', rminElDerived, ...
    'r_phys', cfg.rminPhys, ...
    'eps_rms', cfg.tolOuter/sqrt(NE), ...
    'nested_inner_solver', 'MMA (Svanberg), genuine nested sub-optimization, tolInner = 0.05', ...
    's2_signal', 'beta (legacy); the design-driven ''drms'' trigger was NOT adopted', ...
    'diag_recorder', logical(opt.Diag), ...
    'caveat', olhoffm4_caveat());
end
