#!/usr/bin/env python3
"""DIFF_AUDIT.md + evidence/diff_audit.json: every changed path vs 013cc48, classified."""
import json, subprocess
W = '/Users/piotrek/Programming/topOpt4freqMax-migration-253069'
STUDY = 'analysis/OlhoffCurrent/diagnostics/upstream_253069_migration'
BASE = '013cc48451d33bed61c5c4eea174bbd898d548a2'
g = lambda *a: subprocess.run(['git', '-C', W, *a], capture_output=True, text=True).stdout
g('add', '-N', 'analysis/OlhoffCurrent', 'examples/Performance')
try:
    ns = [l.split('\t') for l in g('diff', '--numstat', BASE).splitlines()]
    st = dict(reversed(l.split('\t')) for l in g('diff', '--name-status', BASE).splitlines())
finally:
    g('reset', '-q')
bi = json.load(open(f'{W}/{STUDY}/evidence/byte_identity.json'))
up = {r['path'] for r in bi['files']}

def classify(p):
    if p.startswith('analysis/OlhoffCurrent/+impl/'):
        return ('PROMOTED_BYTE_COPY', 'byte-identical to upstream 253069 (BYTE_IDENTITY.md)')
    if p.startswith(STUDY + '/'):
        return ('STUDY_RECORD', 'this migration study (docs, scripts, compact evidence)')
    if p in ('analysis/OlhoffCurrent/SOURCE_MANIFEST.json',):
        return ('PROVENANCE', 'regenerated integrity manifest (79 files, tree 4ba9a3ae...)')
    if p in ('analysis/OlhoffCurrent/PROVENANCE.json', 'analysis/OlhoffCurrent/PROVENANCE.md', 'analysis/OlhoffCurrent/README.md', 'analysis/OlhoffCurrent/EVIDENCE_POLICY.md'):
        return ('PROVENANCE_DOCS', 'provenance/policy/readme for the promotion and named presets')
    if p.startswith('analysis/OlhoffCurrent/tests/'):
        return ('OLHOFFCURRENT_TESTS', 'updated or new OlhoffCurrent tests and fixtures')
    if p in ('analysis/OlhoffCurrent/olhoffcurrent_presets.m', 'analysis/OlhoffCurrent/olhoffcurrent_preset.m',
             'analysis/OlhoffCurrent/olhoffcurrent_production_preset.m', 'analysis/OlhoffCurrent/olhoffcurrent_config.m',
             'analysis/OlhoffCurrent/olhoffcurrent_caveat.m'):
        return ('PRESET_LAYER', 'named-preset registry, lookup, resolution, production event reader, per-preset caveat')
    if p in ('analysis/OlhoffCurrent/olhoffcurrent_run.m',):
        return ('PRESET_LAYER', 'named preset required; per-outer-iteration cost fields; preset-aware status notes')
    if p in ('analysis/OlhoffCurrent/olhoffcurrent_provenance.m', 'analysis/OlhoffCurrent/olhoffcurrent_currentness.m'):
        return ('PROVENANCE_CODE', 'production preset from the event log; currentness against the recorded upstream branch')
    if p == 'analysis/OlhoffCurrent/olhoffcurrent_finalization_gate.m':
        return ('EVIDENCE_GATE', 'SUPERSEDED_PRODUCTION_SOURCE rule for pinned production source across a promotion')
    if p.startswith('examples/Performance/'):
        return ('OLHOFF_HARNESS', 'Olhoff-specific benchmark harness compatibility (HARNESS_UPDATE.md)')
    return ('UNAUTHORIZED', 'outside the migration scope')

rows = []
for add, dele, path in ns:
    c, why = classify(path)
    rows.append(dict(path=path, status=st.get(path, '?'), added=add, deleted=dele, cls=c, reason=why))
summary = {}
for r in rows:
    summary[r['cls']] = summary.get(r['cls'], 0) + 1
unauth = [r for r in rows if r['cls'] == 'UNAUTHORIZED']
phase6 = [r['path'] for r in rows if any(k in r['path'] for k in ('ourApproach', 'YukselApproach', 'three_method_parametric_study', 'tools/Matlab', 'profile_freeze_manifest'))]
json.dump(dict(base=BASE, n_paths=len(rows), by_class=summary, unauthorized=unauth, phase6_paths=phase6, rows=rows),
          open(f'{W}/{STUDY}/evidence/diff_audit.json', 'w'), indent=1)

L = ['# DIFF_AUDIT — Part 18, UNAUTHORIZED_DIFF_ZERO, PHASE6_UNTOUCHED', '',
     '```', 'UNAUTHORIZED_DIFF_ZERO' if not unauth else 'UNAUTHORIZED_DIFF_PRESENT', 'PHASE6_UNTOUCHED_PASS' if not phase6 else 'PHASE6_UNTOUCHED_FAIL', '```', '',
     f'Every path that differs from `{BASE}` in the migration worktree (tracked changes + new files; git-ignored raw evidence and the read-only symlinks to the primary checkout\'s ignored evidence are excluded by `.gitignore`). Generated by `scripts/mig_diff_audit.py`; `evidence/diff_audit.json`.', '',
     '| class | paths |', '|---|---|'] + [f'| {k} | {v} |' for k, v in sorted(summary.items())] + ['',
     f'**Unauthorized paths: {len(unauth)}.** **Paths touching Proposed, Yuksel, their solvers, frozen profiles, the common evaluator or `tools/Matlab`: {len(phase6)}.**', '',
     '## Scope statements', '',
     '- **`+impl`**: only byte copies from 253069 (20 paths); no hand edit.',
     '- **Filter / MMA / multiplicity / material kernels**: changed only where upstream 253069 changed them (`fem/assemble2D.m`, `algo/genGrad.m` take the stiffness struct and `+olh/+material/stiffnessInterpolation.m` adds the Pedersen law, inert under `simp` — bitwise proven by the historical runs; `fem/eigSolve.m` options pass-through, identical defaults). `filter/*`, `mma*/*`, `algo/innerLoop.m`, `algo/multRule.m`, `algo/deltaLambda.m`, `+olh/+multi/*`, `+olh/+material/massInterpolation.m`: **untouched** (already identical).',
     '- **ρ_min, maxCluster, filter radius, p, material law values of any existing preset**: unchanged (CONFIG_HASH_TRANSITION: 81 old leaves equal for all historical configurations; `duOlhoffFrozenM4.m` byte-identical).',
     '- **p-continuation logging defect**: not repaired (`olhoffSolve.m` = upstream byte for byte).',
     '- **SOCP, C480 causal run**: not touched; no file of `c480_socp_causal_run` exists in the worktree.',
     '- **Harness**: every change is inside an Olhoff branch, an Olhoff-gated column, or an Olhoff-only record/field; the detailed CSV gains Olhoff columns that are `N/A` for other methods. The Proposed/Yuksel code paths, frozen budgets, evaluator and profile manifest are unchanged (HARNESS_UPDATE.md).',
     '- **Historical evidence**: no historical study file, campaign output or `FINAL_SHA256.txt` was edited.', '',
     '## Phase 6 — deferred (Part 18)', '',
     '| item | classification | status |', '|---|---|---|',
     '| R = 0.06 physical radius re-freeze for Proposed and Yuksel | SEPARATE BENCHMARK POLICY / SCIENTIFIC TASK | not implemented |',
     '| Pedersen treatment or Du–Olhoff cut-off in Proposed | SEPARATE BENCHMARK POLICY / SCIENTIFIC TASK | not implemented |',
     '| low-density mass changes in Proposed | SEPARATE BENCHMARK POLICY / SCIENTIFIC TASK | not implemented |',
     '| evaluator ω₁ policy across methods | SEPARATE BENCHMARK POLICY / SCIENTIFIC TASK (reporting) | not implemented |',
     '| any other benchmark-method modification | SEPARATE BENCHMARK POLICY / SCIENTIFIC TASK | none made |', '',
     '## Every changed path', '', '| status | path | +/− | class | reason |', '|---|---|---|---|---|']
study = [r for r in rows if r['cls'] == 'STUDY_RECORD']
for r in rows:
    if r['cls'] == 'STUDY_RECORD':
        continue
    L.append(f"| {r['status']} | `{r['path']}` | +{r['added']}/−{r['deleted']} | {r['cls']} | {r['reason']} |")
L.append(f"| A | `{STUDY}/**` ({len(study)} files) | new | STUDY_RECORD | this study; every file is listed with its SHA-256 in `FINAL_SHA256.txt` |")
open(f'{W}/{STUDY}/DIFF_AUDIT.md', 'w').write('\n'.join(L) + '\n')
print(json.dumps(dict(n=len(rows), by_class=summary, unauthorized=len(unauth), phase6=phase6), indent=1))
