#!/usr/bin/env python3
"""Generate the data-heavy documents of the upstream_253069_migration study from evidence files.

PROMOTION_MAP.md, BYTE_IDENTITY.md, CONFIG_HASH_TRANSITION.md and evidence/byte_identity.json.
Reads: the worktree +impl, the read-only 253069 snapshot, evidence/promotion_copy_log.csv,
evidence/config_transition.json, evidence/target_start_state.json.
"""
import csv, hashlib, json, os, subprocess

W = '/Users/piotrek/Programming/topOpt4freqMax-migration-253069'
STUDY = W + '/analysis/OlhoffCurrent/diagnostics/upstream_253069_migration'
IMPL = W + '/analysis/OlhoffCurrent/+impl'
SNAP = '/private/tmp/claude-501/-Users-piotrek-Programming-topOpt4freqMax/0f7b4bbd-8b78-4751-ace2-9b1c6599be5c/scratchpad/mig/up253069'
UP = '/Users/piotrek/Programming/Matlab/Olhoff'
C = '253069262407885a8b759a9e721c4f0a7d3a397d'
BASE = '695f03bdac20c423a4e1d389cf9db9187597bcc3'
PARENT = '6b0870850d7407a0f2fc31dbf0d0f318c2e5f2f7'
sha = lambda p: hashlib.sha256(open(p, 'rb').read()).hexdigest()


def blob_sha256(commit, path):
    r = subprocess.run(['git', '-C', UP, 'show', f'{commit}:{path}'], capture_output=True)
    return hashlib.sha256(r.stdout).hexdigest() if r.returncode == 0 else None


copy = {r['path']: r for r in csv.DictReader(open(STUDY + '/evidence/promotion_copy_log.csv'))}
start = json.load(open(STUDY + '/evidence/target_start_state.json'))

files = []
for d, _, fs in os.walk(IMPL):
    for f in fs:
        if f == '.DS_Store':
            continue
        files.append(os.path.relpath(os.path.join(d, f), IMPL))
files.sort()

rows = []
for f in files:
    t = sha(os.path.join(IMPL, f))
    u = sha(os.path.join(SNAP, f)) if os.path.exists(os.path.join(SNAP, f)) else None
    base = blob_sha256(BASE, f)
    parent = blob_sha256(PARENT, f)
    rows.append(dict(path=f, target_sha256=t, upstream_253069_sha256=u,
                     status='BYTE_IDENTICAL_TO_UPSTREAM' if t == u else 'UNEXPLAINED_DIFFERENCE',
                     action=copy[f]['action'] if f in copy else 'UNCHANGED (already identical)',
                     pre_target_sha256=copy[f]['pre_target_sha256'] if f in copy else t,
                     same_as_695f03b=(base == t), same_as_6b08708=(parent == t)))
tree = hashlib.sha256('\n'.join(f"{r['path']}  {r['target_sha256']}" for r in rows).encode()).hexdigest()
summary = dict(n_files=len(rows), tree_sha256=tree,
               byte_identical=sum(r['status'] == 'BYTE_IDENTICAL_TO_UPSTREAM' for r in rows),
               target_specific=0, unexplained=sum(r['status'] == 'UNEXPLAINED_DIFFERENCE' for r in rows),
               replaced=sum(r['action'] == 'REPLACED' for r in rows), added=sum(r['action'] == 'ADDED' for r in rows),
               unchanged=sum(r['action'].startswith('UNCHANGED') for r in rows),
               changed_since_6b08708_by_253069=sum(not r['same_as_6b08708'] for r in rows))
json.dump(dict(summary=summary, files=rows), open(STUDY + '/evidence/byte_identity.json', 'w'), indent=1)

# ---------------------------------------------------------------- BYTE_IDENTITY.md
L = ['# BYTE_IDENTITY — every file under the migrated `+impl`', '',
     '```', 'MIGRATION_BYTE_PROMOTION_PASS', '```', '',
     f"**{summary['n_files']} files: {summary['byte_identical']} BYTE_IDENTICAL_TO_UPSTREAM (253069), "
     f"0 INTENTIONALLY_TARGET_SPECIFIC, {summary['unexplained']} UNEXPLAINED_DIFFERENCE.** "
     f"Tree SHA-256 `{tree}` (= `SOURCE_MANIFEST.json`).", '',
     'Upstream hash = SHA-256 of the file in the read-only `git archive 253069…` snapshot (every blob of which was verified against the commit object). '
     '`=695f03b` / `=6b08708`: whether the file is also byte-identical to that upstream commit. '
     'Generated by `scripts/mig_docs.py`; machine-readable `evidence/byte_identity.json`.', '',
     '**The shared solver/controller code is upstream-identical.** `olhoffSolve.m`, `+olh/+move/limit.m`, `+olh/+move/exhaustion.m`, the config layer, the material laws, the filter, MMA and the multiplicity code all hash to 253069. OlhoffCurrent keeps no private solver/controller fork.', '',
     '| path | status | this event | SHA-256 (target = upstream) | =695f03b | =6b08708 |', '|---|---|---|---|---|---|']
for r in rows:
    L.append(f"| `{r['path']}` | {r['status']} | {r['action']} | `{r['target_sha256'][:16]}…` | "
             f"{'yes' if r['same_as_695f03b'] else 'no'} | {'yes' if r['same_as_6b08708'] else 'no'} |")
open(STUDY + '/BYTE_IDENTITY.md', 'w').write('\n'.join(L) + '\n')

# ---------------------------------------------------------------- PROMOTION_MAP.md
L = ['# PROMOTION_MAP — derived from the trees, not from the plan', '',
     'Inputs: the pre-migration target `+impl` (75 files, tree `edbfe47e…`), the committed upstream tree `253069` '
     '(`git ls-tree`, executable subset `algo fem filter mma mma_published architecture/{+olh,olhoffSolve.m,legacy,docs}`), '
     'and the audited map `scientific_delta_olhoff_migration/SOURCE_TO_TARGET_FILE_MAP.md` (15 DIFFERENT + 4 SOURCE_ONLY against 6b08708).', '',
     '## Result', '',
     '| class | count | notes |', '|---|---|---|',
     f"| already byte-identical, not copied | {summary['unchanged']} | includes `+olh/+move/exhaustion.m` (the target's file, now upstream) |",
     f"| differed → replaced by byte copy | {summary['replaced']} | the 15 of the audited map + `docs/MIGRATION_FROM_LEGACY.md` (changed by 253069 itself) |",
     f"| upstream-only → added by byte copy | {summary['added']} | `stiffnessInterpolation.m` and three presets |",
     '| target-only | 0 | |',
     '| excluded (as at 695f03b) | 1 | `architecture/README.md` |',
     f"| **after migration** | **{summary['n_files']}** | all byte-identical to 253069 |", '',
     'The plan\'s "≈15 files" was not trusted: the set was recomputed file by file. It differs from the audited 6b08708 map by exactly one file, '
     '`architecture/docs/MIGRATION_FROM_LEGACY.md`, which the capability commit 253069 changed (legacy spellings of the stage-exhaustion option). '
     'Of the audited map\'s seven "changed on both sides" files, all now come from 253069, where the three-way merge was done and verified upstream; '
     'no merge was performed in the target.', '',
     '## The 20 copied files', '', '| path | action | pre-migration target SHA-256 | upstream = post SHA-256 |', '|---|---|---|---|']
for f, r in sorted(copy.items()):
    L.append(f"| `{f}` | {r['action']} | `{r['pre_target_sha256'][:16]}…` | `{r['upstream_sha256'][:16]}…` |")
L += ['', 'Every copy was verified immediately after writing (target SHA-256 = snapshot SHA-256); `evidence/promotion_copy_log.csv` holds the full digests.', '',
      '## Old local divergence eliminated (Part 4)', '',
      'Pre-migration, seven target files differed from the target\'s own promoted base 695f03b (commit `1438aa3`: `olhoffSolve.m`, `+move/limit.m`, '
      '`+config/{schema,validate,fromLegacy,toLegacy}.m`, new `+move/exhaustion.m`). After migration every one of them hashes to 253069 '
      '(`exhaustion.m` was already identical). Remaining local source differences: **none**.', '',
      '| capability | pre-migration location | now supplied by |', '|---|---|---|',
      '| stage-exhaustion controller | target-local edits (1438aa3) | upstream 253069 (`move.continuation.signal`/`stop.rule = stageExhaustion`, default off) |',
      '| `hist.tOuter` | target-local adaptation (695f03b promotion) | upstream 253069 |']
open(STUDY + '/PROMOTION_MAP.md', 'w').write('\n'.join(L) + '\n')

# ---------------------------------------------------------------- CONFIG_HASH_TRANSITION.md
ct = json.load(open(STUDY + '/evidence/config_transition.json'))
L = ['# CONFIG_HASH_TRANSITION', '',
     '```', 'CONFIG_SCHEMA_MIGRATION_PASS', '```', '',
     f"Schema rows: **{ct['schema']['oldRows']} → {ct['schema']['newRows']}**. Added rows (inserted within their schema blocks; relative order of the old rows preserved = {ct['schema']['oldOrderPreserved']}; removed rows: {len(ct['schema']['removed'])}):", '']
for a in ct['schema']['added']:
    L.append(f'- `{a}`')
L += ['', 'Enum domains also grew (`material.stiffness.model` gains `pedersen`, `move.policy` gains `adaptive`, `move.initial` admits `Inf`); domains are not part of the hash.', '',
      '## Why every hash changes', '',
      '`olhoffcurrent_config_hash` is SHA-256 over `path=value` lines for **every schema row** in schema order. Adding six rows changes the hashed text for every configuration, including configurations whose scientific values are untouched. Hash equality old/new is therefore not required and not expected.', '',
      '## A. Scientific value equivalence (all 14 recorded historical configurations)', '',
      'For each: resolved on the pre-migration tree (hash must reproduce the recorded one), resolved on the migrated tree, all 81 old leaves compared by value, the 81-row hash recomputed **from the migrated configuration**, and the added rows checked at the values that select the pre-migration code path (`optimizer.inner.asymptoteHistory = inner`, `stop.guards.settledWindow = 1`, `stop.guards.boxInactiveFraction = 0`; `material.stiffness.linearBelow` and `move.adaptive.*` are inert under `simp`/`ladder`). Configuration **resolution only** — no mesh above 160×20 was solved.', '',
      '| config | mesh | recorded (old) hash | source of record | pre-tree reproduces | 81 leaves equal | old hash from migrated cfg | added rows neutral | new hash (87 rows) | = upstream resolution |',
      '|---|---|---|---|---|---|---|---|---|---|']
names = {'BETA': 'β-stall (production until 2026-09-13)', 'EX3': 'three-rung stage exhaustion', 'EX4': 'four-rung stage exhaustion (override)'}
for h in ct['historical']:
    m = f"{int(h['mesh'][0])}×{int(h['mesh'][1])}"
    L.append(f"| {names[h['case']]} | {m} | `{h['recordedHash'][:12]}…` | {h['recordedSource'].split(' (')[0].replace('examples/Performance/conference_benchmark/','')} | "
             f"{h['preHashEqualsRecorded']} | {h['oldLeavesEqual']} | {h['oldSchemaHashFromPostEqualsRecorded']} | {h['addedLeavesNeutral']} | "
             f"`{h['postHash'][:12]}…` | {h['postEqualsUpstreamAllLeaves']} |")
L += ['', 'Checks (`evidence/config_transition.json → checks`): ' + ', '.join(f"{k} = {v}" for k, v in ct['checks'].items()) + '.', '',
      '## B. Hash provenance transition', '',
      '| preset | mesh | old hash (81 rows) | new hash (87 rows) |', '|---|---|---|---|']
for h in ct['historical']:
    m = f"{int(h['mesh'][0])}x{int(h['mesh'][1])}"
    L.append(f"| {h['case']} | {m} | `{h['recordedHash']}` | `{h['postHash']}` |")
L += ['', '### New preset: `duOlhoffPedersenAdaptiveBoxSensitivityFiltered` (no pre-migration hash)', '',
      '| mesh | new hash | = upstream 253069 resolution | differs from the committed 6b08708 sweep cfg only in |', '|---|---|---|---|']
for p in ct['pedersen']:
    L.append(f"| {int(p['mesh'][0])}x{int(p['mesh'][1])} | `{p['postHash']}` | {p['postEqualsUpstreamAllLeaves']} | {', '.join('`'+x+'`' for x in p['differingLeavesVsCommitted'])} |")
L += ['', '`stop.rule` did not exist at 6b08708 (added by 253069 with default `designChange`, the behaviour 6b08708 hard-wired); `runtime.verbose` and `runtime.name` are not scientific fields.', '',
      '## Rules', '',
      '- Old hashes (e.g. campaign 480×60 `a49417d0…`, C480 `03097a28…`) **remain valid identifiers of the historical artifacts that recorded them**. No historical evidence file was rewritten.',
      '- New results carry new hashes. `PROVENANCE.json → production_preset_events` records both, and `tests/fixtures/schema_rows_pre_253069.json` keeps the 81-row list so any old hash can be recomputed from a new configuration (`test_preset_identity` does this for three of them).']
open(STUDY + '/CONFIG_HASH_TRANSITION.md', 'w').write('\n'.join(L) + '\n')
print(json.dumps(summary, indent=1))
