function mig_harness_check(outJson)
%MIG_HARNESS_CHECK  BENCHMARK_PREFLIGHT evidence: the conference harness after migration.
%   1. confbench_selftest (mechanics; sub-160 or no solve), T1..T14
%   2. confbench_preflight on the campaign method set at 160x20 -- NO SOLVE
%   3. harness smoke: the Olhoff column through confbench_method_config ->
%      confbench_run_case at 160x20 with the outer cap CUT to 3 (software only),
%      then confbench_manifest and confbench_export into a scratch directory,
%      checking the per-outer cost columns and the formulation-bearing labels.
P = mig_paths();
repo = P.repo;
restoredefaultpath;
addpath(P.scripts);
scriptDir = fullfile(repo, 'examples', 'Performance');
addpath(scriptDir);
addpath(fullfile(scriptDir, 'conference_bench'));
addpath(fullfile(repo, 'tools', 'Matlab'));
addpath(fullfile(repo, 'analysis', 'three_method_parametric_study'));
addpath(fullfile(repo, 'analysis', 'OlhoffCurrent'));
olhoffcurrent_scrub_forbidden_paths(repo);
entryThreads = maxNumCompThreads(1); %#ok<NASGU>
S = struct('when', char(datetime('now')));

% ---- 1. mechanics self-test ----------------------------------------------------
st = confbench_selftest(fullfile(P.ev, 'harness_selftest.json'));
S.selftest = struct('tests', st.tests, 'all_pass', all([st.tests.pass]), ...
    'failed_ids', {{st.tests(~[st.tests.pass]).id}}, ...
    'reported_pass_field', st.pass, ...
    'note', ['report.pass in confbench_selftest is computed before T8..T14 are appended ' ...
             '(pre-existing ordering); all_pass is recomputed over every test here']);

% ---- 2. preflight, campaign method set, 160x20, no solve ------------------------
cfg = struct('resolutions', [160 20], 'methods', struct('proposed', true, 'yuksel', true, 'olhoff', true), ...
    'singleThread', true, 'maxOuterOverride', [], 'confirmLongCampaign', false, ...
    'outputDir', tempname(), 'runLabel', 'migration_253069_preflight', 'yukselMaxIters', 5000, ...
    'runWarmup', false, 'runEvaluator', false, 'fitScaling', false);
cfg.scientificEvidence = true; cfg.performanceCampaign = false;
mc = struct();
for k = {'proposed', 'yuksel', 'olhoff'}
    mc.(k{1}) = confbench_method_config(k{1}, 160, 20);
end
pre = confbench_preflight(cfg, mc);
S.preflight = struct('pass', pre.pass, 'checks', pre.checks, 'notes', {pre.notes}, ...
    'olhoff_preset', pre.olhoff_preset, 'n_checks', numel(pre.checks), ...
    'n_failed', sum(~[pre.checks.pass]), 'failed', {{pre.checks(~[pre.checks.pass]).name}});

% ---- 3. harness smoke ----------------------------------------------------------
mcfg = confbench_method_config('olhoff', 160, 20, cfg.outputDir);
rec = confbench_run_case('olhoff', mcfg, struct('max_outer_override', 3, 'label', 'migration_harness_smoke'));
% the driver (performance_comparison.m) adds these after confbench_run_case
rec.mesh = [160 20]; rec.n_elements = 3200; rec.profile_id = mcfg.olhoff_preset;
rec.scientific_observation = false; rec.evaluator = [];
need = {'outer_time_total_s', 'outer_time_per_outer_mean_s', 'outer_time_per_outer_median_s', ...
        'outer_time_excluding_inner_per_outer_mean_s', 'eigen_time_per_outer_mean_s', ...
        'gradient_time_per_outer_mean_s', 'total_wall_time_per_outer_s', 'total_wall_time_s'};
S.smoke = struct('status', rec.status, 'ok', rec.ok, 'production_preset', rec.production_preset, ...
    'method', rec.method, 'effective_config_hash', rec.effective_config_hash, ...
    'times_fields_present', all(isfield(rec.times, need)), ...
    'outer_iterations', rec.counts.outer_iterations, 'caveat_head', rec.caveat(1:min(160, end)));
odir = fullfile(tempname(), 'harness_smoke');
cfgE = cfg; cfgE.outputDir = odir; cfgE.scientificEvidence = false; cfgE.fitScaling = false;
cfgE.methods = struct('proposed', false, 'yuksel', false, 'olhoff', true);
manifest = confbench_manifest(cfgE, struct('olhoff', mcfg), struct('olhoff', rec.resolved_implementation));
files = confbench_export(cfgE, rec, manifest, confbench_scaling_fit(cfgE, rec));
det = fileread(files.detailed_csv); notes = fileread(files.notes_md); prim = fileread(files.primary_csv);
schema = jsondecode(fileread(files.schema_json));
S.export = struct( ...
    'detailed_has_per_outer_columns', contains(det, 'olhoff_total_wall_time_per_outer_s') && ...
        contains(det, 'olhoff_eigen_time_per_outer_mean_s') && contains(det, 'olhoff_preset'), ...
    'detailed_preset_cell', contains(det, 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered'), ...
    'notes_has_cost_per_outer_table', contains(notes, 'Cost per outer iteration'), ...
    'notes_header_is_formulation_label', contains(notes, '## Du-Olhoff reconstruction (Pedersen stiffness + linear mass, adaptive box)'), ...
    'no_M4_label_in_new_outputs', ~contains(notes, 'reconstruction (M4):') && ~contains(prim, 'Du-Olhoff reconstruction (M4),'), ...
    'timing_schema_key', isfield(schema.methods, 'DuOlhoffReconstruction') && ~isfield(schema.methods, 'DuOlhoffReconstructionM4'), ...
    'timing_schema_preset', schema.methods.DuOlhoffReconstruction.preset, ...
    'manifest_benchmark_preset', manifest.olhoff_implementation.benchmark_olhoff_preset, ...
    'manifest_production_preset', manifest.olhoff_implementation.production_preset);
S.pass = S.selftest.all_pass && S.preflight.pass && strcmp(S.smoke.status, 'CAP_HIT') && ...
    ~S.smoke.ok && strcmp(S.smoke.production_preset, 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered') && ...
    S.smoke.times_fields_present && all(structfun(@(v) ~islogical(v) || v, S.export));
fid = fopen(outJson, 'w'); fwrite(fid, jsonencode(S, 'PrettyPrint', true)); fclose(fid);
fprintf('HARNESS selftest=%d preflight=%d (%d checks, %d failed) smoke=%s export=%d PASS=%d\n', ...
    S.selftest.all_pass, S.preflight.pass, S.preflight.n_checks, S.preflight.n_failed, S.smoke.status, ...
    all(structfun(@(v) ~islogical(v) || v, S.export)), S.pass);
if ~S.preflight.pass, disp(S.preflight.failed.'); end
for i = 1:numel(st.tests), fprintf('  [%d] %s %s\n', st.tests(i).pass, st.tests(i).id, st.tests(i).detail); end
end
