function R = olhoffcurrent_presets()
%OLHOFFCURRENT_PRESETS  The registry of named OlhoffCurrent scientific presets.
%
%   R = OLHOFFCURRENT_PRESETS() returns one struct per CANONICAL preset.  Each is
%   a distinct scientific formulation or controller realization, named by what
%   distinguishes it mathematically -- the low-density material law, the outer
%   move controller and stop, and the filter -- and never by an audit code.
%
%   The shared solver lives in +impl/ and is byte-identical to upstream
%   Olhoff@253069262407885a8b759a9e721c4f0a7d3a397d.  Presets are how science is
%   selected; nothing here restates mathematics.  Each entry names the promoted
%   upstream preset it delegates to plus, where a realization was only ever run
%   as upstream preset + overrides, exactly those overrides.
%
%   THE THREE PRESETS
%   -----------------
%   duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered
%       The HISTORICAL OlhoffCurrent formulation: SIMP rho^3, eq. (4b) mass,
%       four-rung move ladder advanced by the beta stall, settled-move
%       design-change stop.  Production 2026-09-07 .. 2026-09-13 under the name
%       duOlhoffFixedPenaltySensitivityFiltered, which remains its compatibility
%       alias and can resolve to nothing else.
%
%   duOlhoffSimpEq4bThreeRungStageExhaustionSensitivityFiltered
%       HISTORICAL DIAGNOSTIC: the same formulation under the three-rung
%       stage-exhaustion controller of the C320/C480/C800 studies.  Validated
%       locally, never promoted, not production-eligible.
%
%   duOlhoffPedersenAdaptiveBoxSensitivityFiltered
%       The successful upstream sweep formulation: Pedersen (2000) low-density
%       stiffness, linear mass, per-element adaptive move box, natural design-
%       change stop.  A DISTINCT scientific formulation -- not a bug fix of the
%       eq. (4b) presets.
%
%   Which preset is production is NOT decided here; it is the latest event in
%   PROVENANCE.json production_preset_events (see OLHOFFCURRENT_PRODUCTION_PRESET).
%
%   ALIASES
%   -------
%     compatibilityAliases  names that RESOLVE to this preset (API continuity)
%     historicalAliases     audit codes and run labels.  PROVENANCE ONLY: they
%                           match old evidence to this preset and are refused
%                           as preset names.
%
%   See also OLHOFFCURRENT_PRESET, OLHOFFCURRENT_CONFIG, OLHOFFCURRENT_PRODUCTION_PRESET.

upstream = '253069262407885a8b759a9e721c4f0a7d3a397d';

common = struct( ...
    'filter',       'Sigmund (1997) sensitivity filter on every f_sk, fixed physical radius R = 0.06', ...
    'multiplicity', 'fixed subspace N = 2, diagonal offsets and off-diagonals retained in (25d)', ...
    'optimizer',    'published MMA on the increment, tol 0.05, 5..500 sub-iterations, state reset every outer iteration', ...
    'penalty',      'p = 3 fixed (no p continuation)');

R = struct([]);

% ---- A. historical beta-stall formulation --------------------------------
e = struct();
e.name                 = 'duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered';
e.upstreamPreset       = 'duOlhoffFrozenM4';
e.upstreamCommit       = upstream;
e.overrides            = {};
e.runtimeDefaults      = struct('maxOuter', 400);
e.classification       = 'SCIENTIFIC_PRESET';
e.role                 = 'HISTORICAL_FORMULATION';
e.productionEligible   = true;
e.formulationFamily    = 'SIMP_EQ4B';
e.displayName          = 'Du-Olhoff reconstruction (SIMP + eq. 4b mass, beta-stall ladder)';
e.label                = ['Du-Olhoff reconstruction, SIMP p = 3 with eq. (4b) mass, ' ...
                          'beta-stall move ladder, sensitivity filtered'];
e.formulation = struct( ...
    'stiffness',   'SIMP rho^3 at every density (material.stiffness.model = simp)', ...
    'mass',        'eq. (4b): C1 low-density cut-off below rho = 0.1, r = 6 (material.mass.model = eq4b)', ...
    'controller',  ['global move ladder [0.04 0.02 0.01 0.005]; descends when the bound ' ...
                    'variable beta stalls (window 10, tolerance 5e-3)'], ...
    'stopRule',    ['||drho||_2 < eps = 0.05*sqrt(NE/3200), asserted only when the move limit ' ...
                    'is unchanged from the previous iteration (stop.rule = designChange, settledMove)'], ...
    'stageExhaustion', 'off', ...
    'filter', common.filter, 'multiplicity', common.multiplicity, ...
    'optimizer', common.optimizer, 'penalty', common.penalty);
e.compatibilityAliases = {'duOlhoffFixedPenaltySensitivityFiltered'};
e.historicalAliases    = {'M4', 'TMA', 'B0', 'REG160', 'duOlhoffFrozenM4', 'A1_frozen160'};
e.evidence = { ...
    'examples/Performance/conference_benchmark/campaign_9mesh_r2 (2026-09-11 nine-mesh campaign, this preset)', ...
    'analysis/OlhoffM4Reconstruction (frozen conference realization; bitwise at 160x20 and 320x40)', ...
    'upstream architecture/anchors/reference/A1_frozen160 (science digest 1afe4b7e...)'};
e.mustNotBeLabelled    = 'Olhoff 2007';
e.epistemicClass       = 'reconstruction (class C): internally coherent, not a claimed historical implementation';
e.distinctFrom         = ['duOlhoffPedersenAdaptiveBoxSensitivityFiltered in the low-density material ' ...
                          'law (SIMP + eq. 4b vs Pedersen + linear mass) and in the outer controller/stop'];
R = [R, e];

% ---- A'. historical three-rung stage-exhaustion controller ----------------
e = struct();
e.name                 = 'duOlhoffSimpEq4bThreeRungStageExhaustionSensitivityFiltered';
e.upstreamPreset       = 'duOlhoffFrozenM4';
e.upstreamCommit       = upstream;
e.overrides            = {'move.levels', [0.04 0.02 0.01], ...
                          'move.continuation.signal', 'stageExhaustion', ...
                          'stop.rule', 'stageExhaustion'};
e.runtimeDefaults      = struct('maxOuter', 1600);
e.classification       = 'HISTORICAL_DIAGNOSTIC_PRESET';
e.role                 = 'HISTORICAL_DIAGNOSTIC';
e.productionEligible   = false;
e.formulationFamily    = 'SIMP_EQ4B';
e.displayName          = 'Du-Olhoff reconstruction (SIMP + eq. 4b mass, three-rung stage exhaustion)';
e.label                = ['Du-Olhoff reconstruction, SIMP p = 3 with eq. (4b) mass, three-rung ' ...
                          'stage-exhaustion ladder, sensitivity filtered (historical diagnostic)'];
e.formulation = struct( ...
    'stiffness',   'SIMP rho^3 at every density (material.stiffness.model = simp)', ...
    'mass',        'eq. (4b): C1 low-density cut-off below rho = 0.1, r = 6 (material.mass.model = eq4b)', ...
    'controller',  ['global move ladder [0.04 0.02 0.01]; descends one rung per stage-exhaustion ' ...
                    'declaration E = A OR B (W = P = 20, Wnp = 10, stage-local windows)'], ...
    'stopRule',    ['terminal stage-exhaustion declaration at the last rung (stop.rule = ' ...
                    'stageExhaustion); the design-change test and its guards are replaced'], ...
    'stageExhaustion', 'on (move transitions and terminal admission)', ...
    'filter', common.filter, 'multiplicity', common.multiplicity, ...
    'optimizer', common.optimizer, 'penalty', common.penalty);
e.compatibilityAliases = {};
e.historicalAliases    = {'TR3_C', 'TR3_C_320x40', 'CAN3_480x60', 'CAN3_800x100', 'EX3_160'};
e.evidence = { ...
    'analysis/OlhoffCurrent/diagnostics/three_rung_promotion_validation_retry1 (C320, cfgHash afad9ea4...)', ...
    'analysis/OlhoffCurrent/diagnostics/three_rung_canary_preflight (C480 03097a28..., C800 7724af5e...; untracked at 013cc48)', ...
    'upstream repro/audits/upstream_olhoffcurrent_capabilities STAGE_EXHAUSTION_TEST (EX3_160)'};
e.mustNotBeLabelled    = 'Olhoff 2007';
e.epistemicClass       = ['reconstruction (class C) with a diagnostic controller; validated locally, ' ...
                          'never promoted, cross-mesh generalization not established'];
e.distinctFrom         = ['duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered in the outer controller ' ...
                          'and stop only (three policy fields); same material law'];
R = [R, e];

% ---- B. Pedersen / adaptive-box formulation ------------------------------
e = struct();
e.name                 = 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered';
e.upstreamPreset       = 'duOlhoffAdaptivePedersen';
e.upstreamCommit       = upstream;
e.overrides            = {};
e.runtimeDefaults      = struct('maxOuter', 400);
e.classification       = 'SCIENTIFIC_PRESET';
e.role                 = 'DISTINCT_FORMULATION';
e.productionEligible   = true;
e.formulationFamily    = 'PEDERSEN_LINEAR_MASS';
e.displayName          = 'Du-Olhoff reconstruction (Pedersen stiffness + linear mass, adaptive box)';
e.label                = ['Du-Olhoff reconstruction, Pedersen (2000) low-density stiffness with ' ...
                          'linear mass, adaptive per-element move box, sensitivity filtered'];
e.formulation = struct( ...
    'stiffness',   ['SIMP rho^3 above rho0 = 0.1; Pedersen (2000) eq. (5) linear rho*rho0^(p-1) ' ...
                    'below it (material.stiffness.model = pedersen, linearBelow = 0.1)'], ...
    'mass',        'eq. (2) linear, q = 1, no cut-off (material.mass.model = eq2)', ...
    'controller',  ['per-element adaptive move box: initial and ceiling 0.10, floor 0.002; x1.2 when ' ...
                    'the last two outer steps of an element agree in sign, x0.7 when they reverse'], ...
    'stopRule',    ['||drho||_2 < eps = 0.05*sqrt(NE/3200), no guards and no persistence ' ...
                    '(stop.rule = designChange, settledMove off): a heuristic design-change stop, ' ...
                    'not a KKT test'], ...
    'stageExhaustion', 'off', ...
    'filter', common.filter, 'multiplicity', common.multiplicity, ...
    'optimizer', common.optimizer, 'penalty', common.penalty);
e.compatibilityAliases = {};
e.historicalAliases    = {'duOlhoffAdaptivePedersen', 'S160x20', 'S240x30', 'S320x40', 'S400x50', ...
                          'S480x60', 'S560x70', 'S640x80', 'S720x90', 'S800x100'};
e.evidence = { ...
    'upstream Olhoff@6b0870850d7407a0f2fc31dbf0d0f318c2e5f2f7 repro/results/S*x* and SWEEP_R06 (nine meshes, R = 0.06)', ...
    'analysis/OlhoffCurrent/diagnostics/scientific_delta_olhoff_migration (formulation split; untracked at 013cc48)', ...
    'analysis/OlhoffCurrent/diagnostics/upstream_253069_migration (S160x20 bitwise under this tree)'};
e.mustNotBeLabelled    = 'Olhoff 2007';
e.epistemicClass       = ['reconstruction: class C controller and radius, class B/D material law ' ...
                          '(Pedersen is the alternative Du & Olhoff sec. 2.2 name, not their choice)'];
e.distinctFrom         = ['duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered in the low-density ' ...
                          'material law and the outer controller/stop; NOT a bug fix of it'];
R = [R, e];
end
