function s = olhoffcurrent_caveat(presetName)
%OLHOFFCURRENT_CAVEAT  The epistemic caveat that must travel with every number.
%
%   s = OLHOFFCURRENT_CAVEAT(presetName) returns the caveat of that named preset.
%   The name is required: the presets are different formulations and do not
%   share one caveat.
%
%   Every OlhoffCurrent preset is a RECONSTRUCTION of the Du & Olhoff (2007)
%   method, not a claimed reproduction of the authors' own code, and must be
%   labelled "Du-Olhoff reconstruction", never "Olhoff 2007".
%
%   See also OLHOFFCURRENT_PRESETS.

if nargin < 1 || isempty(presetName)
    error('olhoffcurrent_caveat:NameRequired', ...
        'olhoffcurrent_caveat requires a preset name; the presets do not share one caveat.');
end
info = olhoffcurrent_preset(presetName);

common = ['Must NOT be labelled "Olhoff 2007". Field-level provenance (A/B/C/D) is ' ...
    'documented in analysis/OlhoffCurrent/+impl/architecture/docs/SCIENTIFIC_CONFIG_PROVENANCE.md ' ...
    'and is printed per run by olh.config.describe.'];

switch info.name
    case 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered'
        s = ['Du-Olhoff RECONSTRUCTION, Pedersen/adaptive-box formulation (class C controller ' ...
             'and filter radius, class B/D material law): SIMP p = 3 with the Pedersen (2000) ' ...
             'linearized low-density stiffness (rho*rho0^(p-1) below rho0 = 0.1) and LINEAR ' ...
             'mass, eq. (2); a per-element ADAPTIVE move box (initial 0.10, floor 0.002, x1.2 ' ...
             'on monotone / x0.7 on reversing outer steps); NATURAL termination by ' ...
             '||drho||_2 < 0.05*sqrt(NE/3200) with no guards and no persistence, a heuristic ' ...
             'design-change stop and not a KKT certificate; Sigmund sensitivity filter on all ' ...
             'f_sk at a FIXED PHYSICAL radius R = 0.06 (1.2 elements at 160x20, 6 at 800x100). ' ...
             'This is a DISTINCT formulation from the historical SIMP + eq. (4b) OlhoffCurrent ' ...
             'reconstruction (duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered), not a bug ' ...
             'fix of it; Pedersen stiffness is the alternative Du & Olhoff sec. 2.2 name, not ' ...
             'their choice. Terminal bimodality is NOT expected beyond coarse meshes: in the ' ...
             'committed R = 0.06 sweep the optimum is bimodal only at 160x20 (native gap12 ' ...
             '0.7 %) and native gap12 is 11.8-24.5 % from 240x30 to 800x100. Native eigenfrequencies are those ' ...
             'of the Pedersen/linear-mass model; any cross-method table must name its ' ...
             'evaluator model. ' common];
    case 'duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered'
        s = ['Du-Olhoff RECONSTRUCTION (class C), historical SIMP + eq. (4b) formulation: ' ...
             'SIMP p = 3 at every density with the eq. (4b) C1 low-density mass cut-off; a ' ...
             'global move ladder [0.04 0.02 0.01 0.005] advanced by the bound-variable stall; ' ...
             'design-change stop asserted only on a settled move limit. Internally coherent ' ...
             'and fully documented, but not a claimed historical implementation. Numerical ' ...
             'continuation, filter radius, multiplicity tolerance and inner-loop convergence ' ...
             'are not specified in Du & Olhoff (2007) and are reconstruction choices here; the ' ...
             'outer iteration count is set by the move-ladder schedule. ' common];
    case 'duOlhoffSimpEq4bThreeRungStageExhaustionSensitivityFiltered'
        s = ['Du-Olhoff RECONSTRUCTION (class C), HISTORICAL DIAGNOSTIC controller: SIMP p = 3 ' ...
             'with the eq. (4b) C1 low-density mass cut-off under a three-rung move ladder ' ...
             '[0.04 0.02 0.01] advanced, and terminated, by the two-branch stage-exhaustion ' ...
             'rule E = A OR B. Validated locally (C160/C320), never promoted to production, ' ...
             'cross-mesh generalization not established; not production-eligible. ' common];
    otherwise
        error('olhoffcurrent_caveat:NoCaveat', 'No caveat is defined for preset %s.', info.name);
end
end
