function gate = a4_validate_frozen_identity(arm, topologyCsvPath, baseline)
%A4_VALIDATE_FROZEN_IDENTITY  Specification-faithful V-P2-2 validator.
%
% Exact scalar identity and topology-file identity are separate invariants.
% Comparing the full-precision in-memory topology with a reload of a CSV
% written at 15 significant digits is only a numerical diagnostic and never
% contributes to the stop decision.
%
% BASELINE is returned by A4_FROZEN_BASELINE_REFERENCE or
% A4_VALIDATE_FROZEN_BASELINE. The produced CSV is compared with both the
% validated immutable fixture hash and the declared expected hash.

if nargin < 3 || ~isstruct(baseline) || ...
        ~isfield(baseline, 'validated') || ~baseline.validated
    error('a4:FrozenBaselineMetadataMissing', ...
        'V-P2-2 requires validated immutable-baseline metadata.');
end

topologyCsvPath = char(java.io.File(topologyCsvPath).getCanonicalPath());
if strcmp(topologyCsvPath, baseline.path)
    error('a4:FrozenBaselinePathAlias', ...
        'Produced topology may not alias the immutable baseline: %s', ...
        topologyCsvPath);
end
if ~strcmp(topologyCsvPath, baseline.produced_topology_path)
    error('a4:FrozenProducedPathMismatch', ...
        ['V-P2-2 received an undeclared produced topology path. ' ...
         'Expected %s, got %s.'], ...
        baseline.produced_topology_path, topologyCsvPath);
end

expected = struct( ...
    'omega1_tracked', 159.56562699328325, ...
    'final_design_change', 3.034903639330122e-03, ...
    'iterations', 2000, ...
    'mode_index_jstar', 1, ...
    'mac_to_phi0', 0.9996284251363903, ...
    'omega1_omega2_gap', 67.37267502573462);
expectedTopologySha256 = baseline.expected_sha256;

gate = struct( ...
    'pass', true, ...
    'failures', {{}}, ...
    'expected_scalars', expected, ...
    'scalar_identity', struct(), ...
    'exact_scalar_identity', true, ...
    'topology_csv_path', topologyCsvPath, ...
    'reference_topology_path', baseline.path, ...
    'expected_topology_sha256', expectedTopologySha256, ...
    'reference_topology_sha256', baseline.actual_sha256, ...
    'actual_topology_sha256', '', ...
    'topology_file_identity', false, ...
    'numerical_diagnostics', localBlankDiagnostics());

names = fieldnames(expected);
for i = 1:numel(names)
    name = names{i};
    present = isfield(arm, name);
    actual = NaN;
    if present, actual = arm.(name); end
    identical = present && isequal(actual, expected.(name));
    gate.scalar_identity.(name) = identical;
    if ~identical
        gate.exact_scalar_identity = false;
        gate.pass = false;
        gate.failures{end+1} = sprintf('%s expected %.17g got %.17g', ...
            name, expected.(name), actual); %#ok<AGROW>
    end
end

if isfile(topologyCsvPath)
    gate.actual_topology_sha256 = a4_sha256_file(topologyCsvPath);
    gate.topology_file_identity = ...
        strcmp(gate.actual_topology_sha256, expectedTopologySha256) && ...
        strcmp(gate.actual_topology_sha256, baseline.actual_sha256);
    gate.numerical_diagnostics = localCsvReloadDiagnostics(arm, topologyCsvPath);
else
    gate.actual_topology_sha256 = '<missing>';
end

if ~gate.topology_file_identity
    gate.pass = false;
    gate.failures{end+1} = sprintf( ...
        'topology CSV SHA-256 expected %s got %s', ...
        expectedTopologySha256, gate.actual_topology_sha256); %#ok<AGROW>
end
end

function diagnostics = localBlankDiagnostics()
diagnostics = struct( ...
    'decision_role', 'non-blocking', ...
    'comparison', 'full-precision in-memory topology versus CSV reload', ...
    'csv_reload_exactly_equals_in_memory', false, ...
    'same_number_of_values', false, ...
    'n_values', 0, ...
    'n_different_values', 0, ...
    'max_abs_difference', NaN);
end

function diagnostics = localCsvReloadDiagnostics(arm, path)
diagnostics = localBlankDiagnostics();
if ~isfield(arm, 'topology') || isempty(arm.topology), return; end

reloaded = readmatrix(path);
inMemory = arm.topology(:);
reloaded = reloaded(:);
diagnostics.n_values = numel(inMemory);
diagnostics.same_number_of_values = numel(inMemory) == numel(reloaded);
if ~diagnostics.same_number_of_values, return; end

diagnostics.csv_reload_exactly_equals_in_memory = isequal(inMemory, reloaded);
different = inMemory ~= reloaded;
diagnostics.n_different_values = sum(different);
if isempty(inMemory)
    diagnostics.max_abs_difference = 0;
else
    diagnostics.max_abs_difference = max(abs(inMemory - reloaded));
end
end
