function fi_barrier()
[S,P,L,R,E]=fi_setup();A=load(fullfile(S.study,'evaluations','mma_replay.mat'),'CK');
c=A.CK([A.CK.iter]==19);pre=A.CK([A.CK.iter]==18).x;
alfa=max(max(c.low+.1*(pre-c.low),pre-.5*(P.xmax-P.xmin)),P.xmin);
beta=min(min(c.upp-.1*(c.upp-pre),pre+.5*(P.xmax-P.xmin)),P.xmax);
cl=c.xsi.*(c.x-alfa);cu=c.eta.*(beta-c.x);
truecl=c.xsi.*(c.x-P.xmin);truecu=c.eta.*(P.xmax-c.x);
s=sqrt(mean((P.F11/P.lamref).^2));
o=struct('scope','Observational barrier arithmetic at authenticated production call 19; no new variant', ...
 'epsimin',1e-7,'sRow0',s,'normalized_barrier_scale',1e-7/(s*P.move), ...
 'lower_artificial_comp_quantiles',quantile(cl,[0 .1 .5 .9 1]), ...
 'upper_artificial_comp_quantiles',quantile(cu,[0 .1 .5 .9 1]), ...
 'sum_artificial_box_comp',sum(cl+cu), ...
 'sum_physical_box_comp',sum(truecl+truecu), ...
 'certified_beta_gain',R.xRef(end)-1, ...
 'sum_comp_over_gain',sum(cl+cu)/(R.xRef(end)-1), ...
 'raw_comp_required',s*P.move*1e-6, ...
 'density_bound_tol',1e-6*(P.xmax(1:P.NE)-P.xmin(1:P.NE)));
fi_json(fullfile(E,'barrier_diagnostic.json'),o);disp(rmfield(o,'density_bound_tol'));
end
