function fi_initial_model()
% Observational check of already-retained call 1, no new optimizer call.
[S,P,L,R,E]=fi_setup();A=load(fullfile(S.study,'evaluations','mma_replay.mat'),'CK');
c=A.CK([A.CK.iter]==1);x0=[zeros(P.NE,1);1];
low=x0-.5*(P.xmax-P.xmin);upp=x0+.5*(P.xmax-P.xmin);
[fv,J]=P.evalProd(x0);
[f0app,fapp]=fi_mma_app(x0,c.x,P.xmin,P.xmax,low,upp,-1,P.f,fv,J);
fnew=P.evalProd(c.x);modelObjective=f0app+c.zmma+1000*sum(c.ymma);
o=struct('scope','Retained first MMA call, coefficients reconstructed without solving', ...
 'initial_objective',-1,'initial_constraints',fv.','initial_feasible',max(fv)<=1e-12, ...
 'candidate_true_objective',-c.x(end),'candidate_approx_objective',f0app, ...
 'candidate_total_approx_objective',modelObjective, ...
 'approx_objective_worsening',modelObjective+1, ...
 'true_objective_worsening',1-c.x(end), ...
 'max_model_constraint_with_y',max(fapp-c.ymma), ...
 'max_true_minus_approx',max([-c.x(end)-f0app;fnew-fapp]), ...
 'auxiliary_y',c.ymma.','auxiliary_z',c.zmma);
assert(o.initial_feasible && o.max_true_minus_approx<0 && o.approx_objective_worsening>0);
fi_json(fullfile(E,'initial_model_diagnostic.json'),o);disp(o);
end
