function [M,K,A] = fi_metric(P,R,x,mu,xsi,eta)
N=P.NE; z=x(1:N); zo=R.xRef(1:N); width=P.xmax-P.xmin;
[c,J]=P.evalProd(x); q=P.f+J.'*mu;
xi=[max(q(1:N),0);0]; et=[max(-q(1:N),0);0];
K=fp_kkt(P,x,mu,xi,et,'exact problem, implied physical-box multipliers');
s=K.stationarity.sRow0;
raw=P.f+J.'*mu-xsi+eta;
proj=z-min(max(z-P.move*q(1:N)/s,P.xmin(1:N)),P.xmax(1:N));
bo=local_bound(P,R.xRef); bx=local_bound(P,x);
large=abs(zo)>=.9*P.move; ob=bo~=0;
[co,~]=P.evalProd(R.xRef);
M=struct('bs',x(end),'beta',x(end)*P.lamref,'beta_gap',(R.xRef(end)-x(end))*P.lamref, ...
 'scaled_gap',R.xRef(end)-x(end),'gainRecovery',(x(end)-1)/(R.xRef(end)-1), ...
 'l2',norm(z-zo),'linf',norm(z-zo,inf),'d2',norm(z-zo)/norm(zo), ...
 'dinf',norm(z-zo,inf)/P.move,'cosine',dot(z,zo)/max(norm(z)*norm(zo),eps), ...
 'signAgreement',mean(sign(z(large))==sign(zo(large))), ...
 'allSignAgreement',mean(sign(z)==sign(zo)), ...
 'boundAgreement',mean(bx(ob)==bo(ob)),'activeAgreement',mean(bx==bo), ...
 'rowActiveAgreement',mean((abs(c)<=1e-8)==(abs(co)<=1e-8)), ...
 'maxMoveRatio',max(abs(z))/P.move,'constraintResidual',max([c;0]), ...
 'boxViolation',max([P.xmin-x;x-P.xmax;0]), ...
 'kkt',max([K.stationarity.norm_rms,abs(q(end)),K.complementarity.max_box_comp_normalized,K.complementarity.max_abs_mu_f]), ...
 'kktRms',K.stationarity.norm_rms,'kktMax',K.stationarity.norm_max, ...
 'betaStationarity',abs(q(end)), 'boxComplementarity',K.complementarity.max_box_comp_normalized, ...
 'rowComplementarity',K.complementarity.max_abs_mu_f, ...
 'rawSolverStationarityRms',sqrt(mean(raw(1:N).^2))/s, ...
 'projectedKktRms',sqrt(mean(proj.^2))/P.move, ...
 'c1',c(1),'c2',c(2),'c3',c(3),'c4',c(4));
so=P.Ac*R.xRef-P.bc; po=R.muRef(1)*so/norm(so);
qo=P.f+P.Ac.'*po-R.muRef(1)*P.dc+P.Alin.'*R.muRef(3:4);
dualBound=sum(min(qo.*P.xmin,qo.*P.xmax))-po.'*P.bc+R.muRef(1)*P.gammac-R.muRef(3:4).'*P.blin;
M.oracleWitnessGap=P.f.'*x-dualBound;
groups={P.rho>.1 & P.rho<.9,P.rho>=.4 & P.rho<=.6}; names={'gray','mid'};
for j=1:2
 id=groups{j}; la=id&large; ib=id&ob; n=names{j};
 M.([n 'D2'])=norm(z(id)-zo(id))/max(norm(zo(id)),eps);
 M.([n 'Dinf'])=max(abs(z(id)-zo(id)))/P.move;
 M.([n 'SignAgreement'])=mean(sign(z(la))==sign(zo(la)));
 M.([n 'BoundAgreement'])=mean(bx(ib)==bo(ib));
end
M.fidelity=abs(M.scaled_gap)<=1e-8 && M.gainRecovery>=.999 && M.d2<=.01 && M.dinf<=.1 && ...
 M.signAgreement>=.99 && M.boundAgreement>=.99 && M.constraintResidual<=1e-8 && M.boxViolation<=1e-10 && ...
 min([mu;xi;et])>=-1e-10 && M.kktRms<=1e-6 && M.kktMax<=1e-5 && M.betaStationarity<=1e-6 && ...
 M.rowComplementarity<=1e-6 && M.boxComplementarity<=1e-6;
A=[bx; int8(abs(c)<=1e-8)];
end
function b=local_bound(P,x)
N=P.NE; w=P.xmax(1:N)-P.xmin(1:N);
b=zeros(N,1,'int8'); b(x(1:N)<=P.xmin(1:N)+1e-6*w)=-1;
b(x(1:N)>=P.xmax(1:N)-1e-6*w)=1;
end
