function cfg = duOlhoffFrozenM4(cfg)
%DUOLHOFFFROZENM4  The frozen conference reconstruction.
%
%   Historical labels: TMA, B0, REG160, "frozen M4".
%   Classification: SCIENTIFIC_PRESET.
%   Provenance: RECONSTRUCTION preset.  Not a published Du-Olhoff realization.
%
%   Formulation
%     stiffness    eq. (1) SIMP, p = 3 held FIXED
%                  (sec. 2.1 says p is "normally assigned values increasing
%                   from 1 to 3"; fixing it is a reconstruction ruling made
%                   because the reported initial eigenfrequencies only fit p=3)
%     mass         eq. (4b), the C1 model
%     filter       Sigmund (1997) SENSITIVITY filter, physical radius R = 0.06,
%                  applied to EVERY f_sk (not only the diagonal)
%     projection   disabled
%     multiplicity fixed subspace of size 2, no classifier, with the diagonal
%                  offsets diag(lambda_j - lambda_n) retained in (25d)
%     optimizer    published MMA (Svanberg Sept-2007 constants) on the increment
%     move         staged ladder [0.04 0.02 0.01 0.005], descending when the
%                  bound variable beta stalls over a window of 10
%     stopping     ||d(design)||_2 < eps, asserted only when the move limit is
%                  unchanged from the previous iteration
%     tolerance    eps = 0.05 at 160x20, scaled as 0.05*sqrt(NE/3200)
%
%   This preset carries a KNOWN DEFICIENCY deliberately: under a move ladder the
%   measured step reports the schedule rather than the design on any iteration
%   where the move limit changes.  settledMove suppresses the symptom; it does
%   not remove the cause.  See audit_termination_mesh_admission (verdict
%   S2_CONTINUATION_DEFECT).  Fix architecture, not history.
if nargin < 1, cfg = olh.config.defaults(); end
cfg = olh.config.assign(cfg, ...
    'material.stiffness.p',                    3, ...
    'material.stiffness.continuation.enabled', false, ...
    'material.mass.model',                     'eq4b', ...
    'material.mass.continuation.enabled',      false, ...
    'filter.type',                             'sensitivity', ...
    'filter.applyTo',                          'all', ...
    'filter.radiusPhysical',                   0.06, ...
    'filter.radiusElements',                   [], ...
    'projection.enabled',                      false, ...
    'multiplicity.method',                     'subspace', ...
    'multiplicity.subspaceSize',               2, ...
    'multiplicity.diagonalOffsets',            true, ...
    'multiplicity.offDiagonal',                true, ...
    'multiplicity.tolerance',                  0.05, ...
    'optimizer.inner.type',                    'mma', ...
    'optimizer.inner.variant',                 'published', ...
    'optimizer.inner.variable',                'increment', ...
    'optimizer.inner.tolerance',               0.05, ...
    'optimizer.inner.minIterations',           5, ...
    'optimizer.inner.maxIterations',           500, ...
    'move.policy',                             'ladder', ...
    'move.initial',                            0.04, ...
    'move.levels',                             [0.04 0.02 0.01 0.005], ...
    'move.continuation.signal',                'boundVariable', ...
    'move.continuation.window',                10, ...
    'move.continuation.tolerance',             5e-3, ...
    'stop.norm',                               'l2', ...
    'stop.guards.settledMove',                 true, ...
    'stop.guards.ladderExhausted',             false, ...
    'stop.guards.maxDesignChange',             false);

cfg = olh.config.assign(cfg, 'runtime.maxOuter', 400);
end
