function [cfg, meta] = tb_config(nelx, nely)
%TB_CONFIG  The single authorized run: 240x30, fixed move = 0.04.
%   Canonical production formulation with exactly two conceptual changes:
%     move.policy='fixed', move.initial=0.04    the mechanism-measurement arm
%     stop.tolerance=0, stop.toleranceRule='explicit'
%                                               minimal stop override so native
%                                               termination cannot truncate the
%                                               observation (PREREGISTRATION 14)
info = olhoffcurrent_preset();
cap  = 1200;                                    % preregistered cap
overrides = { 'move.policy', 'fixed', 'move.initial', 0.04, ...
              'stop.tolerance', 0, 'stop.toleranceRule', 'explicit' };
cfg = olh.config.resolve(info.upstreamPreset, ...
        'domain.mesh.nelx', nelx, 'domain.mesh.nely', nely, ...
        'runtime.maxOuter', cap, 'runtime.singleThread', true, ...
        'runtime.diagnostics', true, 'runtime.verbose', false, ...
        'runtime.name', sprintf('TB_FIXEDMOVE_%dx%d', nelx, nely), ...
        overrides{:});
cfg.provenance.productionPreset = info.name;
cfg.provenance.implementation   = 'analysis/OlhoffCurrent';
meta = struct('run','D','label','240x30 fixed move 0.04 (unstopped, withheld test)', ...
              'nelx',nelx,'nely',nely,'preset',info.name, ...
              'upstreamPreset',info.upstreamPreset,'maxOuter',cap,'overrides',{overrides});
end
