function postprocess_targeted_replays()
%POSTPROCESS_TARGETED_REPLAYS Build retained tables/figures from replay MATs.
here=fileparts(mfilename('fullpath'));repo=fileparts(fileparts(here));figDir=fullfile(here,'figures');
addpath(here);addpath(fullfile(repo,'tools'));addpath(fullfile(repo,'tools','Matlab'));
maxNumCompThreads(1);
O=load(fullfile(here,'raw','olhoff','s1_640x80_diagnostic.mat'));
Y=load(fullfile(here,'raw','yuksel','yuksel_800x100_diagnostic.mat'));
P1=load(fullfile(here,'raw','proposed','proposed_160x20_diagnostic_run1.mat'));
P2=load(fullfile(here,'raw','proposed','proposed_160x20_diagnostic_run2.mat'));

write_configuration_identity(O.gate,Y.result.gate,P1.result.gate,here);
olhoffSummary=process_olhoff(O,here,figDir);
yukselSummary=process_yuksel(Y.result,here,figDir);
proposedSummary=process_proposed(P1.result,P2.result,here,figDir);
summary=struct('generated_at',char(datetime('now','TimeZone','Europe/Warsaw', ...
    'Format','yyyy-MM-dd''T''HH:mm:ssXXX')),'timing_role','ALL REPLAY TIMING IS DIAGNOSTIC ONLY', ...
    'olhoff',olhoffSummary,'yuksel',yukselSummary,'proposed',proposedSummary);
write_json(fullfile(here,'matlab_analysis_summary.json'),summary);
fprintf('TARGETED_REPLAY_POSTPROCESS_COMPLETE\n');
end

function write_configuration_identity(o,y,p,here)
method=string({'Olhoff';'Yuksel';'Proposed'});mesh=string({o.mesh;y.mesh;p.mesh});
original_profile_id=string({o.original_profile_id;y.original_profile_id;p.original_profile_id});
replay_profile_id=string({o.replay_profile_id;y.replay_profile_id;p.replay_profile_id});
numerical_config_identical=[o.pass;y.pass;p.pass];
source_hashes_equal=[true;true;true];
diagnostic_only_differences=string({ ...
    'external failed-attempt LP output/residual retention; numerical cfg unchanged'; ...
    'record_history=true; scalar audit retention; density snapshot stride=10'; ...
    'record_history=true; native spectral history=true; identical run repeated once'});
pass_fail=repmat("PASS",3,1);pass_fail(~numerical_config_identical)="FAIL";
T=table(method,mesh,original_profile_id,replay_profile_id,numerical_config_identical,source_hashes_equal, ...
    diagnostic_only_differences,pass_fail);writetable(T,fullfile(here,'configuration_identity.csv'));
end

function s=process_olhoff(D,here,figDir)
r=D.res;f=r.failed_attempt;lp=f.lp;o=lp.output;
lpIterations=first_numeric_field(o,{'iterations','simplex_iterations','dual_simplex_iterations'});
solverMessage=first_text_field(o,{'message'});
originalAttempt=D.comparison.original_failure_attempt;replayAttempt=D.comparison.replay_failure_attempt;
causal='GENERIC_LP_ITERATION_LIMIT_ONLY';
if ~strcmp(D.comparison.reproduction_verdict,'FAILURE_REPRODUCED'),causal='CAUSE_REMAINS_UNRESOLVED';end
T=table(originalAttempt,replayAttempt,lp.exitflag,lpIterations,f.omega(1),f.omega(2),f.omega(3), ...
    f.N,f.gap12,f.lamref,f.current_move,f.policy_stage,f.trigger_counter,f.trigger_this_iteration, ...
    lp.matrix_dimensions(1),lp.matrix_dimensions(2),lp.matrix_dimensions(3),lp.nnz_A,lp.nnz_Aeq, ...
    lp.row_norm_ratio_A,lp.row_norm_ratio_Aeq,lp.normalized_gram_rcond,lp.constraint_row_rank, ...
    lp.max_inequality_violation,lp.max_equality_residual,lp.max_lower_bound_violation, ...
    lp.max_upper_bound_violation,lp.active_bound_fraction,lp.returned_point_finite,lp.finite_matrices, ...
    string(solverMessage),string(D.comparison.reproduction_verdict),string(causal), ...
    'VariableNames',{'original_failure_attempt','replay_failure_attempt','linprog_exitflag','lp_iterations', ...
    'omega1','omega2','omega3','N','gap12','lamref','move','policy_stage','trigger_counter', ...
    'trigger_this_attempt','n_inequalities','n_variables','n_equalities','nnz_A','nnz_Aeq', ...
    'row_norm_ratio_A','row_norm_ratio_Aeq','normalized_gram_rcond','constraint_row_rank', ...
    'max_inequality_violation','max_equality_residual','max_lower_bound_violation', ...
    'max_upper_bound_violation','active_bound_fraction','returned_point_finite','finite_matrices', ...
    'solver_message','reproduction_verdict','causal_classification'});
writetable(T,fullfile(here,'olhoff_640_failure_diagnostics.csv'));

h=r.hist;n=r.nOuter;k0=max(1,n-99);iter=(k0:n)';
H=table(iter,h.omega(1,k0:n)',h.omega(2,k0:n)',h.omega(3,k0:n)',h.N(k0:n)', ...
    h.gap12(k0:n)',h.moveLimit(k0:n)',h.policyStage(k0:n)',logical(h.trigger(k0:n)'), ...
    h.dxOuter(k0:n)',h.dRms(k0:n)',h.vol(k0:n)',repmat(false,numel(iter),1), ...
    'VariableNames',{'iteration','omega1','omega2','omega3','N','gap12','move', ...
    'policy_stage','trigger','max_dx','rms_dx','volume','failed_attempt'});
F=table(f.attempted_outer_iteration,f.omega(1),f.omega(2),f.omega(3),f.N,f.gap12, ...
    f.current_move,f.policy_stage,f.trigger_this_iteration,NaN,NaN,f.volume,true, ...
    'VariableNames',H.Properties.VariableNames);H=[H;F];
writetable(H,fullfile(here,'olhoff_640_history_window.csv'));

fig=figure('Visible','off','Color','w','Position',[50 50 1250 900]);tl=tiledlayout(3,1,'Padding','compact');
nexttile;plot(iter,H.omega1(1:end-1),'LineWidth',1.2);hold on;plot(iter,H.omega2(1:end-1),'LineWidth',1.2); ...
    plot(iter,H.omega3(1:end-1),'LineWidth',1.0);scatter(f.attempted_outer_iteration,f.omega(1),45,'rx','LineWidth',2); ...
    ylabel('\omega [rad/s]');legend('\omega_1','\omega_2','\omega_3','failed attempt','Location','best');grid on;
nexttile;semilogy(iter,max(H.gap12(1:end-1),1e-8),'LineWidth',1.2);hold on;yline(.01,'k--'); ...
    scatter(f.attempted_outer_iteration,f.gap12,45,'rx','LineWidth',2);ylabel('gap_{12}');grid on;
nexttile;yyaxis left;plot(iter,H.max_dx(1:end-1),'LineWidth',1.2);hold on; ...
    plot(iter,H.move(1:end-1),'--','LineWidth',1.0);ylabel('update / move');ylim([0 0.003]); ...
    yyaxis right;stairs(iter,H.N(1:end-1),'LineWidth',1.2);ylabel('N');ylim([0.5 3.5]); ...
    xline(f.attempted_outer_iteration,'r--');xlabel('outer iteration');grid on; ...
    legend('max |d\rho|','move','N','failed attempt','Location','best'); ...
    title(tl,'Olhoff 640x80: final pre-failure window and attempted k=1067');
exportgraphics(fig,fullfile(figDir,'01_olhoff_640_prefailure_history.png'),'Resolution',180);close(fig);

fig=figure('Visible','off','Color','w','Position',[50 50 1200 620]);tl=tiledlayout(1,2,'Padding','compact');
nexttile;vals=[lp.row_norm_A(:);lp.row_norm_Aeq(:)];bar(vals);set(gca,'YScale','log'); ...
    xlabel('constraint row');ylabel('row 2-norm');grid on;title('LP constraint scaling proxy');
nexttile;v=[lp.max_inequality_violation lp.max_equality_residual lp.max_lower_bound_violation lp.max_upper_bound_violation]; ...
    if all(isnan(v)),axis off;text(0.5,0.58,'Residual and bound-activity diagnostics unavailable', ...
        'HorizontalAlignment','center','FontWeight','bold','FontSize',13); ...
        text(0.5,0.43,'No primal point was returned by linprog.', ...
        'HorizontalAlignment','center','FontSize',12); ...
        text(0.5,0.28,sprintf('exitflag=%d, reported iterations=%g',lp.exitflag,lpIterations), ...
        'HorizontalAlignment','center','FontSize',11); ...
    else,bar(v);set(gca,'YScale','log','XTickLabel',{'ineq','equality','lower','upper'}); ...
        ylabel('max residual / violation');grid on;title(sprintf('exitflag=%d, iterations=%g',lp.exitflag,lpIterations));end
title(tl,'Olhoff failed-attempt LP diagnostics (post-solve, no LP alteration)');
exportgraphics(fig,fullfile(figDir,'02_olhoff_640_lp_diagnostics.png'),'Resolution',180);close(fig);

s=struct('reproduction_verdict',D.comparison.reproduction_verdict,'original_failure_attempt',originalAttempt, ...
    'replay_failure_attempt',replayAttempt,'exitflag',lp.exitflag,'lp_iterations',lpIterations, ...
    'solver_message',solverMessage,'omega',f.omega(1:3).','N',f.N,'gap12',f.gap12, ...
    'lamref',f.lamref,'move',f.current_move,'trigger_iteration',r.trigger_iterations(1), ...
    'causal_classification',causal,'history_bit_identical',D.comparison.all_history_bit_identical, ...
    'density_bit_identical',D.comparison.final_density_bit_identical, ...
    'snapshots_bit_identical',D.comparison.snapshots_bit_identical, ...
    'normalized_gram_rcond',lp.normalized_gram_rcond,'row_norm_ratio_A',lp.row_norm_ratio_A, ...
    'active_bound_fraction',lp.active_bound_fraction,'returned_point_finite',lp.returned_point_finite, ...
    'diagnostic_wall_time_s',r.wallclock);
end

function s=process_yuksel(r,here,figDir)
H=r.info.history;n=H.n;relativeObjectiveChange=NaN(n,1);
for k=2:n
    if H.stage(k)==H.stage(k-1),relativeObjectiveChange(k)=abs(H.objective(k)-H.objective(k-1))/max(abs(H.objective(k-1)),eps);end
end
stepP95=NaN(n,1);stepActiveFrac=stepP95;moveFrac=stepP95;modeCos=stepP95;modeAngleDeg=stepP95;du=stepP95;
snapshotChecksum=strings(n,1);snapshotTurnover=NaN(n,1);
[stepP95,stepActiveFrac,moveFrac,modeCos,modeAngleDeg,du,snapshotChecksum,snapshotTurnover]= ...
    add_yuksel_audit(r.info.stage1.audit,0,stepP95,stepActiveFrac,moveFrac,modeCos,modeAngleDeg,du, ...
    snapshotChecksum,snapshotTurnover);
[stepP95,stepActiveFrac,moveFrac,modeCos,modeAngleDeg,du,snapshotChecksum,snapshotTurnover]= ...
    add_yuksel_audit(r.info.stage2.audit,r.info.stage1.iterations,stepP95,stepActiveFrac,moveFrac,modeCos,modeAngleDeg,du, ...
    snapshotChecksum,snapshotTurnover);
dominantFractionUpperBound=NaN(n,1);dominantCountUpperBound=NaN(n,1);
localized=stepP95<0.5*H.d_inf_design;
dominantFractionUpperBound(localized)=0.05;dominantCountUpperBound(localized)=ceil(0.05*numel(r.xFinal));
T=table(H.iter,H.stage,H.stage_iter,H.d_inf_design,H.d_rms_design,H.d_inf,H.d_rms,H.objective, ...
    relativeObjectiveChange,H.rV,H.grayness,H.move_active_frac,stepP95,stepActiveFrac,moveFrac, ...
    modeCos,modeAngleDeg,du,dominantFractionUpperBound,dominantCountUpperBound, ...
    snapshotChecksum,snapshotTurnover, ...
    'VariableNames',{'total_iteration','stage','stage_iteration','max_dx','rms_dx', ...
    'max_dx_physical','rms_dx_physical','objective','relative_objective_change','relative_volume_residual', ...
    'grayness','move_active_fraction','step_p95','step_active_fraction','move_fraction', ...
    'mode_cosine','mode_angle_deg','mode_update_norm','dominant_fraction_upper_bound', ...
    'dominant_count_upper_bound','density_checksum_at_snapshot','binary_turnover_since_prior_snapshot'});
writetable(T,fullfile(here,'yuksel_800_history.csv'));

starts=[701 801 901 701];ends=[800 900 1000 1000];labels=string({'S2 701-800';'S2 801-900';'S2 901-1000';'S2 final 300'});
W=table('Size',[4 19],'VariableTypes',{'string','double','double','double','double','double','double','double', ...
    'double','double','double','double','double','double','double','string','string','string','string'}, ...
    'VariableNames',{'window','stage','global_start','global_end','max_dx_start','max_dx_end','max_dx_median', ...
    'rms_dx_median','max_to_rms_median','objective_relative_span','median_relative_objective_change', ...
    'median_step_p95_to_max','fraction_iterations_localized','max_snapshot_turnover', ...
    'dominant_variable_fraction_upper_bound','objective_frequency_trend','motion_pattern', ...
    'cap_classification','diagnosis'});
for i=1:4
    idx=r.info.stage1.iterations+(starts(i):ends(i));x=T.max_dx(idx);rr=T.rms_dx(idx);ob=T.objective(idx);
    W.window(i)=labels(i);W.stage(i)=2;W.global_start(i)=idx(1);W.global_end(i)=idx(end);W.max_dx_start(i)=x(1);W.max_dx_end(i)=x(end);
    W.max_dx_median(i)=median(x,'omitnan');W.rms_dx_median(i)=median(rr,'omitnan');
    W.max_to_rms_median(i)=median(x./max(rr,eps),'omitnan');
    W.objective_relative_span(i)=(max(ob)-min(ob))/max(abs(mean(ob)),eps);
    W.median_relative_objective_change(i)=median(T.relative_objective_change(idx),'omitnan');
    W.median_step_p95_to_max(i)=median(T.step_p95(idx)./max(x,eps),'omitnan');
    W.fraction_iterations_localized(i)=mean(localized(idx));
    W.max_snapshot_turnover(i)=max(T.binary_turnover_since_prior_snapshot(idx),[],'omitnan');
    W.dominant_variable_fraction_upper_bound(i)=0.05;
    W.objective_frequency_trend(i)="OBJECTIVE_STABLE; final native frequency only";
    W.motion_pattern(i)="IRREGULAR_OSCILLATION + LOCALIZED_VARIABLE_MOTION";
    W.cap_classification(i)="PERSISTENT_NONCONVERGENCE";
    W.diagnosis(i)="not a simple cap limitation; modest extension not justified";
end
writetable(W,fullfile(here,'yuksel_800_cap_diagnosis.csv'));

late=r.info.stage1.iterations+(701:1000);
fig=figure('Visible','off','Color','w','Position',[50 50 1200 650]);semilogy(T.total_iteration(late),T.max_dx(late),'LineWidth',1.2);hold on; ...
    semilogy(T.total_iteration(late),T.rms_dx(late),'LineWidth',1.2);yline(.01,'k--','native tolerance'); ...
    grid on;xlabel('total iteration');ylabel('density change');legend('max |dx|','RMS dx','Location','best'); ...
    title('Yuksel 800x100: final 300 Stage-2 iterations');
exportgraphics(fig,fullfile(figDir,'03_yuksel_800_late_density_change.png'),'Resolution',180);close(fig);
fig=figure('Visible','off','Color','w','Position',[50 50 1200 650]);yyaxis left;plot(T.total_iteration(late),T.objective(late),'LineWidth',1.2); ...
    ylabel('moving-load compliance');yyaxis right;semilogy(T.total_iteration(late),max(T.relative_objective_change(late),eps),'LineWidth',1.0); ...
    ylabel('relative objective change');xlabel('total iteration');grid on;title('Yuksel 800x100: late objective behavior');
exportgraphics(fig,fullfile(figDir,'04_yuksel_800_late_objective.png'),'Resolution',180);close(fig);

s=struct('status',r.status,'endpoint_matches_original',r.original_comparison.endpoint_matches_original, ...
    'total_iterations',r.info.timing.total_iterations,'stage1_iterations',r.info.stage1.iterations, ...
    'stage2_iterations',r.info.stage2.iterations,'final_max_dx',r.info.stopping.final_max_density_change, ...
    'final_rms_dx',r.info.stopping.final_rms_density_change,'final_relative_objective_change', ...
    r.info.stopping.final_relative_objective_change,'final_omega',r.omega(:).', ...
    'final_density_checksum',numeric_fingerprint(r.xFinal),'diagnostic_wall_time_s',r.diagnostic_wall_time_s, ...
    'late300_max_dx_min',min(T.max_dx(late)),'late300_max_dx_max',max(T.max_dx(late)), ...
    'late300_max_dx_median',median(T.max_dx(late)),'late300_rms_dx_median',median(T.rms_dx(late)), ...
    'late300_objective_relative_span',(max(T.objective(late))-min(T.objective(late)))/abs(mean(T.objective(late))), ...
    'late300_median_relative_objective_change',median(T.relative_objective_change(late),'omitnan'), ...
    'late300_fraction_localized_upper_bound',mean(localized(late)), ...
    'late300_median_p95_to_max',median(T.step_p95(late)./T.max_dx(late),'omitnan'));
end

function [p95,active,mv,mc,ma,du,checks,turn]=add_yuksel_audit(a,offset,p95,active,mv,mc,ma,du,checks,turn)
idx=offset+a.iter(:);p95(idx)=a.stepP95;active(idx)=a.stepActiveFrac;mv(idx)=a.moveFrac;
mc(idx)=a.modeCos;ma(idx)=a.modeAngleDeg;du(idx)=a.du;
prev=[];
for j=1:numel(a.snapshotIter)
    k=offset+a.snapshotIter(j);x=a.xPhysSnapshots(:,j);checks(k)=numeric_fingerprint(x);
    if ~isempty(prev),turn(k)=mean(binary_exact(x)~=binary_exact(prev));end;prev=x;
end
end

function s=process_proposed(a,b,here,figDir)
sameN=a.nIter==b.nIter;sameX=isequaln(a.xFinal,b.xFinal);sameW=isequaln(a.omega,b.omega);
sameObj=isequaln(a.info.objective_history,b.info.objective_history);sameHist=numerical_history_equal(a.info.history,b.info.history);
sameFreqHist=isequaln(a.info.freq_iter_omega,b.info.freq_iter_omega);
commonDiff=max_common_difference(a.common_evaluators,b.common_evaluators);
if sameN&&sameX&&sameW&&sameObj&&sameHist&&sameFreqHist&&commonDiff==0
    verdict='DETERMINISTIC';
elseif sameN&&max(abs(a.xFinal-b.xFinal))<1e-10&&max(abs(a.omega-b.omega))<1e-8&&commonDiff<1e-8
    verdict='NUMERICALLY_EQUIVALENT';
else,verdict='NONDETERMINISTIC';end

runs=[1;2];iters=[a.nIter;b.nIter];w1=[a.omega(1);b.omega(1)];w2=[a.omega(2);b.omega(2)];w3=[a.omega(3);b.omega(3)];
finalDx=[a.info.stopping.final_max_density_change;b.info.stopping.final_max_density_change];
densityChecksum=string({numeric_fingerprint(a.xFinal);numeric_fingerprint(b.xFinal)});
topologyChecksum=string({numeric_fingerprint(binary_exact(a.xFinal));numeric_fingerprint(binary_exact(b.xFinal))});
rawE1=[a.common_evaluators.omega_raw_E1(1);b.common_evaluators.omega_raw_E1(1)];
binaryE1=[a.common_evaluators.omega_binary_E1(1);b.common_evaluators.omega_binary_E1(1)];
determinismVerdict=repmat(string(verdict),2,1);D=table(runs,iters,w1,w2,w3,finalDx,densityChecksum,topologyChecksum,rawE1,binaryE1,determinismVerdict);
writetable(D,fullfile(here,'proposed_160_determinism.csv'));

T=history_table(a);T.run(:)=1;T2=history_table(b);T2.run(:)=2;T=[T;T2];
T=movevars(T,'run','Before',1);writetable(T,fullfile(here,'proposed_160_history.csv'));

ev=a.common_evaluators;quantity=string({'omega1';'omega2';'omega3'});native=a.omega(1:3);
E1_raw=ev.omega_raw_E1(:);E2_raw=ev.omega_raw_E2(:);E3_raw=ev.omega_raw_E3(:);
E1_binary=ev.omega_binary_E1(:);E2_binary=ev.omega_binary_E2(:);E3_binary=ev.omega_binary_E3(:);
interpretation=string({ ...
    'low native first mode is absent under every common evaluator'; ...
    'common model shifts/reorders the clustered native spectrum'; ...
    'higher spectrum is strongly interpolation-sensitive'});
C=table(quantity,native,E1_raw,E2_raw,E3_raw,E1_binary,E2_binary,E3_binary,interpretation);
writetable(C,fullfile(here,'proposed_160_common_evaluators.csv'));

modes=evaluate_proposed_native_modes(a.xFinal,a.gate.replay,3);
modeOmegaDiff=max(abs(modes.omega(:)-a.omega(:)));
save(fullfile(here,'raw','proposed','proposed_160_native_modes.mat'),'modes','modeOmegaDiff','-v7.3');
L=modes.localization;LM=table([L.mode]',[L.omega]',[L.displacement_fraction_low]',[L.displacement_fraction_gray]', ...
    [L.displacement_fraction_solid]',[L.kinetic_fraction_low]',[L.kinetic_fraction_gray]', ...
    [L.kinetic_fraction_solid]',[L.strain_fraction_low]',[L.strain_fraction_gray]', ...
    [L.strain_fraction_solid]',[L.density_weighted_by_displacement]', ...
    [L.peak_to_median_element_displacement]',[L.participation_elements_90pct]', ...
    'VariableNames',{'mode','omega','displacement_fraction_low','displacement_fraction_gray', ...
    'displacement_fraction_solid','kinetic_fraction_low','kinetic_fraction_gray','kinetic_fraction_solid', ...
    'strain_fraction_low','strain_fraction_gray','strain_fraction_solid','density_weighted_by_displacement', ...
    'peak_to_median_element_displacement','participation_elements_90pct'});
writetable(LM,fullfile(here,'proposed_160_mode_localization.csv'));

fig=figure('Visible','off','Color','w','Position',[50 50 1200 650]);plot(a.info.freq_iter_omega(:,1:3),'LineWidth',1.1); ...
    grid on;xlabel('iteration');ylabel('native \omega [rad/s]');legend('\omega_1','\omega_2','\omega_3','Location','best'); ...
    title('Proposed 160x20: retained native spectral history (diagnostic eigensolves)');
exportgraphics(fig,fullfile(figDir,'05_proposed_160_native_spectral_history.png'),'Resolution',180);close(fig);

xb=binary_exact(a.xFinal);fig=figure('Visible','off','Color','w','Position',[50 50 1300 520]);
subplot(2,1,1);imagesc(reshape(1-a.xFinal,20,160));axis image off;colormap(gray(256));title(sprintf('Raw density, grayness %.4f',mean(4*a.xFinal.*(1-a.xFinal))));
subplot(2,1,2);imagesc(reshape(1-xb,20,160));axis image off;title('Exact-count volume-preserving binary topology (connected)');
exportgraphics(fig,fullfile(figDir,'06_proposed_160_density_topology.png'),'Resolution',180);close(fig);

fig=figure('Visible','off','Color','w','Position',[50 50 1400 720]);tl=tiledlayout(3,1,'Padding','compact');
for k=1:3
    nexttile;u=modes.phi(1:2:end,k);v=modes.phi(2:2:end,k);mag=reshape(sqrt(u.^2+v.^2),21,161); ...
        imagesc(mag);axis image off;colorbar;title(sprintf('Native mode %d: \\omega=%.3f rad/s; low+gray displacement fraction=%.3f', ...
        k,modes.omega(k),L(k).displacement_fraction_low+L(k).displacement_fraction_gray));
end
title(tl,'Proposed 160x20 native mode-shape magnitude');
exportgraphics(fig,fullfile(figDir,'07_proposed_160_native_mode_shapes.png'),'Resolution',180);close(fig);

labels={'Native','E1 raw','E2 raw','E3 raw','E1 binary','E2 binary','E3 binary'};
spectra=[a.omega(:) ev.omega_raw_E1(:) ev.omega_raw_E2(:) ev.omega_raw_E3(:) ...
    ev.omega_binary_E1(:) ev.omega_binary_E2(:) ev.omega_binary_E3(:)]';
fig=figure('Visible','off','Color','w','Position',[50 50 1400 650]);bar(spectra);grid on; ...
    set(gca,'XTickLabel',labels);ylabel('\omega [rad/s]');legend('mode 1','mode 2','mode 3','Location','northwest'); ...
    title('Proposed 160x20: native versus unchanged common evaluators');
exportgraphics(fig,fullfile(figDir,'08_proposed_160_native_common_spectra.png'),'Resolution',180);close(fig);

s=struct('determinism_verdict',verdict,'iterations',a.nIter,'native_omega',a.omega(:).', ...
    'final_max_dx',a.info.stopping.final_max_density_change,'density_checksum',numeric_fingerprint(a.xFinal), ...
    'binary_topology_checksum',numeric_fingerprint(xb),'both_match_original', ...
    a.original_comparison.endpoint_matches_original&&b.original_comparison.endpoint_matches_original, ...
    'common_raw_E1',ev.omega_raw_E1(:).','common_binary_E1',ev.omega_binary_E1(:).', ...
    'common_raw_E2',ev.omega_raw_E2(:).','common_raw_E3',ev.omega_raw_E3(:).', ...
    'common_binary_E2',ev.omega_binary_E2(:).','common_binary_E3',ev.omega_binary_E3(:).', ...
    'grayness',ev.grayness,'raw_connected',ev.connectivity_raw_05.left_right_connected, ...
    'binary_connected',ev.connectivity_binary.left_right_connected, ...
    'native_mode_recompute_max_abs_difference',modeOmegaDiff,'mode_localization',L, ...
    'diagnostic_wall_time_run1_s',a.diagnostic_wall_time_s,'diagnostic_wall_time_run2_s',b.diagnostic_wall_time_s);
end

function T=history_table(r)
H=r.info.history;n=H.n;freq=r.info.freq_iter_omega;
T=table(H.iter,H.stage,H.stage_iter,H.d_inf_design,H.d_rms_design,H.d_inf,H.d_rms, ...
    H.objective,H.rV,H.grayness,H.move_active_frac,freq(:,1),freq(:,2),freq(:,3), ...
    'VariableNames',{'iteration','stage','stage_iteration','max_dx','rms_dx','max_dx_physical', ...
    'rms_dx_physical','objective','relative_volume_residual','grayness','move_active_fraction', ...
    'omega1','omega2','omega3'});
end

function d=max_common_difference(a,b)
names={'omega_raw_E1','omega_raw_E2','omega_raw_E3','omega_binary_E1','omega_binary_E2','omega_binary_E3'};d=0;
for i=1:numel(names),d=max(d,max(abs(a.(names{i})(:)-b.(names{i})(:))));end
end

function same=numerical_history_equal(a,b)
namesA=sort(fieldnames(a));namesB=sort(fieldnames(b));
same=isequal(namesA,namesB);if ~same,return;end
for i=1:numel(namesA)
    name=namesA{i};
    if strcmp(name,'elapsed_s'),continue;end
    same=same&&isequaln(a.(name),b.(name));
    if ~same,return;end
end
end

function x=first_numeric_field(s,names)
x=NaN;for i=1:numel(names),if isfield(s,names{i})&&isnumeric(s.(names{i}))&&isscalar(s.(names{i})),x=double(s.(names{i}));return;end,end
end

function x=first_text_field(s,names)
x='';for i=1:numel(names),if isfield(s,names{i}),x=char(string(s.(names{i})));return;end,end
end

function xb=binary_exact(x)
x=double(x(:));n=round(0.5*numel(x));[~,ord]=sortrows([-x,(1:numel(x))'],[1 2]);xb=zeros(size(x));xb(ord(1:n))=1;
end

function s=numeric_fingerprint(x)
x=double(x(:));w=(1:numel(x))';s=sprintf('n=%d;sum=%.17g;weighted=%.17g;l2=%.17g',numel(x),sum(x),sum(w.*x),norm(x));
end

function write_json(path,value)
fid=fopen(path,'w');assert(fid>=0,'Cannot write %s',path);c=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end
