function A = ms_analyze(runs)
%MS_ANALYZE  The three preregistered analyses: transition response (B9),
%   mesh scaling of the active set (B10), grayness decomposition (B11).
%
%   runs is a struct array of ms_run outputs.

A = struct();

% ================= B9: transition response ==============================
A.transitions = struct('key',{},'mesh',{},'arm',{},'events',{}, ...
                       'stopIter',{},'lastDescent',{},'gapToStop',{});
for i = 1:numel(runs)
    r = runs(i); P = r.per;
    ev = find(P.descent);
    E = struct('iter',{},'moveBefore',{},'moveAfter',{},'moveFactor',{}, ...
               'l2Before',{},'l2After',{},'l2Factor',{}, ...
               'rmsBefore',{},'rmsAfter',{},'maxBefore',{},'maxAfter',{},'maxFactor',{}, ...
               'MndBefore',{},'MndAfter',{},'MndRelChange',{}, ...
               'omega1Before',{},'omega1After',{},'omega1RelChange',{}, ...
               'volBefore',{},'volAfter',{},'stopRawAfter',{});
    for k = ev(:).'
        b = k-1; a = k;
        E(end+1) = struct( ...
            'iter', k, ...
            'moveBefore', P.move(b), 'moveAfter', P.move(a), ...
            'moveFactor', P.move(b)/P.move(a), ...
            'l2Before', P.l2(b), 'l2After', P.l2(a), 'l2Factor', P.l2(b)/P.l2(a), ...
            'rmsBefore', P.rms(b), 'rmsAfter', P.rms(a), ...
            'maxBefore', P.maxAbs(b), 'maxAfter', P.maxAbs(a), ...
            'maxFactor', P.maxAbs(b)/P.maxAbs(a), ...
            'MndBefore', P.Mnd(b), 'MndAfter', P.Mnd(a), ...
            'MndRelChange', (P.Mnd(a)-P.Mnd(b))/P.Mnd(b), ...
            'omega1Before', P.omega1(b), 'omega1After', P.omega1(a), ...
            'omega1RelChange', (P.omega1(a)-P.omega1(b))/P.omega1(b), ...
            'volBefore', P.volume(b), 'volAfter', P.volume(a), ...
            'stopRawAfter', P.stopRaw(a)); %#ok<AGROW>
    end
    if isempty(ev); last = NaN; else; last = ev(end); end
    A.transitions(end+1) = struct('key', sprintf('%s_%dx%d', r.arm, r.mesh(1), r.mesh(2)), ...
        'mesh', r.mesh, 'arm', r.arm, 'events', E, 'stopIter', r.nOuter, ...
        'lastDescent', last, 'gapToStop', r.nOuter - last);
end

% ================= B10: active-set mesh scaling =========================
% N_active is MEASURED, never assumed.  The model under test is
%     RMS(drho) ~ move * sqrt(N_active/NE)
% and it is reported as measured-vs-predicted, not fitted.
A.activeSet = struct('key',{},'mesh',{},'arm',{},'NE',{},'tau',{}, ...
    'nActiveFinal',{},'fracActiveFinal',{},'nActiveMedianLast10',{}, ...
    'rmsMeasuredFinal',{},'rmsPredictedFinal',{},'ratio',{});
for i = 1:numel(runs)
    r = runs(i); P = r.per; NE = r.NE;
    lastK = max(1, r.nOuter-9):r.nOuter;
    nAF = P.nActive(end,:);
    med = median(P.nActive(lastK,:), 1);
    % epsRMS threshold is column 1 by construction in ms_run
    predicted = P.move(end)*sqrt(nAF(1)/NE);
    A.activeSet(end+1) = struct('key', sprintf('%s_%dx%d', r.arm, r.mesh(1), r.mesh(2)), ...
        'mesh', r.mesh, 'arm', r.arm, 'NE', NE, 'tau', r.tau, ...
        'nActiveFinal', nAF, 'fracActiveFinal', nAF/NE, ...
        'nActiveMedianLast10', med, ...
        'rmsMeasuredFinal', P.rms(end), 'rmsPredictedFinal', predicted, ...
        'ratio', P.rms(end)/predicted);
end

% ================= B11: grayness decomposition ==========================
A.grayness = struct('mesh',{},'baselineMnd',{},'fixedMnd',{}, ...
    'MndRelReduction',{},'baselineGray',{},'fixedGray',{}, ...
    'baselineMid',{},'fixedMid',{},'baselineOmega1',{},'fixedOmega1',{}, ...
    'omega1RelChange',{},'baselineVol',{},'fixedVol',{});
meshes = unique(cell2mat(arrayfun(@(r) r.mesh(:).', runs, 'UniformOutput', false)'), 'rows');
for m = 1:size(meshes,1)
    b = local_pick(runs, 'baseline',  meshes(m,:));
    f = local_pick(runs, 'fixedmove', meshes(m,:));
    if isempty(b) || isempty(f); continue; end
    A.grayness(end+1) = struct('mesh', meshes(m,:), ...
        'baselineMnd', b.Mnd_final, 'fixedMnd', f.Mnd_final, ...
        'MndRelReduction', (b.Mnd_final - f.Mnd_final)/b.Mnd_final, ...
        'baselineGray', b.gray_final, 'fixedGray', f.gray_final, ...
        'baselineMid', b.mid_final, 'fixedMid', f.mid_final, ...
        'baselineOmega1', b.omega(1), 'fixedOmega1', f.omega(1), ...
        'omega1RelChange', (f.omega(1)-b.omega(1))/b.omega(1), ...
        'baselineVol', b.volume_final, 'fixedVol', f.volume_final);
end

% ================= trajectory stability for CAP_HIT arms ================
% A capped run is NOT convergence.  What can still be said is whether the
% trajectory settled, so each is characterised over its last 25 iterations.
A.stability = struct('key',{},'status',{},'omega1RelRangeLast25',{}, ...
    'MndRelRangeLast25',{},'maxAbsLast25',{},'l2Last',{},'tolOuter',{},'l2OverTol',{}, ...
    'boundSaturationFinal',{},'boundSaturationMeanLast25',{}, ...
    'MndSlopeLast30',{},'omega1SlopeLast30',{});
for i = 1:numel(runs)
    r = runs(i); P = r.per;
    w = max(1, r.nOuter-24):r.nOuter;
    % Bound saturation: how hard is the optimizer still pressing against its own
    % move limit when the run stops?  A design that has genuinely settled takes a
    % step well inside the bound; a run stopped by a bound REDUCTION is still
    % pressing against it.  This separates the two without reference to any
    % tolerance.
    sat = P.maxAbs./P.move;
    A.stability(end+1) = struct('key', sprintf('%s_%dx%d', r.arm, r.mesh(1), r.mesh(2)), ...
        'status', r.status, ...
        'omega1RelRangeLast25', (max(P.omega1(w))-min(P.omega1(w)))/mean(P.omega1(w)), ...
        'MndRelRangeLast25', (max(P.Mnd(w))-min(P.Mnd(w)))/mean(P.Mnd(w)), ...
        'maxAbsLast25', max(P.maxAbs(w)), ...
        'l2Last', P.l2(end), 'tolOuter', r.tolOuter, 'l2OverTol', P.l2(end)/r.tolOuter, ...
        'boundSaturationFinal', sat(end), 'boundSaturationMeanLast25', mean(sat(w)), ...
        'MndSlopeLast30', local_slope(P.outer, P.Mnd, r.nOuter, 30), ...
        'omega1SlopeLast30', local_slope(P.outer, P.omega1, r.nOuter, 30));
end
end

function m = local_slope(x, y, n, w)
%LOCAL_SLOPE  Least-squares slope of y over the last w iterations, per iteration.
k = max(1, n-w+1):n;
if numel(k) < 2; m = NaN; return; end
pf = polyfit(x(k), y(k), 1); m = pf(1);
end

function r = local_pick(runs, arm, mesh)
r = [];
for i = 1:numel(runs)
    if strcmp(runs(i).arm, arm) && isequal(runs(i).mesh(:).', mesh(:).'); r = runs(i); return; end
end
end
