%PERFORMANCE_AUDIT_PROPOSED_VARIANTS Cheap controlled OurApproach variants.
%
% This runner preserves the production branch and changes only decoded
% configuration values.  It exists solely for PERFORMANCE_COMPARISON_AUDIT.
% It does not reproduce or replace the unavailable 240-by-30 late state.

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
configPath = fullfile(scriptDir,'performance_comparison.json');
resultPath = fullfile(scriptDir,'performance_audit_proposed_variants.json');
addpath(fullfile(repoRoot,'tools','Matlab'));
% Required only for the optional refresh branch. A clean wrapper call does
% not add this directory even though topopt_freq calls a4_mode_screen.
addpath(fullfile(repoRoot,'scripts','revision_v1'));

base = jsondecode(fileread(configPath));
base.domain.mesh.nelx = 32;
base.domain.mesh.nely = 4;
base.optimization.approach = 'ourApproach';
base.optimization.max_iters = 80;
base.optimization.convergence_tol = 1e-6;
base.optimization.load_sensitivity = 'complete';
base.optimization.gate_a0_diagnostics = true;
% These two legacy keys are inert for semi_harmonic loads but Gate A0
% intentionally rejects them, so remove them for telemetry-enabled runs.
if isfield(base.optimization,'semi_harmonic_rho_source')
    base.optimization = rmfield(base.optimization,'semi_harmonic_rho_source');
end
base.optimization.harmonic_normalize = false;
base.postprocessing.compute_modes = 1;
base.postprocessing.save_final_image = false;
base.postprocessing.save_snapshot_image = false;
base.postprocessing.save_frequency_iterations = false;

variants = struct( ...
    'name',{},'description',{},'configure',{});
variants(end+1) = struct( ...
    'name','current_frozen_reference', ...
    'description',['Current branch semantics: solid reference eigenpair is frozen, ' ...
        'but F=omega0^2*M(x)*Phi0 still changes with x.'], ...
    'configure',@(cfg) cfg);
variants(end+1) = struct( ...
    'name','explicit_refresh_disabled', ...
    'description','Explicit update_after=0; expected to equal the default frozen-reference path.', ...
    'configure',@(cfg) localSetRefresh(cfg,0));
variants(end+1) = struct( ...
    'name','refresh_every_iteration', ...
    'description','Set update_after=1 on the active semi-harmonic mode.', ...
    'configure',@(cfg) localSetRefresh(cfg,1));
variants(end+1) = struct( ...
    'name','heaviside_flag_disabled', ...
    'description',['Set JSON filter.heaviside=false. OurApproach does not receive this ' ...
        'flag, so this is an inert-key equivalence check.'], ...
    'configure',@(cfg) localSetHeaviside(cfg,false));
variants(end+1) = struct( ...
    'name','reduced_move_limit', ...
    'description','Reduce MMA move limit from 0.2 to 0.05.', ...
    'configure',@(cfg) localSetMove(cfg,0.05));
variants(end+1) = struct( ...
    'name','omitted_load_derivative', ...
    'description','Use the paper-described omitted dF/dx sensitivity instead of the JSON default complete branch.', ...
    'configure',@(cfg) localSetLoadSensitivity(cfg,'omitted'));
variants(end+1) = struct( ...
    'name','oc_optimizer', ...
    'description','Use OC rather than the performance JSON MMA optimizer.', ...
    'configure',@(cfg) localSetOptimizer(cfg,'OC'));

records = cell(numel(variants),1);
for v = 1:numel(variants)
    cfg = variants(v).configure(base);
    wallTimer = tic;
    try
        [x,omega,tIter,nIter,mem,info] = run_topopt_from_json(cfg);
    catch ME
        rec = struct();
        rec.name = variants(v).name;
        rec.description = variants(v).description;
        rec.status = 'failed_as_designed_branch_executed';
        rec.wrapper_wall_time_seconds = toc(wallTimer);
        rec.error_identifier = ME.identifier;
        rec.error_message = ME.message;
        records{v} = rec;
        continue
    end
    wall = toc(wallTimer);
    h = info.cr2_history;
    late = max(1,nIter-19):nIter;
    finiteFrequency = h.tracked_mode_omega(isfinite(h.tracked_mode_omega));

    rec = struct();
    rec.name = variants(v).name;
    rec.description = variants(v).description;
    rec.status = 'completed';
    rec.iterations = nIter;
    rec.hit_iteration_cap = nIter >= double(cfg.optimization.max_iters);
    rec.final_change = info.last_change;
    rec.converged_by_production_test = info.last_change <= double(cfg.optimization.convergence_tol);
    rec.final_objective = info.last_obj;
    rec.final_volume = info.last_vol;
    rec.final_omega_rad_per_s = omega(:);
    rec.loop_time_seconds = tIter*nIter;
    rec.wrapper_wall_time_seconds = wall;
    rec.incremental_rss_mb = mem;
    rec.refresh = info.semi_harmonic_refresh;
    rec.final_density_signature = struct( ...
        'sum_x',sum(x), ...
        'sum_x_squared',sum(x.^2), ...
        'weighted_sum',sum((1:numel(x))'.*x), ...
        'minimum',min(x), ...
        'maximum',max(x), ...
        'grayness',mean(4*x.*(1-x)));
    rec.final_density = x(:);
    rec.last_20 = struct( ...
        'iterations',late(:), ...
        'objective',h.objective(late), ...
        'design_change_linf',h.design_change(late), ...
        'topology_lag1_linf',h.topology_lag1_linf(late), ...
        'topology_lag2_linf',h.topology_lag2_linf(late), ...
        'volume',h.volume(late), ...
        'grayness',h.grayness(late), ...
        'tracked_mode_omega',h.tracked_mode_omega(late), ...
        'tracked_mode_mac',h.tracked_mode_mac(late), ...
        'sensitivity_difference_l2',h.sensitivity_difference_l2(late));
    rec.late_summary = struct( ...
        'objective_range',max(h.objective(late))-min(h.objective(late)), ...
        'change_min',min(h.design_change(late)), ...
        'change_max',max(h.design_change(late)), ...
        'lag2_min',min(h.topology_lag2_linf(late)), ...
        'lag2_max',max(h.topology_lag2_linf(late)), ...
        'finite_tracked_frequencies',numel(finiteFrequency));
    records{v} = rec;
end

baseX = records{1}.final_density;
comparisons = struct();
comparisons.explicit_refresh_disabled_max_abs_x_difference = ...
    max(abs(baseX-records{2}.final_density));
comparisons.heaviside_flag_toggle_max_abs_x_difference = ...
    max(abs(baseX-records{4}.final_density));
comparisons.default_and_explicit_disabled_objective_difference = ...
    abs(records{1}.final_objective-records{2}.final_objective);

output = struct();
output.audit = 'performance_comparison proposed-method controlled variants';
output.status = 'completed';
output.timestamp = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
output.matlab_version = version;
output.fixture = struct( ...
    'source_config','examples/Performance/performance_comparison.json', ...
    'mesh','32x4', ...
    'maximum_iterations',80, ...
    'convergence_tolerance',1e-6, ...
    'telemetry','Gate-A0 CR2 history from the unmodified production branch');
output.refresh_dependency_defect = [ ...
    'A first clean-session refresh-every-iteration run failed at topopt_freq:552 ' ...
    'because run_topopt_from_json does not add scripts/revision_v1, where ' ...
    'a4_mode_screen is defined. This diagnostic runner adds that path explicitly.'];
output.variants = records;
output.cross_variant_comparisons = comparisons;
output.unavailable_requested_experiments = { ...
    ['A truly fixed RHS cannot be selected by the JSON interface: freezing the reference ' ...
     'eigenpair still leaves F=omega0^2*M(x)*Phi0 design dependent.'], ...
    ['Restarting the unavailable 240x30 late state with preserved MMA history is impossible: ' ...
     'the original run saved neither x nor MMA asymptotes/history and topopt_freq exposes no restart input.'], ...
    ['Restarting that state with reset MMA asymptotes is impossible for the same missing-state ' ...
     'and missing-restart-interface reasons.'], ...
    ['Direct comparison of the two alleged alternating 240x30 states is impossible: no state ' ...
     'vectors or hashes from iterations 9997-10000 were persisted.'], ...
    ['Alternative stopping metrics beyond max(abs(x_k-x_{k-1})) cannot be reconstructed for ' ...
     'the original run because only console scalars, not late topology vectors, were retained.']};
output.limitations = { ...
    'Small-mesh dynamics can falsify mechanisms but cannot establish the 240x30 cycle period.', ...
    'The variant timings are diagnostic only and are not performance estimates.', ...
    'No production numerical behavior was edited by this runner.'};

fid = fopen(resultPath,'w');
if fid < 0
    error('PerformanceAuditVariants:Write','Unable to create %s',resultPath);
end
cleanupFid = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(output,PrettyPrint=true));
fprintf('\nPerformance audit proposed-method variants completed.\n');
fprintf('Saved: %s\n',resultPath);
for v = 1:numel(records)
    rec = records{v};
    if strcmp(rec.status,'completed')
        fprintf('  %-27s it=%3d cap=%d ch=%8.3e obj=%10.3f omega1=%9.3f refresh=%d\n', ...
            rec.name,rec.iterations,rec.hit_iteration_cap,rec.final_change, ...
            rec.final_objective,rec.final_omega_rad_per_s(1),rec.refresh.n_refresh);
    else
        fprintf('  %-27s FAILED: %s\n',rec.name,rec.error_identifier);
    end
end
fprintf('  Heaviside flag max|delta x|: %.3e\n', ...
    comparisons.heaviside_flag_toggle_max_abs_x_difference);

function cfg = localSetRefresh(cfg,value)
cfg.domain.load_cases(1).loads(1).update_after = value;
end

function cfg = localSetHeaviside(cfg,value)
cfg.optimization.filter.heaviside = value;
end

function cfg = localSetMove(cfg,value)
cfg.optimization.move_limit = value;
end

function cfg = localSetLoadSensitivity(cfg,value)
cfg.optimization.load_sensitivity = value;
end

function cfg = localSetOptimizer(cfg,value)
cfg.optimization.optimizer = value;
end
