% Phase 2I WP10: complete hard-gate quantities and cutoff-tie explanations.
repo=fileparts(fileparts(fileparts(mfilename('fullpath'))));outDir=fileparts(mfilename('fullpath'));
addpath(fullfile(repo,'analysis','iteration_efficiency_phase2a'));
S=load(fullfile(outDir,'raw','capture_96x12_H3200.mat'),'Xd','Xs');
Xd=S.Xd(:,2:end);Xs=double(S.Xs(:,2:end));n=size(Xd,2);nx=96;ny=12;
rows=cell(n,25);brows={};br=0;
for k=1:n
 xd=Xd(:,k);xs=Xs(:,k);td=ie2a.topology_metrics(xd,nx,ny);ts=ie2a.topology_metrics(xs,nx,ny);
 diff=find(td.binary~=ts.binary);ne=numel(xd);ns=round(.5*ne);
 [~,od]=sortrows([-xd,(1:ne).'],[1 2]);[~,os]=sortrows([-xs,(1:ne).'],[1 2]);
 gapD=xd(od(ns))-xd(od(ns+1));gapS=xs(os(ns))-xs(os(ns+1));cutS=xs(os(ns));tie=find(xs==cutS);
 tieStraddle=gapS==0;explained=isempty(diff)||(tieStraddle&&all(ismember(diff,tie)));
 rows(k,:)={k,td.volume_pass,ts.volume_pass,td.required_connected,ts.required_connected, ...
  td.topology_pass,ts.topology_pass,td.hard_gate_pass,ts.hard_gate_pass,numel(diff),explained, ...
  td.max_detached_area,ts.max_detached_area,td.n_islands_significant,ts.n_islands_significant, ...
  td.aggregate_detached_area,ts.aggregate_detached_area,td.n_islands_all,ts.n_islands_all, ...
  gapD,gapS,numel(tie),tieStraddle,td.n_solid,ts.n_solid};
 if ~isempty(diff)
  br=br+1;brows(br,:)={k,numel(diff),gapD,gapS,cutS,numel(tie),tieStraddle,all(ismember(diff,tie)),explained, ...
   td.hard_gate_pass,ts.hard_gate_pass,td.topology_pass,ts.topology_pass,td.max_detached_area,ts.max_detached_area}; %#ok<AGROW>
 end
end
names={'k','volume_pass_double','volume_pass_single','required_connected_double','required_connected_single', ...
 'topology_pass_double','topology_pass_single','hard_gate_pass_double','hard_gate_pass_single', ...
 'binary_differing_elements','binary_difference_explained','max_detached_area_double','max_detached_area_single', ...
 'n_islands_significant_double','n_islands_significant_single','aggregate_detached_area_double','aggregate_detached_area_single', ...
 'n_islands_all_double','n_islands_all_single','cutoff_gap_double','cutoff_gap_single','single_cutoff_tie_group_size', ...
 'single_tie_straddles_cutoff','n_solid_double','n_solid_single'};
writetable(cell2table(rows,'VariableNames',names),fullfile(outDir,'HARD_GATE_EQUIVALENCE.csv'));
writetable(cell2table(brows,'VariableNames',{'k','binary_differing_elements','cutoff_gap_double','cutoff_gap_single', ...
 'single_cutoff_density','single_cutoff_tie_group_size','single_tie_straddles_cutoff','all_changed_inside_tie_group', ...
 'difference_explained','hard_gate_double','hard_gate_single','topology_double','topology_single', ...
 'max_detached_area_double','max_detached_area_single'}),fullfile(outDir,'BINARY_DIFFERENCE_ANALYSIS.csv'));
