function mt_export(out, csvPath)
%MT_EXPORT  Write the per-iteration telemetry required by sec. 13 of the brief.
P = out.per;
T = table(P.outer, P.omega1, P.omega2, P.gap12, P.volume, ...
          P.Mnd, P.gray, P.mid, ...
          P.move, P.stage, P.itersSinceMoveChange, double(P.descent), ...
          P.maxAbs, P.rms, P.l2, P.ratio, double(P.utilBelow), P.utilCount, ...
          P.beta, P.betaStallRel, double(P.betaStallFires), P.objRelRange, ...
          P.nInner, double(P.innerConv), P.multN, P.degen, double(P.multJ), ...
    'VariableNames', {'outer','omega1','omega2','gap12','volume', ...
      'Mnd_pct','gray_frac','mid_frac', ...
      'move','stage','itersSinceMoveChange','moveDescent', ...
      'maxAbs','rms','l2','r_rho','r_rho_below_thr','utilPersistCount', ...
      'beta','betaStallRel','betaStallFires','objRelRange_W10', ...
      'nInner','innerConv','multN','degen','multJ'});
writetable(T, csvPath);
fprintf('[mt_export] %s (%d rows, %d cols)\n', csvPath, height(T), width(T));
end
