function S = mt_stages(P, lastIter)
%MT_STAGES  Stage-by-stage analysis (brief sec. 15), up to lastIter inclusive.
if nargin < 2 || isempty(lastIter); lastIter = numel(P.outer); end
edges = find(P.moveChanged & P.outer <= lastIter);
S = struct('stage',{},'move',{},'first',{},'last',{},'nIter',{}, ...
           'Mnd0',{},'Mnd1',{},'dMnd',{},'w0',{},'w1',{},'dw',{}, ...
           'rMed',{},'rMin',{},'rMax',{},'finalCount',{},'mature',{});
for k = 1:numel(edges)
    a = edges(k);
    if k < numel(edges); b = edges(k+1)-1; else; b = lastIter; end
    r = P.ratio(a:b);
    S(k) = struct('stage',P.stage(a),'move',P.move(a),'first',a,'last',b, ...
        'nIter',b-a+1,'Mnd0',P.Mnd(a),'Mnd1',P.Mnd(b),'dMnd',P.Mnd(b)-P.Mnd(a), ...
        'w0',P.omega1(a),'w1',P.omega1(b),'dw',P.omega1(b)-P.omega1(a), ...
        'rMed',median(r),'rMin',min(r),'rMax',max(r), ...
        'finalCount',P.utilCount(min(b+1,numel(P.outer))), ...
        'mature', P.utilCount(min(b+1,numel(P.outer))) >= 10 || (b==lastIter));
end
end
