function T = mt_transitions(P)
%MT_TRANSITIONS  Per-descent record (brief sec. 14): the state IMMEDIATELY
%   BEFORE each descent, plus the r_rho history of the preceding 10 iterations.
d = find(P.descent);
T = struct('iter',{},'moveFrom',{},'moveTo',{},'rrhoPrev10',{}, ...
           'allBelow',{},'countAtCall',{},'Mnd',{},'gray',{},'mid',{}, ...
           'omega1',{},'volume',{});
for k = 1:numel(d)
    i = d(k);
    lo = max(1, i-10); hi = i-1;
    rr = P.ratio(lo:hi).';
    T(k) = struct('iter',i,'moveFrom',P.move(i-1),'moveTo',P.move(i), ...
        'rrhoPrev10',rr,'allBelow',all(rr < 0.5) && numel(rr)==10, ...
        'countAtCall',P.utilCount(i), ...
        'Mnd',P.Mnd(i-1),'gray',P.gray(i-1),'mid',P.mid(i-1), ...
        'omega1',P.omega1(i-1),'volume',P.volume(i-1));
end
end
