function schema = confbench_timing_schema()
%CONFBENCH_TIMING_SCHEMA  What every reported count and time means, per method.
%
%   Written to timing_schema.json beside the results so that no reader has to
%   infer the semantics from a column header.  The central statement is that
%   the counts and the component times are METHOD-NATIVE and not mathematically
%   identical across methods; total wall time is the common quantity.

schema = struct();
schema.schema_version = 'conference_benchmark_timing/2';
schema.schema_history = struct( ...
    'v1', ['Proposed time1 = solver initialization INCLUDING the reference ' ...
        'eigenanalysis (stage1_eigenanalysis_and_preparation_s).'], ...
    'v2', ['2026-09-14: Proposed time1 = the reference eigenanalysis ALONE ' ...
        '(stage1_reference_eigenanalysis_s); the preparation moved to ' ...
        'overhead_time_s, where the Yuksel and Du-Olhoff records already ' ...
        'place their setup, so that the Other column means the same thing on ' ...
        'every row. Recorded v1 rows are brought to v2 by ' ...
        'confbench_proposed_times from their recorded sub-interval timers ' ...
        '(stage1_time_s, stage1_reference_eigen_time_s); nothing is re-timed.']);

schema.common = struct( ...
    'total_wall_time_s', ['Caller-side tic/toc around the solve and nothing ' ...
        'else. CSV/JSON/MAT writing, plotting, table formatting, LaTeX ' ...
        'generation, the common E1/E2/E3 evaluator and topology rendering ' ...
        'are all outside it.'], ...
    'overhead_time_s', ['Whatever the solve spends outside the two named ' ...
        'stages: configuration dispatch, model build, filter preparation, ' ...
        'the final modal analysis and result assembly. It exists so that no ' ...
        'microsecond has to be forced into a named stage. Printed in the ' ...
        'table as the "Other [s]" column, for every method alike.'], ...
    'identity', 'total_wall_time_s = time1 + time2 + overhead_time_s  (Total = Time 1 + Time 2 + Other on every table row)', ...
    'timing_accounting_residual_s', ...
        'total_wall_time_s minus (time1 + time2 + overhead_time_s).', ...
    'timing_accounting_fail', ['TIMING_ACCOUNTING_FAIL: set when the residual ' ...
        'exceeds the predeclared tolerance recorded alongside it.'], ...
    'independent_crosscheck_residual_s', ['A SECOND, independent measurement ' ...
        'of the same interval: the caller-side total minus the solver''s own ' ...
        'self-reported wall time. Unlike the identity above it is not an ' ...
        'algebraic tautology, so it detects a mis-nested timer.'], ...
    'threads', 'All runs are single-threaded (maxNumCompThreads(1)).', ...
    'memory', ['NOT MEASURED and NOT REPORTED. Reliable, method-independent ' ...
        'peak-memory measurement was not available in the MATLAB environment; ' ...
        'memory was omitted rather than reported with inconsistent semantics.']);

schema.methods = struct();

schema.methods.Proposed = struct( ...
    'architecture', 'one reference eigenanalysis, then a SIMP topology optimization', ...
    'count1', struct('name','eigenanalysis_solves', 'value','always 1', ...
        'meaning', ['The number of reference eigenanalyses performed. This ' ...
        'is a SOLVE count. It is NOT an optimization iteration and must not ' ...
        'be read as one.']), ...
    'count2', struct('name','simp_iterations', ...
        'meaning','SIMP topology-optimization iterations.'), ...
    'time1', struct('name','stage1_reference_eigenanalysis_s', ...
        'boundary', ['the single reference eigenanalysis of the solid ' ...
        'domain and NOTHING else: assembly of K0 and M0, the eigensolve, ' ...
        'extraction of the frozen mode(s). Solver preparation (mesh, ' ...
        'element matrices, connectivity, filter, boundary conditions) is ' ...
        'NOT in it; it is in overhead_time_s. The detailed CSV keeps ' ...
        'stage1_time_s (initialization including the eigenanalysis, the ' ...
        'schema-1 Time 1) and stage1_preparation_time_s = stage1_time_s - ' ...
        'time1.']), ...
    'time2', struct('name','stage2_simp_time_s', ...
        'boundary','the SIMP optimization loop only.'), ...
    'assertions', {{'stage1_reference_eigen_solves == 1', ...
        'time1 <= stage1_time_s (the eigenanalysis is a sub-interval of the initialization)', ...
        'overhead_time_s = total_wall_time_s - time1 - time2 (preparation + final modal analysis + dispatch)'}});

schema.methods.Yuksel = struct( ...
    'architecture', 'two sequential optimization stages', ...
    'count1', struct('name','stage1_iterations','meaning','Stage-1 optimization iterations.'), ...
    'count2', struct('name','stage2_iterations','meaning','Stage-2 optimization iterations.'), ...
    'time1', struct('name','stage1_time_s','boundary','the Stage-1 loop only.'), ...
    'time2', struct('name','stage2_time_s','boundary','the Stage-2 loop only; disjoint from Stage 1.'), ...
    'assertions', {{'N_total = N1 + N2', 'T1 + T2 = optimization_loop_time (non-overlapping timers)'}});

olhPreset = olhoffcurrent_preset(confbench_olhoff_preset());
schema.methods.DuOlhoffReconstruction = struct( ...
    'label', olhPreset.displayName, ...
    'preset', olhPreset.name, ...
    'upstream_preset', olhPreset.upstreamPreset, ...
    'upstream_commit', olhPreset.upstreamCommit, ...
    'architecture', ['NESTED: an outer loop, each of whose iterations contains ' ...
        'a complete MMA sub-optimization.'], ...
    'count1', struct('name','outer_iterations','meaning','Fig. 1 outer iterations.'), ...
    'count2', struct('name','inner_mma_iterations_total', ...
        'meaning','cumulative nested MMA sub-iterations over the whole run.'), ...
    'time1', struct('name','outer_time_excluding_inner_s', ...
        'boundary', ['every computational region of an outer iteration EXCEPT ' ...
        'the nested MMA solve: FE assembly, the eigenproblem, modal ' ...
        'processing, generalized-gradient sensitivities, sensitivity ' ...
        'filtering, local subproblem construction, the step controller, the ' ...
        'design update, bookkeeping and the convergence test. Measured as ' ...
        'sum(t_outer) - sum(t_inner) from per-iteration timers, so the nested ' ...
        'solve cannot be double-counted.']), ...
    'time2', struct('name','inner_mma_time_total_s', ...
        'boundary','the nested MMA loop, and only that.'), ...
    'derived', {{'inner_iterations_per_outer_mean', 'inner_time_per_outer_mean_s', ...
        'inner_time_per_inner_iteration_mean_s', 'inner_time_share_pct'}}, ...
    'per_outer_iteration_cost', struct( ...
        'why', ['the outer iteration count need not be monotone in the mesh, so ' ...
            'total wall time alone cannot be read as a per-iteration scaling law'], ...
        'fields', {{'outer_time_total_s = sum(t_outer)', ...
            'outer_time_per_outer_mean_s = sum(t_outer)/N_outer', ...
            'outer_time_per_outer_median_s = median(t_outer)', ...
            'outer_time_excluding_inner_per_outer_mean_s = (sum(t_outer)-sum(t_inner))/N_outer', ...
            'eigen_time_per_outer_mean_s = sum(t_eig)/N_outer (FE assembly + eigensolve)', ...
            'gradient_time_per_outer_mean_s = sum(t_grad)/N_outer', ...
            'total_wall_time_per_outer_s = total_wall_time_s/N_outer', ...
            'inner_time_per_outer_mean_s, inner_time_per_inner_iteration_mean_s'}}), ...
    'prohibited', ['N_outer + N_inner must NEVER be reported as a generic ' ...
        'iteration count: the two are different objects.'], ...
    'caveat', olhoffcurrent_caveat(olhPreset.name));

schema.cross_method_warning = ['Count and time columns represent method-native ' ...
    'computational stages and are not mathematically identical across ' ...
    'methods. Total wall time is the common performance quantity.'];
end
