function man = confbench_manifest(cfg, methodConfigs, resolvedImpl)
%CONFBENCH_MANIFEST  Record exactly what is about to run.  Output, not control.
%
%   man = CONFBENCH_MANIFEST(cfg, methodConfigs, resolvedImpl)
%
%   The manifest is GENERATED FROM the runtime configuration; it never feeds
%   back into it.  The direction is
%
%       user edits cfg  ->  cfg validated  ->  benchmark runs  ->  manifest records
%
%   and never the reverse.  Editing this file changes what is RECORDED, not
%   what is RUN; to change what runs, edit cfg.resolutions in
%   performance_comparison.m.
%
%   See also CONFBENCH_PREFLIGHT, PERFORMANCE_COMPARISON.

here = fileparts(mfilename('fullpath'));
repo = fileparts(fileparts(fileparts(here)));

man = struct();
man.manifest_schema = 'conference_performance_benchmark/1';
man.generated_datetime = datetime('now', 'TimeZone', 'local', 'Format', ...
    'yyyy-MM-dd''T''HH:mm:ssXXX');
man.generated_datetime = char(string(man.generated_datetime));
man.generated_by = 'examples/Performance/performance_comparison.m';
man.manifest_role = ['OUTPUT. Generated from the runtime configuration. It is ' ...
    'not a source of scientific settings and nothing reads it back.'];

% ---- the runtime configuration, verbatim -------------------------------
man.configuration = cfg;
man.active_resolutions = cfg.resolutions;
man.active_resolutions_count = size(cfg.resolutions, 1);
man.active_methods = activeMethodList(cfg);
man.element_counts = cfg.resolutions(:,1) .* cfg.resolutions(:,2);

% ---- per-method frozen scientific settings -----------------------------
man.method_configurations = methodConfigs;

% ---- implementation identity -------------------------------------------
man.resolved_implementations = resolvedImpl;

% ---- source hashes ------------------------------------------------------
tracked = { ...
    'examples/Performance/performance_comparison.m', ...
    'examples/Performance/conference_bench/confbench_method_config.m', ...
    'examples/Performance/conference_bench/confbench_run_case.m', ...
    'examples/Performance/conference_bench/confbench_preflight.m', ...
    'examples/Performance/conference_bench/confbench_manifest.m', ...
    'examples/Performance/conference_bench/confbench_export.m', ...
    'examples/Performance/conference_bench/confbench_timing_schema.m', ...
    'examples/Performance/conference_bench/confbench_caveats.m', ...
    'examples/Performance/conference_bench/confbench_scaling_fit.m', ...
    'analysis/OlhoffCurrent/olhoffcurrent_preset.m', ...
    'analysis/OlhoffCurrent/olhoffcurrent_config.m', ...
    'analysis/OlhoffCurrent/olhoffcurrent_run.m', ...
    'analysis/OlhoffCurrent/olhoffcurrent_paths.m', ...
    'analysis/OlhoffCurrent/olhoffcurrent_assert_dispatch.m', ...
    'analysis/OlhoffCurrent/PROVENANCE.json', ...
    'analysis/ourApproach/Matlab/topopt_freq.m', ...
    'analysis/YukselApproach/Matlab/top99neo_inertial_freq.m', ...
    'tools/Matlab/run_topopt_from_json.m', ...
    'analysis/three_method_parametric_study/study_base_config.m', ...
    'analysis/three_method_parametric_study/study_evaluate_design.m', ...
    'analysis/three_method_parametric_study/results/profile_freeze_manifest.json'};
man.source_hashes = struct();
for i = 1:numel(tracked)
    p = fullfile(repo, tracked{i});
    key = matlab.lang.makeValidName(tracked{i});
    if exist(p, 'file') == 2
        man.source_hashes.(key) = struct('path', tracked{i}, ...
            'sha256', olhoffcurrent_sha256_file(p));
    else
        man.source_hashes.(key) = struct('path', tracked{i}, 'sha256', 'MISSING');
    end
end

% ---- production Olhoff implementation: provenance and integrity ---------
% Recorded so that every result can answer "what implementation produced this
% number?" from the artifact alone: which tree, promoted from which upstream
% commit, at which named preset, and with which source-tree hash.
prov   = olhoffcurrent_provenance();
srcMan = olhoffcurrent_source_manifest();
cur    = olhoffcurrent_currentness('Verbose', false);
man.olhoff_implementation = struct( ...
    'implementation', 'analysis/OlhoffCurrent', ...
    'role', 'PRODUCTION - the only Olhoff implementation production may execute', ...
    'production_preset', prov.production_preset, ...
    'upstream_preset_alias', prov.production_preset_upstream_alias, ...
    'promoted_from_repository', prov.source.repository, ...
    'promoted_from_branch', prov.source.branch, ...
    'promoted_from_commit', prov.source.commit, ...
    'promotion_date', prov.promotion_date, ...
    'source_tree_sha256', srcMan.treeHash, ...
    'source_n_files', srcMan.nFiles, ...
    'source_integrity_ok', srcMan.ok, ...
    'currentness_state', cur.state, ...
    'main_repo_commit', prov.main_repo_commit, ...
    'epistemic_status', olhoffcurrent_caveat(), ...
    'implementation_map', 'analysis/OLHOFF_IMPLEMENTATION_MAP.md');

% ---- environment --------------------------------------------------------
man.environment = struct( ...
    'matlab_version', version(), ...
    'matlab_release', version('-release'), ...
    'computer', computer(), ...
    'max_num_comp_threads', maxNumCompThreads(), ...
    'single_thread_requested', cfg.singleThread, ...
    'blas_library', blasLibraryOrUnknown(), ...
    'hostname', hostnameOrUnknown());

% ---- repository state ---------------------------------------------------
man.repository = repositoryState(repo);

% ---- what this run is, epistemically -----------------------------------
man.run_class = struct( ...
    'run_label', cfg.runLabel, ...
    'scientific_evidence', cfg.scientificEvidence, ...
    'performance_campaign', cfg.performanceCampaign, ...
    'max_outer_override', cfg.maxOuterOverride, ...
    'yuksel_max_iters', fieldOrDefault(cfg, 'yukselMaxIters', []), ...
    'yuksel_max_iters_frozen', confbench_frozen_budget('yuksel'), ...
    'warmup_performed', cfg.runWarmup);

man.caveats = confbench_caveats();
man.timing_schema = confbench_timing_schema();
end

% =========================================================================
function v = fieldOrDefault(S, name, dflt)
if isfield(S, name) && ~isempty(S.(name)); v = S.(name); else; v = dflt; end
end

% =========================================================================
function names = activeMethodList(cfg)
names = {};
fn = fieldnames(cfg.methods);
for i = 1:numel(fn)
    if cfg.methods.(fn{i}); names{end+1} = fn{i}; end %#ok<AGROW>
end
end

function s = repositoryState(repo)
s = struct('path', repo, 'git_available', false, 'head', 'UNKNOWN', ...
    'branch', 'UNKNOWN', 'dirty', 'UNKNOWN', 'dirty_files', {{}});
[st, head] = system(sprintf('git -C "%s" rev-parse HEAD', repo));
if st ~= 0; return; end
s.git_available = true;
s.head = strtrim(head);
[~, br] = system(sprintf('git -C "%s" rev-parse --abbrev-ref HEAD', repo));
s.branch = strtrim(br);
[~, porcelain] = system(sprintf('git -C "%s" status --porcelain', repo));
porcelain = strtrim(porcelain);
s.dirty = ~isempty(porcelain);
if s.dirty
    lines = strsplit(porcelain, newline);
    s.dirty_files = lines(~cellfun(@isempty, lines));
    s.dirty_file_count = numel(s.dirty_files);
else
    s.dirty_file_count = 0;
end
end

function v = blasLibraryOrUnknown()
try
    v = version('-blas');
catch
    v = 'UNKNOWN';
end
end

function h = hostnameOrUnknown()
try
    [st, h] = system('hostname');
    if st ~= 0; h = 'UNKNOWN'; else; h = strtrim(h); end
catch
    h = 'UNKNOWN';
end
end
