function schema = confbench_timing_schema()
%CONFBENCH_TIMING_SCHEMA  What every reported count and time means, per method.
%
%   Written to timing_schema.json beside the results so that no reader has to
%   infer the semantics from a column header.  The central statement is that
%   the counts and the component times are METHOD-NATIVE and not mathematically
%   identical across methods; total wall time is the common quantity.

schema = struct();
schema.schema_version = 'conference_benchmark_timing/1';

schema.common = struct( ...
    'total_wall_time_s', ['Caller-side tic/toc around the solve and nothing ' ...
        'else. CSV/JSON/MAT writing, plotting, table formatting, LaTeX ' ...
        'generation, the common E1/E2/E3 evaluator and topology rendering ' ...
        'are all outside it.'], ...
    'overhead_time_s', ['Whatever the solve spends outside the two named ' ...
        'stages: configuration dispatch, model build, filter preparation, ' ...
        'the final modal analysis and result assembly. It exists so that no ' ...
        'microsecond has to be forced into a named stage.'], ...
    'identity', 'total_wall_time_s = time1 + time2 + overhead_time_s', ...
    'timing_accounting_residual_s', ...
        'total_wall_time_s minus (time1 + time2 + overhead_time_s).', ...
    'timing_accounting_fail', ['TIMING_ACCOUNTING_FAIL: set when the residual ' ...
        'exceeds the predeclared tolerance recorded alongside it.'], ...
    'independent_crosscheck_residual_s', ['A SECOND, independent measurement ' ...
        'of the same interval: the caller-side total minus the solver''s own ' ...
        'self-reported wall time. Unlike the identity above it is not an ' ...
        'algebraic tautology, so it detects a mis-nested timer.'], ...
    'threads', 'All runs are single-threaded (maxNumCompThreads(1)).', ...
    'memory', ['NOT MEASURED and NOT REPORTED. Reliable, method-independent ' ...
        'peak-memory measurement was not available in the MATLAB environment; ' ...
        'memory was omitted rather than reported with inconsistent semantics.']);

schema.methods = struct();

schema.methods.Proposed = struct( ...
    'architecture', 'one reference eigenanalysis, then a SIMP topology optimization', ...
    'count1', struct('name','eigenanalysis_solves', 'value','always 1', ...
        'meaning', ['The number of reference eigenanalyses performed. This ' ...
        'is a SOLVE count. It is NOT an optimization iteration and must not ' ...
        'be read as one.']), ...
    'count2', struct('name','simp_iterations', ...
        'meaning','SIMP topology-optimization iterations.'), ...
    'time1', struct('name','stage1_eigenanalysis_and_preparation_s', ...
        'boundary', ['solver initialization: mesh and element matrices, ' ...
        'boundary conditions, filter preparation, and the single reference ' ...
        'eigenanalysis. stage1_reference_eigen_time_s isolates the ' ...
        'eigenanalysis alone and is a SUB-INTERVAL of this.']), ...
    'time2', struct('name','stage2_simp_time_s', ...
        'boundary','the SIMP optimization loop only.'));

schema.methods.Yuksel = struct( ...
    'architecture', 'two sequential optimization stages', ...
    'count1', struct('name','stage1_iterations','meaning','Stage-1 optimization iterations.'), ...
    'count2', struct('name','stage2_iterations','meaning','Stage-2 optimization iterations.'), ...
    'time1', struct('name','stage1_time_s','boundary','the Stage-1 loop only.'), ...
    'time2', struct('name','stage2_time_s','boundary','the Stage-2 loop only; disjoint from Stage 1.'), ...
    'assertions', {{'N_total = N1 + N2', 'T1 + T2 = optimization_loop_time (non-overlapping timers)'}});

schema.methods.DuOlhoffReconstructionM4 = struct( ...
    'label', 'Du-Olhoff reconstruction (M4)', ...
    'architecture', ['NESTED: an outer loop, each of whose iterations contains ' ...
        'a complete MMA sub-optimization.'], ...
    'count1', struct('name','outer_iterations','meaning','Fig. 1 outer iterations.'), ...
    'count2', struct('name','inner_mma_iterations_total', ...
        'meaning','cumulative nested MMA sub-iterations over the whole run.'), ...
    'time1', struct('name','outer_time_excluding_inner_s', ...
        'boundary', ['every computational region of an outer iteration EXCEPT ' ...
        'the nested MMA solve: FE assembly, the eigenproblem, modal ' ...
        'processing, generalized-gradient sensitivities, sensitivity ' ...
        'filtering, local subproblem construction, the step controller, the ' ...
        'design update, bookkeeping and the convergence test. Measured as ' ...
        'sum(t_outer) - sum(t_inner) from per-iteration timers, so the nested ' ...
        'solve cannot be double-counted.']), ...
    'time2', struct('name','inner_mma_time_total_s', ...
        'boundary','the nested MMA loop, and only that.'), ...
    'derived', {{'inner_iterations_per_outer_mean', 'inner_time_per_outer_mean_s', ...
        'inner_time_per_inner_iteration_mean_s', 'inner_time_share_pct'}}, ...
    'prohibited', ['N_outer + N_inner must NEVER be reported as a generic ' ...
        'iteration count: the two are different objects.'], ...
    'caveat', olhoffm4_caveat());

schema.cross_method_warning = ['Count and time columns represent method-native ' ...
    'computational stages and are not mathematically identical across ' ...
    'methods. Total wall time is the common performance quantity.'];
end
