function c = confbench_caveats()
%CONFBENCH_CAVEATS  Text that must travel with the results, in one place.
%
%   These strings go into the JSON metadata, the generated benchmark notes and
%   the LaTeX caption.  They are written once here so the table, the file and
%   the slide cannot drift apart.

c = struct();

c.table_caption = ['Count/time columns represent method-native computational ' ...
    'stages and are not mathematically identical across methods. Total wall ' ...
    'time is the common performance quantity.'];

olhPreset = olhoffcurrent_preset(confbench_olhoff_preset());
c.olhoff = olhoffcurrent_caveat(olhPreset.name);

c.olhoff_label = sprintf(['The Olhoff column is labelled "%s" and must not be ' ...
    'labelled "Olhoff 2007". It is produced by analysis/Olhoff at the named ' ...
    'preset %s (upstream preset %s @ %s). It is NOT the historical SIMP + eq. (4b) ' ...
    'realization that earlier campaigns labelled "Du-Olhoff reconstruction (M4)" ' ...
    '(preset duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered): the two differ in ' ...
    'the low-density material law and the outer controller.'], olhPreset.displayName, ...
    olhPreset.name, olhPreset.upstreamPreset, olhPreset.upstreamCommit(1:7));

c.other_column = ['Stage time [s] = Time 1 + Time 2, computed before rounding. ' ...
    'Other [s] is overhead_time_s: everything inside the timed solve but ' ...
    'outside the two named stages, including setup, final modal analysis ' ...
    'and result assembly. Other includes computations too. ' ...
    'Total wall time [s] = Stage time + Other. Method-specific configuration ' ...
    'dispatch is included only where it lies inside the recorded timer; ' ...
    'Du-Olhoff configuration resolution precedes its timer.'];

% omega_1 columns.  The dagger rule is a rule on the RECORDS, not a judgement:
% a native value that deviates from the common-evaluator value by more than
% omega1_native_flag_tol is flagged, and the notes list what the flagged rows
% carry (native omega_1..3, E1 selected mode and its void kinetic-energy share).
c.omega1_native_flag_tol = 0.05;
c.omega1_columns = sprintf(['omega_1 native is the first eigenfrequency of the ' ...
    'converged design under the solver''s own material model, which differs ' ...
    'per method (Proposed: SIMP p = 3, E_min = 1e-9 E_0, linear mass, rho_min = ' ...
    '1e-9, design floor 0; Yuksel: SIMP p = 3, E_min = 1e-9 E_0, mass linear ' ...
    'above rho = 0.1 and proportional to the sixth power of rho below it; ' ...
    'Du-Olhoff: Pedersen stiffness, linear mass). omega_1 E1 is the same design ' ...
    'under the frozen common evaluator E1 (SIMP p = 3, E_min = 1e-6 E_0, linear ' ...
    'mass), classifier-selected structural mode, computed outside every timer; ' ...
    'it is the only omega_1 that is comparable across methods. A dagger marks a ' ...
    'native value that deviates from E1 by more than %g%%: the native model ' ...
    'then returns a localized mode of near-void elements, not the structural ' ...
    'frequency.'], 100*c.omega1_native_flag_tol);

c.proposed_preparation = ['Proposed Stage 1 preparation (initialization minus the ' ...
    'reference eigenanalysis) is one-off setup and is reported in Other, never ' ...
    'in Time 1. It is a fixed cost that does not scale with the mesh; the ' ...
    'first measured row of a session also carries that session''s first-call ' ...
    'costs.'];

c.sparse_step = ['Per-iteration cost of all three methods steps up between ' ...
    '640x80 and 720x90 while the Du-Olhoff inner MMA, which does no sparse ' ...
    'assembly, does not. The step coincides with the number of DOFs crossing ' ...
    '2^17 = 131072 (103842 at 640x80, 131222 at 720x90). All three solvers ' ...
    'assemble K and M with MATLAB sparse(i,j,v,n,n) every iteration, and in ' ...
    'isolation that call measured about 4x slower for n >= 131072 (MATLAB ' ...
    'R2025b, Apple silicon, 1 thread, 2026-09-14: 0.086 s at n = 131000, ' ...
    '0.382 s at n = 131072, 4e6 triplets), whereas backslash, decomposition ' ...
    'and eigs scale smoothly across the same sizes. Exponents fitted across ' ...
    'this boundary include the step: they describe the assembly primitive as ' ...
    'much as the methods.'];

c.memory = ['Reliable, method-independent peak-memory measurement was not ' ...
    'available in the MATLAB environment; memory was omitted rather than ' ...
    'reported with inconsistent semantics.'];

switch olhPreset.name
    case 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered'
        c.olhoff_iteration_counts = ['The outer iteration count of the Du-Olhoff ' ...
            'reconstruction is set by its per-element adaptive move box and its ' ...
            'mesh-scaled design-change tolerance, neither of which the original ' ...
            'publication specifies, and it is NOT monotone in the mesh (committed ' ...
            'R = 0.06 sweep: 121, 111, 101, 93, 112, 130, 156, 204, 246 outer ' ...
            'iterations from 160x20 to 800x100). Per-outer-iteration cost is ' ...
            'therefore reported next to total wall time.'];
    otherwise
        c.olhoff_iteration_counts = ['The outer iteration count of the Du-Olhoff ' ...
            'reconstruction depends on a move-limit continuation schedule that the ' ...
            'original publication does not specify. The frozen schedule used here ' ...
            'is documented; a different admissible schedule changes the count ' ...
            'without changing the physics.'];
end

c.scaling = ['Scaling exponents may be fitted only to complete campaign data ' ...
    'and never to smoke or preflight runs. For the Du-Olhoff reconstruction ' ...
    'the outer iteration count is a property of the reconstruction''s controller ' ...
    'and stop, not of the published method, and need not be monotone in the ' ...
    'mesh; a total-time exponent mixes per-iteration cost with that count, so ' ...
    'the per-outer-iteration cost fit is reported alongside it. Either exponent ' ...
    'describes this reconstruction, not the published method.'];
end
