function files = confbench_refresh_tables(campaignDir)
%CONFBENCH_REFRESH_TABLES Regenerate CSV/LaTeX tables without running solvers.
% Preserves benchmark_results.json, manifest, timing schema and original notes.
% Schema-1 Proposed rows are re-accounted from recorded sub-interval timers.
% Example (with conference_bench and analysis/Olhoff on the MATLAB path):
%   confbench_refresh_tables('examples/Performance/conference_benchmark/campaign_9mesh_r2')
source = jsondecode(fileread(fullfile(campaignDir, 'benchmark_results.json')));
R = source.runs;
if iscell(R); R = vertcat(R{:}); end
for i = 1:numel(R)
    T = R(i).times;
    if strcmp(R(i).method_key, 'proposed') && ...
            strcmp(T.time1_name, 'stage1_eigenanalysis_and_preparation_s')
        R(i).times = confbench_proposed_times(T.stage1_time_s, ...
            T.stage1_reference_eigen_time_s, T.time2, ...
            T.total_wall_time_s, T.solver_self_report_wall_s);
        R(i).accounting = confbench_accounting(R(i).times, ...
            R(i).accounting.timing_accounting_tolerance_s, ...
            R(i).accounting.timing_accounting_tolerance_rel, ...
            R(i).accounting.independent_crosscheck_tolerance_rel);
    end
end
% Carry the historical method caveats, not the current production preset's.
cav = source.caveats;
current = confbench_caveats();
cav.other_column = [current.other_column ' This table was refreshed from recorded ' ...
    'timers without recomputation. Proposed preparation is moved from the ' ...
    'original Time 1 into Other; total wall times are unchanged. The source ' ...
    'JSON, manifest and notes retain their original timing schema.'];
cav.omega1_native_flag_tol = current.omega1_native_flag_tol;
cav.omega1_columns = ['omega_1 native is the recorded solver frequency; omega_1 E1 ' ...
    'is the recorded common-evaluator frequency. A dagger marks a native ' ...
    'value differing from E1 by more than 5 percent.'];
cav.sparse_step = 'No scaling fits or measurements were recomputed for this table refresh.';
files = confbench_export(struct('outputDir', campaignDir), R, struct(), struct(), ...
    struct('tables_only', true, 'caveats', cav));
end
