function checks = confbench_olhoff_assertions(presetName, mc, tag)
%CONFBENCH_OLHOFF_ASSERTIONS  Field-by-field benchmark assertions for ONE named preset.
%
%   checks = CONFBENCH_OLHOFF_ASSERTIONS(presetName, mc, tag) returns a struct
%   array (name, pass, detail) asserting that mc -- the Olhoff method config from
%   CONFBENCH_METHOD_CONFIG: the flat view with the canonical configuration in
%   mc.canonical -- realizes exactly the formulation of presetName.
%
%   Each preset has its OWN explicit expectations.  No assertion accepts either
%   formulation: run against the other preset's configuration, the
%   formulation-specific checks fail (proved by CONFBENCH_SELFTEST T13).  A
%   preset without a defined assertion set is refused.
%
%   Reads fields directly (no olh package needed on the path).
%
%   See also CONFBENCH_PREFLIGHT, CONFBENCH_OLHOFF_PRESET, OLHOFFCURRENT_PRESETS.

if nargin < 3, tag = sprintf('%dx%d', mc.nelx, mc.nely); end
k = mc.canonical;
c = mc;
g = @(p) dotGet(k, p);
checks = struct('name', {}, 'pass', {}, 'detail', {});

% ---- shared numerics: identical in every preset ----------------------------
checks = add(checks, ['Olhoff ' tag ': resolved from the named preset ' presetName], ...
    isfield(k, 'provenance') && isfield(k.provenance, 'olhoffCurrentPreset') && ...
    strcmp(k.provenance.olhoffCurrentPreset, presetName), ...
    sprintf('cfg.provenance.olhoffCurrentPreset=%s', fieldOr(k.provenance, 'olhoffCurrentPreset', '<absent>')));
checks = add(checks, ['Olhoff ' tag ': genuine nested MMA sub-optimization'], ...
    strcmp(c.innerSolver,'mma') && strcmp(c.innerVar,'drho') && ...
    strcmp(c.mmaVariant,'published') && c.offDiag, ...
    sprintf('innerSolver=%s innerVar=%s mmaVariant=%s offDiag=%d', ...
        c.innerSolver, c.innerVar, c.mmaVariant, c.offDiag));
checks = add(checks, ['Olhoff ' tag ': fixed subspace multiplicity, subN = 2'], ...
    strcmp(c.multRule,'subspace') && c.subN == 2, ...
    sprintf('multRule=%s subN=%d (no threshold classifier)', c.multRule, c.subN));
rminEl = c.rminPhys/(c.b/c.nely);
checks = add(checks, ['Olhoff ' tag ': fixed physical filter R = 0.06 on all f_sk'], ...
    c.rminPhys == 0.06 && isnan(c.rminEl) && abs(rminEl - 0.06*c.nely) < 1e-12 && ...
    strcmp(c.filterMode,'all') && strcmp(g('filter.type'),'sensitivity'), ...
    sprintf('rminPhys=%.10g -> rminEl=%.10g (derived at run time), filterMode=%s', ...
        c.rminPhys, rminEl, c.filterMode));
checks = add(checks, ['Olhoff ' tag ': tolInner = 0.05, 5..500'], ...
    c.tolInner == 0.05 && c.minInner == 5 && c.maxInner == 500, ...
    sprintf('tolInner=%.10g maxInner=%d minInner=%d', c.tolInner, c.maxInner, c.minInner));
checks = add(checks, ['Olhoff ' tag ': p = 3 fixed, rho_min = 1e-3, maxCluster = 4'], ...
    c.p == 3 && ~isfield(c,'pSchedule') && c.rhomin == 1e-3 && c.Nmax == 4, ...
    sprintf('p=%g pSchedule=%d rhomin=%g Nmax=%d', c.p, isfield(c,'pSchedule'), c.rhomin, c.Nmax));
epsRms = c.tolOuter/sqrt(c.nelx*c.nely);

switch presetName
    case 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered'
        checks = add(checks, ['Olhoff ' tag ': Pedersen low-density stiffness, threshold 0.1'], ...
            strcmp(g('material.stiffness.model'),'pedersen') && g('material.stiffness.linearBelow') == 0.1 && ...
            isfield(c,'stiffModel') && strcmp(c.stiffModel,'pedersen') && c.stiffLinearBelow == 0.1, ...
            sprintf('material.stiffness.model=%s linearBelow=%g', g('material.stiffness.model'), ...
                g('material.stiffness.linearBelow')));
        checks = add(checks, ['Olhoff ' tag ': linear mass, eq. (2)'], ...
            strcmp(g('material.mass.model'),'eq2') && strcmp(c.massInterp,'lin') && ...
            ~g('material.mass.continuation.enabled'), ...
            sprintf('material.mass.model=%s massInterp=%s', g('material.mass.model'), c.massInterp));
        checks = add(checks, ['Olhoff ' tag ': adaptive per-element move box 0.10 / 0.002 / x1.2 / x0.7'], ...
            strcmp(g('move.policy'),'adaptive') && strcmp(c.moveFamily,'SA') && c.move == 0.10 && ...
            c.moveMin == 0.002 && isfield(c,'sAGrow') && c.sAGrow == 1.2 && c.sAShrink == 0.7, ...
            sprintf('move.policy=%s moveFamily=%s move0=%g moveMin=%g grow=%s shrink=%s', ...
                g('move.policy'), c.moveFamily, c.move, c.moveMin, num2str(fieldOr(c,'sAGrow',NaN)), ...
                num2str(fieldOr(c,'sAShrink',NaN))));
        checks = add(checks, ['Olhoff ' tag ': stage exhaustion disabled (move and stop)'], ...
            ~strcmp(g('move.continuation.signal'),'stageExhaustion') && ...
            strcmp(g('stop.rule'),'designChange') && ~isfield(c,'stopRule') && ...
            ~strcmp(c.s2Signal,'exhaustion'), ...
            sprintf('move.continuation.signal=%s stop.rule=%s', g('move.continuation.signal'), g('stop.rule')));
        checks = add(checks, ['Olhoff ' tag ': natural design-change stop, no guards'], ...
            strcmp(c.outerNorm,'l2') && abs(epsRms - 0.05/sqrt(3200)) < 1e-15 && ...
            strcmp(c.outerGuard,'none') && ~isfield(c,'boxInactive') && ~isfield(c,'settledWindow') && ...
            ~isfield(c,'restorationGuard') && ~g('stop.guards.ladderExhausted') && ...
            ~g('stop.guards.maxDesignChange') && g('stop.guards.boxInactiveFraction') == 0, ...
            sprintf(['||drho||_2 < %.10g, i.e. per-element RMS < %.9e (constant across ' ...
                'meshes); guard=%s'], c.tolOuter, epsRms, c.outerGuard));
        checks = add(checks, ['Olhoff ' tag ': outer cap 400, no projection, inner asymptotes reset per outer'], ...
            c.maxOuter == 400 && ~g('projection.enabled') && ...
            strcmp(g('optimizer.inner.asymptoteHistory'),'inner') && ~isfield(c,'innerAsy'), ...
            sprintf('maxOuter=%d projection=%d asymptoteHistory=%s', c.maxOuter, ...
                g('projection.enabled'), g('optimizer.inner.asymptoteHistory')));
    case 'duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered'
        % the historical benchmark assertions, retained under the historical preset
        checks = add(checks, ['Olhoff ' tag ': SIMP stiffness with eq. (4b) mass'], ...
            strcmp(g('material.stiffness.model'),'simp') && ~isfield(c,'stiffModel') && ...
            strcmp(g('material.mass.model'),'eq4b') && strcmp(c.massInterp,'4b'), ...
            sprintf('material.stiffness.model=%s material.mass.model=%s', ...
                g('material.stiffness.model'), g('material.mass.model')));
        checks = add(checks, ['Olhoff ' tag ': outer RMS stopping semantics'], ...
            strcmp(c.outerNorm,'l2') && abs(epsRms - 0.05/sqrt(3200)) < 1e-15 && ...
            strcmp(c.outerGuard,'settledmove') && strcmp(g('stop.rule'),'designChange'), ...
            sprintf(['||drho||_2 < %.10g, i.e. per-element RMS < %.9e (constant ' ...
                'across meshes); guard=%s'], c.tolOuter, epsRms, c.outerGuard));
        % The stall SIGNAL is checked by value, not by field absence.
        s2sig = 'beta';
        if isfield(c,'s2Signal') && ~isempty(c.s2Signal); s2sig = char(c.s2Signal); end
        checks = add(checks, ['Olhoff ' tag ': S2 continuation realization as frozen'], ...
            strcmp(c.moveFamily,'S2') && isequal(c.s2Levels,[0.04 0.02 0.01 0.005]) && ...
            c.move == 0.04 && c.s2Window == 10 && c.s2Tol == 5e-3 && strcmp(s2sig,'beta'), ...
            sprintf(['moveFamily=%s move0=%.4g ladder=%s window=%d tol=%.4g; ' ...
                's2Signal=%s (the design-driven ''drms'' trigger was measured ' ...
                'and NOT adopted)'], ...
                c.moveFamily, c.move, mat2str(c.s2Levels), c.s2Window, c.s2Tol, s2sig));
    otherwise
        checks = add(checks, ['Olhoff ' tag ': preset has benchmark assertions'], false, ...
            sprintf('no benchmark assertions are defined for %s; refusing to run it', presetName));
end
checks = add(checks, ['Olhoff ' tag ': single thread and diagnostics off'], ...
    c.threads == 1 && ~c.diag, ...
    sprintf(['threads=%d diag=%d (the per-iteration recorder is proved ' ...
        'bitwise inert and is off so it is not timed)'], c.threads, c.diag));
end

function checks = add(checks, name, ok, detail)
checks(end+1) = struct('name', name, 'pass', logical(ok), 'detail', char(string(detail)));
end

function v = dotGet(S, dotted)
parts = strsplit(dotted, '.');
v = getfield(S, parts{:}); %#ok<GFLD>
end

function v = fieldOr(S, name, dflt)
if isstruct(S) && isfield(S, name); v = S.(name); else; v = dflt; end
end
