function c = confbench_caveats()
%CONFBENCH_CAVEATS  Text that must travel with the results, in one place.
%
%   These strings go into the JSON metadata, the generated benchmark notes and
%   the LaTeX caption.  They are written once here so the table, the file and
%   the slide cannot drift apart.

c = struct();

c.table_caption = ['Count/time columns represent method-native computational ' ...
    'stages and are not mathematically identical across methods. Total wall ' ...
    'time is the common performance quantity.'];

c.olhoff = olhoffm4_caveat();

c.olhoff_label = ['The Olhoff column is labelled "Du-Olhoff reconstruction ' ...
    '(M4)" and must not be labelled "Olhoff 2007".'];

c.memory = ['Reliable, method-independent peak-memory measurement was not ' ...
    'available in the MATLAB environment; memory was omitted rather than ' ...
    'reported with inconsistent semantics.'];

c.olhoff_iteration_counts = ['The outer iteration count of the Du-Olhoff ' ...
    'reconstruction depends on a move-limit continuation schedule that the ' ...
    'original publication does not specify. The frozen schedule used here ' ...
    'is documented; a different admissible schedule changes the count ' ...
    'without changing the physics.'];

c.scaling = ['Scaling exponents may be fitted only to complete campaign data ' ...
    'and never to smoke or preflight runs. For the Du-Olhoff reconstruction ' ...
    'the source audit records that its outer iteration count is an artifact ' ...
    'of the continuation trigger, so a fitted exponent for that method ' ...
    'describes this reconstruction, not the published method.'];
end
