function c = confbench_caveats()
%CONFBENCH_CAVEATS  Text that must travel with the results, in one place.
%
%   These strings go into the JSON metadata, the generated benchmark notes and
%   the LaTeX caption.  They are written once here so the table, the file and
%   the slide cannot drift apart.

c = struct();

c.table_caption = ['Count/time columns represent method-native computational ' ...
    'stages and are not mathematically identical across methods. Total wall ' ...
    'time is the common performance quantity.'];

olhPreset = olhoffcurrent_preset(confbench_olhoff_preset());
c.olhoff = olhoffcurrent_caveat(olhPreset.name);

c.olhoff_label = sprintf(['The Olhoff column is labelled "%s" and must not be ' ...
    'labelled "Olhoff 2007". It is produced by analysis/OlhoffCurrent at the named ' ...
    'preset %s (upstream preset %s @ %s). It is NOT the historical SIMP + eq. (4b) ' ...
    'realization that earlier campaigns labelled "Du-Olhoff reconstruction (M4)" ' ...
    '(preset duOlhoffSimpEq4bBetaStallLadderSensitivityFiltered): the two differ in ' ...
    'the low-density material law and the outer controller.'], olhPreset.displayName, ...
    olhPreset.name, olhPreset.upstreamPreset, olhPreset.upstreamCommit(1:7));

c.memory = ['Reliable, method-independent peak-memory measurement was not ' ...
    'available in the MATLAB environment; memory was omitted rather than ' ...
    'reported with inconsistent semantics.'];

switch olhPreset.name
    case 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered'
        c.olhoff_iteration_counts = ['The outer iteration count of the Du-Olhoff ' ...
            'reconstruction is set by its per-element adaptive move box and its ' ...
            'mesh-scaled design-change tolerance, neither of which the original ' ...
            'publication specifies, and it is NOT monotone in the mesh (committed ' ...
            'R = 0.06 sweep: 121, 111, 101, 93, 112, 130, 156, 204, 246 outer ' ...
            'iterations from 160x20 to 800x100). Per-outer-iteration cost is ' ...
            'therefore reported next to total wall time.'];
    otherwise
        c.olhoff_iteration_counts = ['The outer iteration count of the Du-Olhoff ' ...
            'reconstruction depends on a move-limit continuation schedule that the ' ...
            'original publication does not specify. The frozen schedule used here ' ...
            'is documented; a different admissible schedule changes the count ' ...
            'without changing the physics.'];
end

c.scaling = ['Scaling exponents may be fitted only to complete campaign data ' ...
    'and never to smoke or preflight runs. For the Du-Olhoff reconstruction ' ...
    'the outer iteration count is a property of the reconstruction''s controller ' ...
    'and stop, not of the published method, and need not be monotone in the ' ...
    'mesh; a total-time exponent mixes per-iteration cost with that count, so ' ...
    'the per-outer-iteration cost fit is reported alongside it. Either exponent ' ...
    'describes this reconstruction, not the published method.'];
end
