function audit_run_variant(tag,bcType,nelx,nely,rmin,formulation,optimizer,maxOuter,ov)
%AUDIT_RUN_VARIANT  Diagnostic run with explicit, logged deviations from the
%   repository's regularized defaults.  Deviations live in OV and are recorded
%   in the saved meta so no diagnostic can be mistaken for a production result.
repo='/Users/piotrek/Programming/topOpt4freqMax';
addpath(fullfile(repo,'analysis','OlhoffRegularized','Matlab'));
addpath(fullfile(repo,'analysis','OlhoffRegularized','audit','scripts'));
outDir=fullfile(repo,'analysis','OlhoffRegularized','audit','results',tag);
if exist(outDir,'dir')~=7,mkdir(outDir);end
runCfg=struct('optimizer',optimizer,'formulation',formulation,'verbose',true, ...
    'tol_mult',.05,'max_outer_iterations',maxOuter,'max_inner_iterations',500, ...
    'max_trial_steps',8,'move_min',1e-7,'move_max',.005, ...
    'accept_ratio',.10,'grow_ratio',.75, ...
    'density_tol',1e-4,'objective_tol',1e-5,'persistence',20, ...
    'progress_tolerance',1e-4,'progress_window',10, ...
    'progress_spike_tolerance',3e-4,'progress_dwell',20, ...
    'progress_shrink_factor',.5);
if strcmp(bcType,'cantilever'),runCfg.tip_mass_fraction=.20;end
fn=fieldnames(ov);for i=1:numel(fn),runCfg.(fn{i})=ov.(fn{i});end
fprintf('=== DIAGNOSTIC %s (deviations: %s) ===\n',tag,strjoin(fn',', '));
t=tic;[rho,omega,info]=topopt_olhoff_regularized(nelx,nely,.5,3,rmin,.005,bcType,runCfg);
wall=toc(t);
meta=struct('tag',tag,'bcType',bcType,'nelx',nelx,'nely',nely,'rmin',rmin, ...
  'formulation',formulation,'optimizer',optimizer,'maxOuter',maxOuter,'wall',wall, ...
  'diagnostic',true,'deviations',{fn},'matlab',version);
design=info.design;hist=info.history;status=info.status;stop_reason=info.stop_reason;
iterations=info.iterations;lambda=info.lambda;evlog=info.log;regcfg=info.regularization;
runcfg_used=info.cfg;
save(fullfile(outDir,'run.mat'),'rho','omega','design','hist','status','stop_reason', ...
  'iterations','lambda','evlog','meta','regcfg','runcfg_used','-v7.3');
audit_write_csv(fullfile(outDir,'trajectory.csv'),hist);
h=hist;
fprintf(['AUDITRESULT tag=%s status=%s stop=%s outer=%d accepted=%d rejected=%d inner=%d ' ...
 'contractions=%d w1=%.6f w2=%.6f w3=%.6f N=%d trust=%.3e ceil=%.3e dxInf=%.3e dxRms=%.3e ' ...
 'relObj=%.3e slope=%.3e vol=%.8f gray=%.4f wall=%.1f\n'],tag,status,stop_reason, ...
 iterations.outer,iterations.accepted_updates,iterations.rejected_trials,iterations.inner_total, ...
 iterations.move_ceiling_contractions,omega(1),omega(2),omega(3),h.N(end),h.trustNext(end), ...
 h.moveCeilingNext(end),h.densityChangeInf(end),h.densityChangeRms(end), ...
 h.relativeObjectiveChange(end),h.predictedSlope(end),mean(rho),4*mean(rho.*(1-rho)),wall);
end
