function audit_wp5_table(tags)
%AUDIT_WP5_TABLE  Per-run detail block required by WP5, from saved artifacts.
repo='/Users/piotrek/Programming/topOpt4freqMax';
base=fullfile(repo,'analysis','OlhoffRegularized','audit','results');
for i=1:numel(tags)
    t=tags{i};f=fullfile(base,t,'run.mat');
    if exist(f,'file')~=2,fprintf('\n### %s : NO run.mat\n',t);continue,end
    L=load(f);h=L.hist;it=L.iterations;m=L.meta;
    ctr=find(h.moveCeilingContracted);
    cs=NaN;sm=NaN;cn=NaN;
    if isfield(h,'certificateSlope'),cs=h.certificateSlope(end);cn=h.certificateN(end);sm=h.stationarityMeasure(end);end
    g=(h.omega(2:min(3,size(h.omega,1)),end)-h.omega(1,end))/h.omega(1,end);
    sf=fullfile(base,t,'stationarity.mat');asc=NaN;ratio=NaN;dom=NaN;Nx=NaN;
    if exist(sf,'file')==2
        W=load(sf);S=W.S;
        Nx=S.Nfor(1);
        if isfield(S,'selfConsistentN'),Nx=S.selfConsistentN;end
        k=find([S.cert.N]==Nx & abs([S.cert.radius]-5e-3)<1e-12,1);
        if ~isempty(k),asc=S.cert(k).relGain;end
        j=find([S.phys.N]==Nx & abs([S.phys.t]-1e-5)<1e-12,1);
        if ~isempty(j),ratio=S.phys(j).ratio;dom=S.phys(j).actDomega;end
    end
    fprintf(['\n### %s  (%s %dx%d, rmin=%g, %s/%s)\n' ...
      '  status                        : %s (%s)\n' ...
      '  outer / max_outer             : %d / %d      CAP? %s\n' ...
      '  accepted updates              : %d\n' ...
      '  rejected trials               : %d\n' ...
      '  total inner MMA iterations    : %d   (max per outer %d, cap %d, cap hits %d)\n' ...
      '  final omega1/2/3              : %.6f / %.6f / %.6f\n' ...
      '  final gaps (w_j-w_1)/w_1      : %s\n' ...
      '  final N (step model / cert)   : %d / %g   ; independent exact N = %g\n' ...
      '  final trust / move ceiling    : %.4e / %.4e\n' ...
      '  ceiling contractions          : %d   at outer %s\n' ...
      '  final max|drho| / RMS drho    : %.4e / %.4e\n' ...
      '  final relative objective chg  : %.4e\n' ...
      '  final route slope / certificate / statMeasure : %.4e / %.4e / %.4e\n' ...
      '  independent max feasible ascent (relative dlambda, one step of 5e-3) : %.4e\n' ...
      '  physical fixed-t check at t=1e-5 : actual/predicted = %.4f, actual domega1 = %+.4e\n' ...
      '  volume: mean(rho)=%.10f  residual=%.3e  range over run [%.10f, %.10f]\n' ...
      '  grayness 4*mean(rho(1-rho))   : %.4f\n' ...
      '  wallclock                     : %.1f s\n'], ...
      t,m.bcType,m.nelx,m.nely,m.rmin,m.formulation,m.optimizer, ...
      L.status,L.stop_reason,it.outer,m.maxOuter,localYN(strcmp(L.status,'CAP_HIT')), ...
      it.accepted_updates,it.rejected_trials,it.inner_total,max(h.innerIterations), ...
      L.runcfg_used.maxInner,sum(h.innerIterations>=L.runcfg_used.maxInner), ...
      L.omega(1),L.omega(2),L.omega(3),mat2str(g(:).',5),h.N(end),cn,Nx, ...
      h.trustNext(end),h.moveCeilingNext(end),it.move_ceiling_contractions, ...
      mat2str(ctr(:).'),h.densityChangeInf(end),h.densityChangeRms(end), ...
      h.relativeObjectiveChange(end),h.predictedSlope(end),cs,sm,asc,ratio,dom, ...
      mean(L.rho),sum(L.rho)-0.5*numel(L.rho),min(h.volume),max(h.volume), ...
      4*mean(L.rho.*(1-L.rho)),m.wall);
    if isfield(it,'negative_predictions')
        fprintf('  negative predicted improvements (model failures) : %d\n',it.negative_predictions);
    end
end
end
function s=localYN(t),if t,s='YES';else,s='no';end,end
