function audit_write_csv(f,h)
K=numel(h.outerIteration);fid=fopen(f,'w');
fprintf(fid,['outer,omega1,omega2,omega3,N,multJ,trustUsed,trustNext,ceilUsed,ceilNext,' ...
 'trials,inner,innerConv,accepted,ratio,predicted,actual,predSlope,' ...
 'certSlope,statMeasure,certN,certRelGain,certLpFlag,dxInf,dxRms,' ...
 'volume,objective,relObj,statPass,convCount,acceptedSinceContract,' ...
 'winCumProg,winMaxStep,winReady,winStatPass,ceilContracted\n']);
for k=1:K
 fprintf(fid,'%d,%.10g,%.10g,%.10g,%d,%d,%.6e,%.6e,%.6e,%.6e,%d,%d,%d,%d,%.6e,%.10e,%.10e,%.6e,%.6e,%.6e,%d,%.10e,%d,%.6e,%.6e,%.10g,%.12g,%.6e,%d,%d,%d,%.6e,%.6e,%d,%d,%d\n', ...
  h.outerIteration(k),h.omega(1,k),h.omega(2,k),h.omega(min(3,size(h.omega,1)),k),h.N(k),h.multJ(k), ...
  h.trustUsed(k),h.trustNext(k),h.moveCeilingUsed(k),h.moveCeilingNext(k),h.trialCount(k), ...
  h.innerIterations(k),h.innerConverged(k),h.accepted(k),h.acceptanceRatio(k), ...
  h.predictedImprovement(k),h.actualImprovement(k),h.predictedSlope(k), ...
  h.certificateSlope(k),h.stationarityMeasure(k),h.certificateN(k), ...
  h.certificateRelativeGain(k),h.certificateLpFlag(k),h.densityChangeInf(k), ...
  h.densityChangeRms(k),h.volume(k),h.objective(k),h.relativeObjectiveChange(k), ...
  h.stationarityPass(k),h.convergenceCount(k),h.acceptedSinceMoveContraction(k), ...
  h.windowCumulativeProgress(k),h.windowMaxStepProgress(k),h.progressWindowReady(k), ...
  h.progressStationarityPass(k),h.moveCeilingContracted(k));
end
fclose(fid);
end
