function out = tr_finalize()
%TR_FINALIZE  Declare this closure study's evidence and write its manifests.
%
%   This study produces NO scientific run, so it declares no raw trajectory of
%   its own.  Its required evidence is the audit output that supports its
%   verdicts, plus the immutable artifacts it REUSED -- declared so a later
%   reader can re-verify the reuse without re-running anything.

here  = fileparts(mfilename('fullpath'));
study = fileparts(here);
root  = fileparts(fileparts(study));
repo  = fileparts(fileparts(root));
addpath(root); addpath(here);
guard = olhoffcurrent_paths(); %#ok<NASGU>

STUDY = 'three_rung_promotion_closure';

items = {
 'evidence/inventory.json',        'required', 'Phase 0/1/2 inventory, reuse check and C240 precondition'
 'evidence/blockers.json',         'required', 'Phase 6 gate output and the enumerated remaining blockers'
 'evidence/policy_recovery.json',  'required', 'Phase 7/8/12 validated-policy recovery, promotion delta, dispatch'
 'evidence/software_tests.json',   'required', 'Phase 15 test results, including the explicit skip'
 'evidence/two_branch_FINAL_SHA256.BEFORE.txt', 'required', ...
   'the historical hash manifest exactly as found, archived before repair'
 'evidence/preserved_working_copies/C320x40_iterations.WORKING_COPY.csv', 'required', ...
   'timing-drifted working copy, archived before restoration (tOuter-only)'
 'evidence/preserved_working_copies/C320x40_record.WORKING_COPY.json', 'required', ...
   'timing-drifted working copy, archived before restoration (wall_s/bytes/matlab)'
 'analysis/OlhoffCurrent/diagnostics/three_rung_promotion_validation_retry1/METRICS.json', ...
   'required', 'the REUSED validated scientific verdict -- no new run'
 'analysis/OlhoffCurrent/diagnostics/three_rung_promotion_validation_retry1/FINAL_SHA256.txt', ...
   'required', 'the reused study''s self-verifying manifest'
 'analysis/OlhoffCurrent/evidence/three_rung_promotion_validation_retry1/C320x40_three_rung_trajectory.mat', ...
   'optional', ['the validated C320 three-rung trajectory.  OPTIONAL here because this ' ...
                'study reuses its VERDICT, verified via the retry''s own gate, and ' ...
                'never re-reads the raw container.']
};
D = olhoffcurrent_evidence_declare(study, STUDY, items, 'RepoRoot', repo, ...
      'Extra', struct( ...
        'implTree', olhoffcurrent_source_manifest('Verify',false).treeHash, ...
        'scientific_runs', 0, ...
        'promoted', false, ...
        'reused_verdict', 'THREE_RUNG_PRODUCTION_POLICY_VALIDATED', ...
        'reused_from', 'diagnostics/three_rung_promotion_validation_retry1'));
fprintf('[tr_finalize] EVIDENCE.json: %d artifacts\n', numel(D.artifacts));

inv = jsondecode(fileread(fullfile(study,'evidence','inventory.json')));
pol = jsondecode(fileread(fullfile(study,'evidence','policy_recovery.json')));
sw  = jsondecode(fileread(fullfile(study,'evidence','software_tests.json')));
blk = jsondecode(fileread(fullfile(study,'evidence','blockers.json')));

M = struct();
M.study = STUDY;
M.scientific_runs = 0;
M.nine_mesh_runs = 0;
M.promoted = false;
M.outcome_driven_repair = false;
M.repo = struct('branch','benchmark-methodology-r2', ...
    'startHead','60f5b72519aeba942b650d5408339f7ffe6b978b', ...
    'finalHead', local_head(repo), 'commitCreated', false);
M.implTree = inv.implTree;
M.currentness = inv.currentness;
M.production = struct('presetName', inv.presetName, 'upstreamPreset', inv.upstreamPreset, ...
    'cfgHash320', inv.prodCfgHash320, 'policy', inv.prodPolicy, 'promoted', false);
M.controllerHashes = inv.controllerHashes;
M.reused = struct('from','three_rung_promotion_validation_retry1', ...
    'verdict','THREE_RUNG_PRODUCTION_POLICY_VALIDATED', ...
    'note','REUSED - NO NEW SCIENTIFIC RUN', ...
    'gateOk', inv.retry1.gate.ok, 'run', inv.retry1.run, ...
    'anchors', inv.retry1.anchors, 'cost', inv.retry1.cost);
M.c240 = inv.c240;
M.repairs = struct( ...
  'final_sha256', struct('applied', true, ...
     'old','2fb9fc731d816e5c47c9835d5f777f8bb3be2fe61773ca00119049ed2bf5e0e0', ...
     'new','a7ef91f9cc279b46288f25f6f453495c5d358d96e1ff5ad33a8d87e61c73bd3e', ...
     'entriesChanged', 3, 'entriesTotal', 71), ...
  'timing_drift', struct('applied', true, 'paths', ...
     {{'runs/C320x40_iterations.csv','runs/C320x40_record.json'}}, ...
     'archived', true), ...
  'architecture_evidence_json', struct('applied', false, ...
     'reason','brief scopes Phase 4 to ONLY FINAL_SHA256.txt; no gate effect'));
M.promotionDelta = pol.policyDelta;
M.unexpectedDelta = pol.unexpectedDelta;
M.candidateCfgHash = pol.candCfgHash;
M.candidateMatchesValidatedRun = pol.candMatchesValidatedRun;
M.dispatch = struct('assertPass', pol.dispatchOk, ...
    'allUnderProduction', pol.dispatchAllProduction, ...
    'implTreeMatchesValidatedRun', pol.implTreeMatchesValidatedRun);
M.gates = blk;
M.tests = sw;
M.verdicts = struct( ...
  'c240_transfer',        'ORIGINAL_C240_EVIDENCE_TRANSFER_FAIL', ...
  'historical_hash',      'HISTORICAL_FINAL_SHA256_REPAIR_PASS', ...
  'timing_drift',         'TIMING_ONLY_DRIFT_SETTLED_PASS', ...
  'promotion_provenance', 'PROMOTION_PROVENANCE_BLOCKED', ...
  'policy',               'THREE_RUNG_PRODUCTION_POLICY_VALIDATED [REUSED - NO NEW SCIENTIFIC RUN]', ...
  'promotion',            'PRODUCTION_THREE_RUNG_CONTROLLER_NOT_PROMOTED', ...
  'config_equivalence',   'PROMOTED_PRODUCTION_CONFIG_EQUIVALENCE_NOT_ASSESSED_PROMOTION_NOT_PERFORMED', ...
  'promotion_equivalence','THREE_RUNG_PROMOTION_EQUIVALENCE_NOT_ASSESSED_PROMOTION_NOT_PERFORMED', ...
  'production_freeze',    'PRODUCTION_FREEZE_FAIL', ...
  'campaign',             'NINE_MESH_PERFORMANCE_CAMPAIGN_BLOCKED');
M.remainingBlockers = { ...
  'evidence/three_rung_resolution_240/C240x30_trajectory.mat  REQUIRED_MISSING'; ...
  'evidence/two_branch_controller_validation/C160x20_trajectory.mat  container digest'; ...
  'evidence/two_branch_controller_validation/C320x40_trajectory.mat  container digest'; ...
  'evidence/two_branch_controller_validation/C400x50_trajectory.mat  container digest'; ...
  'evidence/move_activity_400/F400_400x50_trajectory.mat  container digest'; ...
  'evidence/move_activity_400/P400_400x50_trajectory.mat  container digest'; ...
  'three_rung_architecture/EVIDENCE.json stale baselines.json digest (analysed, deferred)'};
M.disclosures = { ...
  ['test_preset_equivalence (a pre-existing repository fixture that solves 160x20 ' ...
   'with the PRODUCTION preset) executed once before the skip rule was applied; ' ...
   'no scientific claim made from it, no artifact retained, no verdict affected']; ...
  ['Phase 4 and Phase 5 repairs were applied before PREREGISTRATION.md was written; ' ...
   'no production promotion was applied at any point, and both repairs are archived ' ...
   'and reversible']};
fid = fopen(fullfile(study,'METRICS.json'),'w'); c1 = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n', jsonencode(M,'PrettyPrint',true)); clear c1
fprintf('[tr_finalize] METRICS.json written\n');

DM = struct('manifest_schema','olhoff_current_data_manifest/1','study',STUDY, ...
    'generated', char(datetime('now','Format','yyyy-MM-dd''T''HH:mm:ssXXX','TimeZone','local')), ...
    'repo_head', local_head(repo), 'implTree', M.implTree, ...
    'scientific_runs', 0, 'promoted', false);
L = local_listStudy(study);
ent = struct('path',{},'bytes',{},'sha256',{},'kind',{});
for k = 1:numel(L)
    d = dir(L{k}); rel = strrep(L{k}(numel(study)+2:end), filesep, '/');
    ent(end+1) = struct('path',rel,'bytes',d.bytes, ...
        'sha256',olhoffcurrent_sha256_file(L{k}),'kind',local_kind(rel)); %#ok<AGROW>
end
DM.files = ent; DM.n_files = numel(ent);
DM.note = ['No runs/ directory: this study executed zero scientific runs. ' ...
           'The validated C320 evidence it reuses lives in ' ...
           'diagnostics/three_rung_promotion_validation_retry1 and is unmodified.'];
fid = fopen(fullfile(study,'DATA_MANIFEST.json'),'w'); c2 = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n', jsonencode(DM,'PrettyPrint',true));
fprintf('[tr_finalize] DATA_MANIFEST.json: %d files\n', numel(ent));
out = struct('evidence',numel(D.artifacts),'files',numel(ent));
end

function h = local_head(repo)
[s,o] = system(sprintf('git -C "%s" rev-parse HEAD', repo));
if s==0, h = strtrim(o); else, h = '<unavailable>'; end
end

function k = local_kind(rel)
if startsWith(rel,'scripts/'),      k = 'script';
elseif startsWith(rel,'evidence/'), k = 'evidence';
elseif endsWith(rel,'.json'),       k = 'manifest';
else,                               k = 'document'; end
end

function L = local_listStudy(study)
L = {}; d = dir(fullfile(study,'**','*'));
for k = 1:numel(d)
    if d(k).isdir, continue; end
    if strcmp(d(k).name,'FINAL_SHA256.txt') || strcmp(d(k).name,'.DS_Store'), continue; end
    L{end+1} = fullfile(d(k).folder, d(k).name); %#ok<AGROW>
end
L = sort(L);
end
