function ma4_export(P, csvPath)
%MA4_EXPORT  Write the per-iteration record, including the activity distribution.
d = fileparts(csvPath); if exist(d,'dir')~=7; mkdir(d); end
T = table(P.outer, P.omega1, P.omega2, P.gap12, P.volume, ...
          P.Mnd, P.gray, P.mid, P.move, P.stage, double(P.descent), ...
          P.maxAbs, P.rms, P.l2, P.ratio, P.Neff, ...
          P.uQuant(:,1), P.uQuant(:,2), P.uQuant(:,3), P.uQuant(:,4), ...
          P.uQuant(:,5), P.uQuant(:,6), P.uQuant(:,7), P.uQuant(:,8), ...
          P.uMean, P.uRMS, ...
          P.nActive(:,1), P.nActive(:,2), P.nActive(:,3), P.nActive(:,4), ...
          P.beta, P.nInner, double(P.innerConv), P.multN, P.degen, ...
    'VariableNames', {'outer','omega1','omega2','gap12','volume', ...
      'Mnd_pct','gray_frac','mid_frac','move','stage','moveDescent', ...
      'maxAbs','rms','l2','r_rho','Neff', ...
      'u_min','u_P50','u_P75','u_P90','u_P95','u_P975','u_P99','u_max', ...
      'u_mean','u_RMS', ...
      'nActive_1e4','nActive_epsRMS','nActive_1e3','nActive_1e2', ...
      'beta','nInner','innerConv','multN','degen'});
writetable(T, csvPath);
fprintf('[ma4_export] %s (%d rows, %d cols)\n', csvPath, height(T), width(T));
end
