function s = olhoffcurrent_caveat()
%OLHOFFCURRENT_CAVEAT  The epistemic caveat that must travel with every number.
%
%   This implementation is a RECONSTRUCTION of the Du & Olhoff (2007) method,
%   not a claimed reproduction of the authors' own code.  Numerical
%   continuation and inner-convergence details are incompletely specified in
%   the original publication, and roughly two thirds of the configuration
%   fields that determine a trajectory are reconstruction choices or later
%   modifications rather than published values.
%
%   It must be labelled "Du-Olhoff reconstruction", never "Olhoff 2007".

s = ['Du-Olhoff RECONSTRUCTION (class C): internally coherent and fully ' ...
     'documented, but not a claimed historical implementation. Numerical ' ...
     'continuation, filter radius, multiplicity tolerance and inner-loop ' ...
     'convergence are not specified in Du & Olhoff (2007) and are ' ...
     'reconstruction choices here. Must NOT be labelled "Olhoff 2007". ' ...
     'Field-level provenance (A/B/C/D) is documented in ' ...
     'analysis/OlhoffCurrent/+impl/architecture/docs/SCIENTIFIC_CONFIG_PROVENANCE.md ' ...
     'and is printed per-run by olh.config.describe.'];
end
