function S = pmg_preview(outJson)
%PMG_PREVIEW  Step 5C: resolve -- NEVER solve -- the production configuration for the
%   nine campaign meshes, through both the OlhoffCurrent API and the conference
%   harness route, and check that only mesh-bound rows differ.
here = fileparts(mfilename('fullpath'));
oc = fileparts(fileparts(fileparts(here)));
repo = fileparts(fileparts(oc));
restoredefaultpath; addpath(here); addpath(oc);
addpath(fullfile(repo, 'examples', 'Performance')); addpath(fullfile(repo, 'examples', 'Performance', 'conference_bench'));
addpath(fullfile(repo, 'tools', 'Matlab')); addpath(fullfile(repo, 'analysis', 'three_method_parametric_study'));
olhoffcurrent_scrub_forbidden_paths(repo);
guard = olhoffcurrent_paths(); %#ok<NASGU>
NAME = 'duOlhoffPedersenAdaptiveBoxSensitivityFiltered';
M = [160 20; 240 30; 320 40; 400 50; 480 60; 560 70; 640 80; 720 90; 800 100];
prod = olhoffcurrent_production_preset();
info = olhoffcurrent_preset(NAME);
rows = olh.config.schema(); rows = rows(:, 1);
S = struct('preset', NAME, 'recorded_production_preset', prod.name, 'benchmark_preset', confbench_olhoff_preset(), ...
    'upstream_preset', info.upstreamPreset, 'upstream_commit', info.upstreamCommit, 'role', info.role, ...
    'n_schema_rows', numel(rows), 'solved', false, 'meshes', struct([]));
vals = cell(numel(rows), size(M, 1));
for i = 1:size(M, 1)
    nelx = M(i, 1); nely = M(i, 2);
    cfg = olhoffcurrent_config(nelx, nely, 'Preset', NAME);
    [mc, profId, prof] = confbench_method_config('olhoff', nelx, nely);
    for r = 1:numel(rows); vals{r, i} = olh.config.getPath(cfg, rows{r}); end
    g = @(p) olh.config.getPath(cfg, p);
    b = g('domain.b');
    m = struct('mesh', sprintf('%dx%d', nelx, nely), 'nelx', nelx, 'nely', nely, 'NE', nelx*nely, ...
        'config_hash', olhoffcurrent_config_hash(cfg), ...
        'harness_config_hash', prof.effective_config_hash, 'harness_profile_id', profId, ...
        'harness_preset', mc.olhoff_preset, 'provenance_preset', cfg.provenance.preset, ...
        'stiffness_model', g('material.stiffness.model'), 'linearBelow', g('material.stiffness.linearBelow'), ...
        'p', g('material.stiffness.p'), 'p_continuation', g('material.stiffness.continuation.enabled'), ...
        'p_continuation_driver', g('material.stiffness.continuation.driver'), ...
        'mass_model', g('material.mass.model'), 'mass_q', g('material.mass.q'), ...
        'mass_continuation', g('material.mass.continuation.enabled'), ...
        'filter_type', g('filter.type'), 'radiusPhysical', g('filter.radiusPhysical'), ...
        'radiusElements_row', g('filter.radiusElements'), 'domain_b', b, ...
        'radiusElements_derived', g('filter.radiusPhysical') / (b / nely), ...
        'projection', g('projection.enabled'), ...
        'move_policy', g('move.policy'), 'move_initial', g('move.initial'), 'move_minimum', g('move.minimum'), ...
        'adaptive_grow', g('move.adaptive.grow'), 'adaptive_shrink', g('move.adaptive.shrink'), ...
        'continuation_signal', g('move.continuation.signal'), ...
        'stop_rule', g('stop.rule'), 'stop_norm', g('stop.norm'), 'stop_toleranceRule', g('stop.toleranceRule'), ...
        'stop_tolerance', g('stop.tolerance'), 'stop_tolerance_expected', 0.05*sqrt(nelx*nely/3200), ...
        'guard_settledMove', g('stop.guards.settledMove'), 'guard_ladderExhausted', g('stop.guards.ladderExhausted'), ...
        'guard_maxDesignChange', g('stop.guards.maxDesignChange'), 'guard_boxInactiveFraction', g('stop.guards.boxInactiveFraction'), ...
        'inner_type', g('optimizer.inner.type'), 'inner_variable', g('optimizer.inner.variable'), ...
        'inner_variant', g('optimizer.inner.variant'), 'inner_tolerance', g('optimizer.inner.tolerance'), ...
        'inner_maxIterations', g('optimizer.inner.maxIterations'), 'multiplicity', g('multiplicity.method'), ...
        'maxCluster', g('eigen.maxCluster'), 'design_minimum', g('design.minimum'), 'volumeFraction', g('design.volumeFraction'), ...
        'maxOuter', g('runtime.maxOuter'), 'singleThread', g('runtime.singleThread'), 'diagnostics', g('runtime.diagnostics'));
    S.meshes = [S.meshes, m];
    fprintf('PREVIEW %-8s hash=%s harness=%s tol=%.6g R=%.3g rminEl=%.3g maxOuter=%d\n', m.mesh, m.config_hash, ...
        m.harness_config_hash(1:12), m.stop_tolerance, m.radiusPhysical, m.radiusElements_derived, m.maxOuter);
end
varying = {};
for r = 1:numel(rows)
    same = true;
    for i = 2:size(M, 1)
        if ~isequaln(vals{r, 1}, vals{r, i}); same = false; break; end
    end
    if ~same; varying{end+1} = rows{r}; end %#ok<AGROW>
end
S.rows_varying_across_meshes = varying;
allowed = {'domain.mesh.nelx', 'domain.mesh.nely', 'stop.tolerance', 'runtime.name'};
x = S.meshes;
S.checks = struct( ...
    'nine_meshes_resolved_not_solved', numel(x) == 9, ...
    'preset_is_recorded_production_and_benchmark', strcmp(prod.name, NAME) && strcmp(S.benchmark_preset, NAME) && all(strcmp({x.harness_preset}, NAME)), ...
    'harness_route_hash_equals_api_hash', all(strcmp({x.config_hash}, {x.harness_config_hash})), ...
    'only_mesh_bound_rows_vary', all(ismember(varying, allowed)), ...
    'stop_tolerance_is_mesh_scaled_rule', all(strcmp({x.stop_toleranceRule}, 'meshScaled')) && ...
        all(abs([x.stop_tolerance] - [x.stop_tolerance_expected]) <= 1e-15 * max(1, [x.stop_tolerance_expected])), ...
    'material_pedersen_linear_mass', all(strcmp({x.stiffness_model}, 'pedersen')) && all([x.linearBelow] == 0.1) && ...
        all(strcmp({x.mass_model}, 'eq2')) && all([x.mass_q] == 1), ...
    'no_eq4b', ~any(strcmp({x.mass_model}, 'eq4b')), ...
    'no_p_continuation', ~any([x.p_continuation]) && ~any([x.mass_continuation]), ...
    'no_projection', ~any([x.projection]), ...
    'fixed_physical_radius_0p06', all([x.radiusPhysical] == 0.06) && all(isnan([x.radiusElements_row])), ...
    'adaptive_box', all(strcmp({x.move_policy}, 'adaptive')) && all([x.move_initial] == 0.1) && ...
        all([x.move_minimum] == 0.002) && all([x.adaptive_grow] == 1.2) && all([x.adaptive_shrink] == 0.7), ...
    'natural_design_change_stop', all(strcmp({x.stop_rule}, 'designChange')) && ~any([x.guard_settledMove]) && ...
        ~any([x.guard_ladderExhausted]) && ~any([x.guard_maxDesignChange]), ...
    'no_stage_exhaustion', ~any(strcmp({x.continuation_signal}, 'stageExhaustion')) && ~any(strcmp({x.stop_rule}, 'stageExhaustion')), ...
    'nested_mma_no_socp', all(strcmp({x.inner_type}, 'mma')), ...
    'maxOuter_400_single_thread_no_diagnostics', all([x.maxOuter] == 400) && all([x.singleThread]) && ~any([x.diagnostics]), ...
    'distinct_hashes_per_mesh', numel(unique({x.config_hash})) == 9);
S.pass = all(struct2array(S.checks));
fid = fopen(outJson, 'w'); fwrite(fid, jsonencode(S, 'PrettyPrint', true)); fclose(fid);
disp(S.checks); fprintf('PREVIEW varying rows: %s\nPREVIEW PASS=%d\n', strjoin(varying, ', '), S.pass);
end
