function st = r240_finalize()
%R240_FINALIZE  Fail-closed retention for the three-rung architecture audit.
%
%   Declares the raw evidence this ZERO-RUN study depends on, writes
%   DATA_MANIFEST.json and a self-verifying FINAL_SHA256.txt, re-records
%   provenance, and runs OLHOFFCURRENT_FINALIZATION_GATE.  Read-only with
%   respect to +impl/ and to every trajectory.

here  = fileparts(mfilename('fullpath'));
study = fileparts(here);
root  = fileparts(fileparts(study));
repo  = fileparts(fileparts(root));
addpath(root); addpath(here);

M = jsondecode(fileread(fullfile(study,'METRICS.json')));

% ---- EVIDENCE.json: the raw trajectories, declared by immutable path -----
items = {
 'analysis/OlhoffCurrent/evidence/three_rung_resolution_240/C240x30_trajectory.mat', 'required', ...
   ['THE new raw evidence: 240x30 four-rung causal-controller trajectory produced by ' ...
    'the ONE authorized scientific run.  RHO 7200 x 1358, CONVERGED @1358.']
 'analysis/OlhoffCurrent/diagnostics/three_rung_resolution_240/runs/C240x30_iterations.csv', 'required', ...
   'Per-iteration telemetry for the new run, written by the unchanged cv_export.'
 'analysis/OlhoffCurrent/diagnostics/three_rung_resolution_240/runs/C240x30_record.json', 'required', ...
   'Scalar record for the new run: status, stage starts, descents, exhaustion struct, hashes.'
 'analysis/OlhoffCurrent/evidence/two_branch_controller_validation/C160x20_trajectory.mat', 'required', ...
   '160x20 causal trajectory: source of the rung-4 comparison at that mesh.'
 'analysis/OlhoffCurrent/evidence/two_branch_controller_validation/C320x40_trajectory.mat', 'required', ...
   '320x40 causal trajectory (CAP_HIT @1600).'
 'analysis/OlhoffCurrent/evidence/two_branch_controller_validation/C400x50_trajectory.mat', 'required', ...
   '400x50 causal trajectory.'
 'analysis/OlhoffCurrent/diagnostics/three_rung_architecture/METRICS.json', 'required', ...
   'The prior audit whose THRESHOLD_SPLITTING guard this run resolves.'
 'analysis/OlhoffCurrent/diagnostics/two_branch_controller_validation/scripts/cv_config.m', 'required', ...
   'THE controller, called unchanged to produce the new run.'
 'analysis/OlhoffCurrent/diagnostics/two_branch_controller_validation/scripts/cv_telemetry.m', 'required', ...
   'Telemetry, called unchanged.'
 'analysis/OlhoffCurrent/diagnostics/two_branch_controller_validation/scripts/cv_export.m', 'required', ...
   'CSV export, called unchanged.'
 'analysis/OlhoffCurrent/diagnostics/two_branch_maturity_240/METRICS.json', 'optional', ...
   'The prior FIXED-MOVE 240x30 arm; used only for the S1 cross-check (window begins 187).'};

extra = struct( ...
  'scientific_runs_executed', 1, ...
  'note', ['This study executed EXACTLY ONE optimization run (C240x30).  Its raw ' ...
           'trajectory is declared here; the prior trajectories it is compared against ' ...
           'are declared by immutable path and SHA-256 rather than copied.'], ...
  'preregistration_sha256', M.preregistration_sha256, ...
  'impl_tree_sha256', M.impl_tree_sha256, ...
  'architecture_verdict', M.verdicts.architecture, ...
  'next_step_verdict', M.verdicts.next_step, ...
  'counterfactual_verdict', M.verdicts.counterfactual, ...
  'threshold_splitting_verdict', M.verdicts.threshold_splitting, ...
  'scientific_runs_executed_note', 'exactly ONE: C240x30, CONVERGED @1358', ...
  'evidence_gaps', {{ ...
     ['no 240x30 PRODUCTION baseline exists; production-relative omega1/M_nd gates at ' ...
      'this mesh are UNAVAILABLE and are NOT imputed from another mesh'], ...
     ['two_branch_maturity_240 raw .mat artifacts are lost (pre-existing); only its ' ...
      'hash-valid METRICS.json scalars were used, for the S1 cross-check'], ...
     'wall-clock time: s/inner drifts 5.63x within the new run; down-weighted, never decisive', ...
     'two_branch_maturity_240 finalization gate FAILS (pre-existing); only its hash-valid PREREGISTRATION.md is used'}});

olhoffcurrent_evidence_declare(study, 'three_rung_resolution_240', items, ...
    'EvidenceRoot', 'analysis/OlhoffCurrent/evidence/two_branch_controller_validation', ...
    'RepoRoot', repo, 'Extra', extra);

% ---- FINAL_SHA256.txt, pass 1: so the study's OWN finalization gate can pass
% before r240_provenance('final') evaluates it.  Without this the final record
% would report a failure created purely by write ordering.
local_writeHashes(study);

% ---- provenance at end -------------------------------------------------
% Now G1-G5 are all satisfiable for this study, so test_finalization_gate sees
% no new deficient study and the recorded testsPass is a real pass.
r240_provenance('final');

% ---- DATA_MANIFEST.json: every artifact THIS study produced -------------
% Everything except FINAL_SHA256.txt, which is the outer hash file and is
% rewritten last, over the manifest itself.
own = local_ownFiles(study);
own = own(~strcmp(own,'FINAL_SHA256.txt'));
arts = {};
for i = 1:numel(own)
    rel = own{i};
    f = fullfile(study, rel);
    d = dir(f);
    arts{end+1} = struct('path', ['analysis/OlhoffCurrent/diagnostics/three_rung_resolution_240/' rel], ...
        'role', local_role(rel), 'bytes', d(1).bytes, ...
        'sha256', olhoffcurrent_sha256_file(f), 'tracked', true); %#ok<AGROW>
end
DM = struct('schema','olhoff_three_rung_resolution_240_manifest/1', ...
    'study','three_rung_resolution_240', ...
    'generated', char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss''Z''')), ...
    'scientific_runs_executed', 1, ...
    'note', ['No raw scientific data was produced.  The study depends on ' ...
             'Its raw trajectory and every dependency are declared in ' ...
             'EVIDENCE.json and verified by olhoffcurrent_evidence_gate.'], ...
    'verdicts', struct('counterfactual', M.verdicts.counterfactual, ...
                       'threshold_splitting', M.verdicts.threshold_splitting, ...
                       'architecture', M.verdicts.architecture, ...
                       'next_step', M.verdicts.next_step, ...
                       'production', 'PRODUCTION_CONTROLLER_NOT_CHANGED', ...
                       'campaign', 'NINE_MESH_PERFORMANCE_CAMPAIGN_BLOCKED'), ...
    'preregistration_sha256', M.preregistration_sha256, ...
    'artifacts', {arts});
fid = fopen(fullfile(study,'DATA_MANIFEST.json'),'w');
fwrite(fid, jsonencode(DM,'PrettyPrint',true)); fclose(fid);
fprintf('[manifest] DATA_MANIFEST.json  (%d artifacts)\n', numel(arts));

% ---- FINAL_SHA256.txt, pass 2: now covering the manifest and the final
% provenance record as well.  Self-verifying over everything but itself.
n = local_writeHashes(study);
fprintf('[hashes]  FINAL_SHA256.txt  (%d files)\n', n);

% ---- the gate ------------------------------------------------------------
st = olhoffcurrent_finalization_gate(study, 'RepoRoot', repo);
end

function n = local_writeHashes(study)
%LOCAL_WRITEHASHES  Write FINAL_SHA256.txt over every file in the study except
%   the hash file itself, so that the hash file is self-verifying (gate G4).
own = local_ownFiles(study);
own = own(~strcmp(own,'FINAL_SHA256.txt'));
lines = {};
lines{end+1} = '# FINAL_SHA256 -- three_rung_resolution_240';
lines{end+1} = sprintf('# generated %s', ...
    char(datetime('now','TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss''Z''')));
lines{end+1} = '# paths are relative to analysis/OlhoffCurrent/diagnostics/three_rung_resolution_240';
lines{end+1} = '# every path listed here must resolve and hash as recorded (gate G4)';
lines{end+1} = '';
for i = 1:numel(own)
    lines{end+1} = sprintf('%s  %s', ...
        olhoffcurrent_sha256_file(fullfile(study,own{i})), own{i}); %#ok<AGROW>
end
fid = fopen(fullfile(study,'FINAL_SHA256.txt'),'w');
fprintf(fid,'%s\n',lines{:}); fclose(fid);
n = numel(own);
end

function f = local_ownFiles(study)
d = dir(fullfile(study,'**','*'));
f = {};
for i = 1:numel(d)
    if d(i).isdir; continue; end
    if strcmp(d(i).name,'.DS_Store'); continue; end
    rel = strrep(erase(fullfile(d(i).folder,d(i).name), [study filesep]), filesep, '/');
    if contains(rel,'__pycache__'); continue; end
    f{end+1} = rel; %#ok<AGROW>
end
f = sort(f);
end

function r = local_role(rel)
if startsWith(rel,'figures/');       r = 'figure';
elseif startsWith(rel,'scripts/');   r = 'analysis code';
elseif startsWith(rel,'evidence/');  r = 'evidence';
elseif endsWith(rel,'.json');        r = 'metrics';
else;                                r = 'report';
end
end
