function outFile=evaluate_candidate_checkpoints(matFile,profileId,nelx,nely)
%EVALUATE_CANDIDATE_CHECKPOINTS Full R3 raw/binary E1-E3 and topology checks.
maxNumCompThreads(1);here=fileparts(mfilename('fullpath'));repo=fileparts(fileparts(here));
addpath(fullfile(repo,'analysis','three_method_parametric_study'));
S=load(matFile,'res');res=S.res;X=double(res.rho_snapshots);nDone=size(X,2)-1;
B=load(fullfile(repo,'analysis','olhoff_native_convergence','results',sprintf('development_%dx%d.mat',nelx,nely)),'res');
xRef=double(B.res.telemetry.rho_snapshots(:,end));xbRef=volume_binary(xRef);
base=readtable(fullfile(repo,'analysis','olhoff_fixed_budget_audit','checkpoint_metrics.csv'),'TextType','string');
br=base(base.mesh==sprintf('%dx%d',nelx,nely)&base.iteration==1600,:);
cp=unique([50 100 150 200 250 300 400 600 800 1200 nDone res.trigger_iterations res.trigger_iterations+50]);cp=cp(cp>=0&cp<=nDone);
rows=cell(numel(cp),43);
for i=1:numel(cp)
 k=cp(i);x=X(:,k+1);xb=volume_binary(x);ev=study_evaluate_design(x,nelx,nely,.5);
 if k<nDone
  w=res.hist.omega(:,k+1);N=res.hist.N(k+1);
 elseif strcmp(res.status,'CAP_HIT')
  w=res.omega;N=detect_n(w,res.cfg);
 else
  w=NaN(3,1);N=NaN;
 end
 gap=(w(2)-w(1))/w(1); loop=res.hist.tEig+res.hist.tGrad+res.hist.tInner;
 vals=[ev.omega_raw_E1(1),ev.omega_raw_E2(1),ev.omega_raw_E3(1),ev.omega_binary_E1(1),ev.omega_binary_E2(1),ev.omega_binary_E3(1)];
 refs=[br.common_raw_E1_omega1,br.common_raw_E2_omega1,br.common_raw_E3_omega1,br.common_binary_E1_omega1,br.common_binary_E2_omega1,br.common_binary_E3_omega1];loss=(refs-vals)./refs;
 rows(i,:)={string(upper(profileId)),string(sprintf('%dx%d',nelx,nely)),k,string(res.status), ...
  w(1),w(2),w(3),gap,N,res.hist.moveLimit(max(1,min(k,nDone))),res.hist.policyStage(max(1,min(k,nDone))), ...
  ev.volume_residual,ev.grayness,ev.gray_fraction_01_09,ev.connectivity_raw_05.left_right_connected, ...
  ev.connectivity_raw_05.n_components,ev.connectivity_binary.left_right_connected,ev.connectivity_binary.n_components, ...
  sqrt(mean((x-xRef).^2)),mean(xb~=xbRef),vals(1),vals(2),vals(3),vals(4),vals(5),vals(6), ...
  loss(1),loss(2),loss(3),loss(4),loss(5),loss(6),sum(loop(1:k)),sum(res.hist.tEig(1:k)), ...
  sum(res.hist.tInner(1:k)),mean(loop(1:k),'omitnan'),sum(res.hist.tEig(1:k))/max(sum(loop(1:k)),eps), ...
  nnz(res.hist.lpFlag(1:max(1,k))~=1),nnz(~res.hist.finiteOk(1:max(1,k))), ...
  nnz(abs(res.hist.volumeResidual(1:max(1,k)))>1e-6),numel(res.trigger_iterations), ...
  string(mat2str(res.trigger_iterations)),res.wallclock};
 fprintf('%s %dx%d checkpoint %d rawE1loss=%.4g binE1loss=%.4g\n',profileId,nelx,nely,k,loss(1),loss(4));
end
names={'profile','mesh','iteration','run_status','native_omega1','native_omega2','native_omega3','native_gap12','native_N', ...
 'move_limit','policy_stage','volume_residual','grayness','gray_fraction','raw_connected','raw_components','binary_connected','binary_components', ...
 'density_rms_to_baseline_k1600','binary_turnover_to_baseline_k1600','raw_E1_omega1','raw_E2_omega1','raw_E3_omega1', ...
 'binary_E1_omega1','binary_E2_omega1','binary_E3_omega1','raw_E1_loss','raw_E2_loss','raw_E3_loss','binary_E1_loss','binary_E2_loss','binary_E3_loss', ...
 'cumulative_loop_time_s','cumulative_eig_time_s','cumulative_inner_time_s','mean_iteration_time_s','eigensolve_share', ...
 'lp_failures','nonfinite_iterations','volume_failures','n_triggers','trigger_iterations','wallclock_s'};
T=cell2table(rows,'VariableNames',names);outFile=fullfile(here,'raw',sprintf('checkpoints_%s_%dx%d.csv',lower(profileId),nelx,nely));writetable(T,outFile);
end
function N=detect_n(w,cfg),N=1;while cfg.n+N<=numel(w)-1&&abs(w(cfg.n+N)-w(cfg.n))/w(cfg.n)<cfg.tolMult,N=N+1;end,end
function xb=volume_binary(x),n=round(.5*numel(x));[~,o]=sortrows([-x(:),(1:numel(x))'],[1 2]);xb=false(size(x));xb(o(1:n))=true;end
