#!/usr/bin/env python3
"""Generate SOURCE_TO_TARGET_FILE_MAP.md and CONFIG_COMPARISON.md from the JSON evaluations."""
import json
from sd_common import AUDIT, EVAL

ROLE = {
 'algo/genGrad.m': ('eq.(19) generalized gradients; stiffness law passed as struct', 'formulation hook: none for SIMP (bitwise); enables Pedersen derivative', 'PROMOTE (inert under SIMP) + NEW NAMED PRESET'),
 'algo/innerLoopRho.m': ("MMA on design variable; adds outer-history asymptotes", "none on executed paths (variable='increment'); refuted variant", 'DO NOT PROMOTE scientifically (arrives inert)'),
 'architecture/+olh/+config/describe.m': ('prints formulation', 'reporting', 'PROMOTE NOW (E)'),
 'architecture/+olh/+config/fromLegacy.m': ('legacy-name mapping', 'software; target adds exhaustion/stopRule, source adds SA/pedersen/innerAsy/guards', 'MERGE (both parents)'),
 'architecture/+olh/+config/schema.m': ('configuration schema', 'declares new options (both parents)', 'MERGE (both parents)'),
 'architecture/+olh/+config/toLegacy.m': ('flat rendering', 'software', 'MERGE (both parents)'),
 'architecture/+olh/+config/validate.m': ('validation rules', 'software; target: exhaustion coupling; source: adaptive/asymptote/Inf rules', 'MERGE (both parents)'),
 'architecture/+olh/+material/stiffnessInterpolation.m': ('SIMP / Pedersen (2000) eq.(5) value+derivative', 'NEW FORMULATION (D) when selected', 'PROMOTE AS NEW NAMED PRESET'),
 'architecture/+olh/+move/exhaustion.m': ('target stage-exhaustion detector E = A OR B', 'controller (C), target-local', 'KEEP (historical/diagnostic reproducibility)'),
 'architecture/+olh/+move/limit.m': ("move policy; target adds 'stageExhaustion' branch, source adds 'adaptive' branch + 5th arg rho", 'controller (C)', 'MERGE (both parents)'),
 'architecture/+olh/+presets/duOlhoffAdaptiveMove.m': ('SIMP/4b + adaptive box', 'reconstruction preset; spikes at 240/480/800', 'KEEP HISTORICAL ONLY (classify EXPERIMENT_PRESET)'),
 'architecture/+olh/+presets/duOlhoffAdaptivePedersen.m': ('the successful sweep realization', 'NEW FORMULATION + controller', 'PROMOTE AS NEW NAMED PRESET'),
 'architecture/+olh/+presets/duOlhoffOuterAsymptotes.m': ('outer-history asymptotes, fixed move', 'refuted by source (N1-N6)', 'DO NOT PROMOTE (classify EXPERIMENT_PRESET)'),
 'architecture/+olh/+presets/list.m': ('preset registry', 'reporting', 'PROMOTE with reclassification'),
 'architecture/docs/CONFIG_REFERENCE.md': ('generated reference', 'documentation', 'REGENERATE after merge'),
 'architecture/docs/PRESETS.md': ('preset docs', 'documentation', 'PROMOTE + add split statement'),
 'architecture/docs/SCIENTIFIC_CONFIG_PROVENANCE.md': ('field provenance', 'documentation', 'PROMOTE'),
 'architecture/olhoffSolve.m': ('canonical solver; source: stiffness struct, eig opts, vector box, aux, 2 guards; target: exhaustion + tOuter', 'controller + reporting; no arithmetic change on shared path (bitwise same-state identity)', 'MERGE (both parents), diff against both'),
 'fem/assemble2D.m': ('K,M assembly; stiffness law via stiffnessInterpolation', 'bitwise under SIMP; enables Pedersen', 'PROMOTE (inert under SIMP) + NEW NAMED PRESET'),
 'fem/eigSolve.m': ('eigs with opts pass-through (identical defaults)', 'software (bitwise)', 'PROMOTE NOW'),
}


def main():
    F = json.loads((EVAL / 'file_map.json').read_text())
    L = ['# SOURCE_TO_TARGET_FILE_MAP', '',
         'Three-way map: upstream base `695f03b` (what OlhoffCurrent was promoted from) → target `analysis/OlhoffCurrent/+impl` → source snapshot `6b08708`. Diff sizes are changed lines (+/−, `difflib`, context 0). Generated by `scripts/sd_tables.py` + `scripts/sd_docs_generated.py`; data `evaluations/file_map.json`.', '',
         f"Counts over the executable subset (algo, fem, filter, mma, mma_published, architecture/+olh, olhoffSolve.m, legacy, docs): **{F['counts']}**.", '',
         '## Files that differ or exist on one side only', '',
         '| path | status | target SHA-256 | source SHA-256 | Δ lines target↔source | base→target | base→source | semantic role | scientific effect | migration class |', '|---|---|---|---|---|---|---|---|---|---|']
    for r in F['rows']:
        if r['status'] == 'IDENTICAL':
            continue
        role, eff, mig = ROLE.get(r['path'], ('', '', ''))
        L.append(f"| `{r['path']}` | {r['status']} | `{(r['target_sha256'] or '—')[:16]}` | `{(r['source_sha256'] or '—')[:16]}` | {r['diff_lines_target_vs_source']} | {r['diff_lines_base_vs_target']} | {r['diff_lines_base_vs_source']} | {role} | {eff} | {mig} |")
    L += ['', 'Full 64-hex digests: `evaluations/file_map.json`.', '',
          '## The plan\'s "unchanged and not re-copied" claim', '',
          'Verified file by file: ' + ('**all 20 listed files are byte-identical** between target and source.' if F['plan_unchanged_claim_all_identical'] else '**FAILED**'), '',
          '| file | status |', '|---|---|'] + [f'| `{k}` | {v} |' for k, v in F['plan_unchanged_claim'].items()]
    L += ['', '## Reconciliation with the plan', '',
          '- Plan Phase 1 lists 15 modified + 4 new upstream files ("≈15"). The measured set is exactly **15 DIFFERENT + 4 SOURCE_ONLY**; nothing is missing and nothing extra differs.',
          '- **Target-local divergence from its own promoted base is 6 modified files + 1 new file** (`exhaustion.m`), not the "one adaptation" stated in `analysis/OlhoffCurrent/PROVENANCE.md` §3/§7, which still says 74 files. `SOURCE_MANIFEST.json` (75 files, `edbfe47…`) is correct; the prose provenance is stale. Four of the 15 differing files (`fromLegacy.m`, `schema.m`, `toLegacy.m`, `validate.m`, plus `limit.m` and `olhoffSolve.m`) changed on BOTH sides and need a three-way merge.',
          '- Semantic identity of the shared numerical path is not inferred from file status: it is proven bitwise at nine frozen states (FIRST_DIVERGENCE.md).', '',
          '## Identical files (59)', '', ', '.join(f"`{r['path']}`" for r in F['rows'] if r['status'] == 'IDENTICAL')]
    (AUDIT / 'SOURCE_TO_TARGET_FILE_MAP.md').write_text('\n'.join(L) + '\n')

    C = json.loads((EVAL / 'config_comparison.json').read_text())
    n = C['configs']
    L = ['# CONFIG_COMPARISON — effective configurations at 480×60', '',
         'Four configurations flattened leaf by leaf (`scripts/sd_config_dump.m`, `evaluations/effective_configs_480.json`):', '',
         '- **S480** — source committed run `repro/results/S480x60` (stored cfg), preset `duOlhoffAdaptivePedersen`.',
         '- **M1** — this audit\'s single run: source code, preset `duOlhoffAdaptiveMove` + `move.initial = 0.10`.',
         '- **C480** — target three-rung canary (stored cfg, hash `03097a28…` re-verified).',
         '- **PROD** — target canonical production resolved now by `olhoffcurrent_config(480,60)` (hash `a49417d0…`).', '',
         f"Leaves: {C['n_leaves']}; identical in all four: **{C['n_identical']}**; differing: {len(C['differing'])}.", '',
         '| leaf | S480 | M1 | C480 | PROD | kind |', '|---|---|---|---|---|---|']
    kind = lambda p: ('FORMULATION' if p.startswith('material.') else 'CONTROLLER' if p.startswith('move.') else
                      'STOPPING' if p.startswith('stop.') else 'RUNTIME' if p.startswith('runtime.') else
                      'METADATA' if p.startswith('provenance.') else 'INNER (inert on executed path)' if p.startswith('optimizer.') else 'OTHER')
    for d in C['differing']:
        L.append('| `' + d['path'] + '` | ' + ' | '.join(str(d[k]).replace('|', '/')[:60] for k in n) + f" | {kind(d['path'])} |")
    L += ['', '## Reading', '',
          '- **S480 vs M1:** only `material.stiffness.model` and `material.mass.model` among scientific leaves (M1 preflight, Amendment 1).',
          '- **M1 vs C480:** only controller (`move.policy`, `move.initial`, adaptive factors, continuation signal), stopping (`stop.rule`, guards) and runtime leaves. Every problem/physics leaf (material, filter, design, eigen, multiplicity, inner optimizer) is equal → D0 passes under M1.',
          '- **C480 vs PROD:** `move.levels` (3 vs 4 rungs), `move.continuation.signal`, `stop.rule`, `runtime.maxOuter`, diagnostics — the three-rung candidate has never been promoted (three_rung_promotion_closure: PRODUCTION_THREE_RUNG_CONTROLLER_NOT_PROMOTED).',
          '- Identical in all four (selection): `filter.radiusPhysical = 0.06`, `filter.type = sensitivity`, `filter.applyTo = all`, `stop.tolerance = 0.15`, `stop.norm = l2`, `design.initial = 0.5`, `design.minimum = 1e-3`, `design.volumeFraction = 0.5`, `material.stiffness.p = 3`, `multiplicity.method = subspace`, `subspaceSize = 2`, `diagonalOffsets = offDiagonal = true`, `optimizer.inner.{type=mma, variant=published, variable=increment, tolerance=0.05, minIterations=5, maxIterations=500}`, `eigen.{solver=eigs, tolerance=1e-12, maxIterations=5000, krylovFactor=4, maxCluster=4}`. Full list in `evaluations/config_comparison.json`.']
    (AUDIT / 'CONFIG_COMPARISON.md').write_text('\n'.join(L) + '\n')
    print('generated docs')


if __name__ == '__main__':
    main()
